(function (root) {
  const computedFeatureOrder = Object.freeze([
    "abs_irms_zscore_vs_baseline",
    "delta_irms_abs",
    "halfcycle_asymmetry",
    "suspicious_run_energy",
    "pulse_count_per_cycle",
    "zero_dwell_ratio",
    "low_current_ratio",
    "max_low_current_run_ms",
    "delta_hf_energy",
    "delta_flux",
    "midband_residual_ratio",
    "zcv",
    "spectral_flux_midhf",
    "peak_fluct_cv",
    "residual_crest_factor",
    "thd_i",
    "hf_energy_delta",
    "edge_spike_ratio",
    "v_sag_pct",
    "cycle_nmse",
  ]);

  const pwaFeatureOrder = Object.freeze([
    "pulse_count_per_cycle",
    "max_low_current_run_ms",
    "zero_dwell_ratio",
    "low_current_ratio",
    "thd_i",
    "spectral_flux_midhf",
    "hf_energy_delta",
    "residual_crest_factor",
    "peak_fluct_cv",
    "zcv",
    "delta_irms_abs",
    "midband_residual_ratio",
    "edge_spike_ratio",
  ]);

  const csvHeaderOrder = Object.freeze([
    "epoch_ms",
    "uptime_ms",
    "frame_start_uptime_ms",
    "frame_end_uptime_ms",
    "feature_compute_end_uptime_ms",
    "log_enqueue_uptime_ms",
    "frame_dt_ms",
    "compute_time_ms",
    "timing_skew_ms",
    "v_rms",
    "voltage",
    "i_rms",
    "current",
    "temp_c",
    "temperature",
    ...computedFeatureOrder,
    "model_pred",
    "label_arc",
    "feat_valid",
    "current_valid",
    "sampling_quality_bad",
    "invalid_loaded_flag",
    "invalid_off_flag",
    "relay_blank_active",
    "turnon_blank_active",
    "transient_blank_active",
    "suspicious_run_len",
    "invalid_loaded_run_len",
    "restrike_count_short",
    "device_family",
    "device_family_code",
    "device_name",
    "trial_number",
    "division_tag",
    "notes",
    "trusted_normal_session",
    "load_type",
    "session_id",
    "context_family_code_runtime",
    "context_family_code_provisional",
    "context_family_confidence",
    "context_family_confidence_provisional",
    "context_acquiring",
    "context_latched",
    "adc_fs_hz",
    "feature_space_version",
  ]);

  const featureMetaByKey = Object.freeze({
    abs_irms_zscore_vs_baseline: { label: "Absolute Z-Deviation", unit: "sigma", decimals: 2 },
    delta_irms_abs: { label: "Abs Delta Irms", unit: "A", decimals: 4 },
    halfcycle_asymmetry: { label: "Half-cycle Asymmetry", unit: "%", decimals: 3 },
    suspicious_run_energy: { label: "Suspicious Run Energy", unit: "", decimals: 3 },
    pulse_count_per_cycle: { label: "Pulse Count / Cycle", unit: "", decimals: 3 },
    zero_dwell_ratio: { label: "Zero Dwell Ratio", unit: "%", decimals: 2 },
    low_current_ratio: { label: "Low-current Ratio", unit: "%", decimals: 2 },
    max_low_current_run_ms: { label: "Max Low-current Run", unit: "ms", decimals: 3 },
    delta_hf_energy: { label: "Abs Delta HF", unit: "dB", decimals: 4 },
    delta_flux: { label: "Abs Delta Flux", unit: "", decimals: 4 },
    midband_residual_ratio: { label: "Midband Residual Ratio", unit: "dB", decimals: 2 },
    zcv: { label: "Zero-cross Variance", unit: "ms", decimals: 3 },
    spectral_flux_midhf: { label: "Spectral Flux (Mid/HF)", unit: "%", decimals: 2 },
    peak_fluct_cv: { label: "Peak Fluctuation CV", unit: "%", decimals: 2 },
    residual_crest_factor: { label: "Residual Crest Factor", unit: "dB", decimals: 2 },
    thd_i: { label: "Current THD", unit: "%", decimals: 2 },
    hf_energy_delta: { label: "HF Energy Delta", unit: "dB", decimals: 2 },
    edge_spike_ratio: { label: "Edge Spike Ratio", unit: "dB", decimals: 2 },
    v_sag_pct: { label: "Voltage Sag", unit: "%", decimals: 3 },
    cycle_nmse: { label: "Cycle NMSE", unit: "%", decimals: 2 },
    i_rms: { label: "Current", unit: "A", decimals: 3 },
    current: { label: "Current", unit: "A", decimals: 3 },
    v_rms: { label: "Voltage", unit: "V", decimals: 1 },
    voltage: { label: "Voltage", unit: "V", decimals: 1 },
    temp_c: { label: "Temperature", unit: "deg C", decimals: 1 },
    temp: { label: "Temperature", unit: "deg C", decimals: 1 },
    label_arc: { label: "Arc Label", unit: "", decimals: 0 },
    model_pred: { label: "Model Prediction", unit: "", decimals: 0 },
    feat_valid: { label: "Feature Valid", unit: "", decimals: 0 },
    current_valid: { label: "Current Valid", unit: "", decimals: 0 },
    fault_state: { label: "Fault State", unit: "", decimals: 0 },
    arc_counter: { label: "Arc Counter", unit: "", decimals: 0 },
    adc_fs_hz: { label: "ADC Rate", unit: "Hz", decimals: 1 },
    fs_err_hz: { label: "ADC Rate Error", unit: "Hz", decimals: 1 },
    frame_start_uptime_ms: { label: "Frame Start", unit: "ms", decimals: 0 },
    frame_end_uptime_ms: { label: "Frame End", unit: "ms", decimals: 0 },
    frame_dt_ms: { label: "Frame Dt", unit: "ms", decimals: 2 },
    compute_time_ms: { label: "Compute Time", unit: "ms", decimals: 2 },
    queue_drop_count: { label: "Queue Drops", unit: "", decimals: 0 },
    sampling_quality_bad: { label: "Sampling Quality Bad", unit: "", decimals: 0 },
    invalid_loaded_flag: { label: "Invalid Loaded", unit: "", decimals: 0 },
    invalid_off_flag: { label: "Invalid Off", unit: "", decimals: 0 },
    relay_blank_active: { label: "Relay Blank", unit: "", decimals: 0 },
    turnon_blank_active: { label: "Turn-on Blank", unit: "", decimals: 0 },
    transient_blank_active: { label: "Transient Blank", unit: "", decimals: 0 },
    suspicious_run_len: { label: "Suspicious Run Len", unit: "", decimals: 0 },
    invalid_loaded_run_len: { label: "Invalid Loaded Run", unit: "", decimals: 0 },
    restrike_count_short: { label: "Restrikes Short", unit: "", decimals: 0 },
    auto_capture: { label: "Auto Capture", unit: "", decimals: 0 },
    device_family_code: { label: "Device Family Code", unit: "", decimals: 0 },
    context_family_code_runtime: { label: "Context Family Runtime", unit: "", decimals: 0 },
    context_family_code_provisional: { label: "Context Family Provisional", unit: "", decimals: 0 },
    context_family_confidence: { label: "Context Confidence", unit: "", decimals: 3 },
    context_family_confidence_provisional: { label: "Provisional Context Confidence", unit: "", decimals: 3 },
    context_acquiring: { label: "Context Acquiring", unit: "", decimals: 0 },
    context_latched: { label: "Context Latched", unit: "", decimals: 0 },
  });

  const aliasMap = Object.freeze({
    i_rms: "i_rms",
    current: "current",
    v_rms: "v_rms",
    voltage: "voltage",
    temp_c: "temp_c",
    temperature: "temp_c",
    model_pred: "model_pred",
    label_arc: "label_arc",
    feat_valid: "feat_valid",
    current_valid: "current_valid",
    session_id: "session_id",
    load_type: "load_type",
    epoch_ms: "epoch_ms",
    uptime_ms: "uptime_ms",
    adc_fs_hz: "adc_fs_hz",
    feature_space_version: "feature_space_version",
    spectral_flux: "spectral_flux_midhf",
    spectral_flux_midhf: "spectral_flux_midhf",
    midhf_flux: "spectral_flux_midhf",
    residual_crest_factor: "residual_crest_factor",
    residual_crest_factor_db: "residual_crest_factor",
    resid_crest_factor: "residual_crest_factor",
    edge_spike_ratio: "edge_spike_ratio",
    edge_spike_ratio_db: "edge_spike_ratio",
    pre_dip_spike_ratio: "edge_spike_ratio",
    midband_residual_ratio: "midband_residual_ratio",
    midband_residual_ratio_db: "midband_residual_ratio",
    cycle_nmse: "cycle_nmse",
    peak_fluct_cv: "peak_fluct_cv",
    thd_i: "thd_i",
    thd_i_db: "thd_i",
    hf_energy_delta: "hf_energy_delta",
    hf_energy_delta_db: "hf_energy_delta",
    zcv: "zcv",
    abs_irms_zscore_vs_baseline: "abs_irms_zscore_vs_baseline",
    delta_irms_abs: "delta_irms_abs",
    halfcycle_asymmetry: "halfcycle_asymmetry",
    suspicious_run_energy: "suspicious_run_energy",
    pulse_count_per_cycle: "pulse_count_per_cycle",
    zero_dwell_ratio: "zero_dwell_ratio",
    low_current_ratio: "low_current_ratio",
    max_low_current_run_ms: "max_low_current_run_ms",
    delta_hf_energy: "delta_hf_energy",
    delta_flux: "delta_flux",
    v_sag_pct: "v_sag_pct",
    context_family_confidence: "context_family_confidence",
    context_family_confidence_provisional: "context_family_confidence_provisional",
    context_family_code_runtime: "context_family_code_runtime",
    context_family_code_provisional: "context_family_code_provisional",
    context_acquiring: "context_acquiring",
    context_latched: "context_latched",
  });

  function normalizeFeatureKey(name) {
    const raw = String(name || "").trim();
    if (!raw) return "";
    const slug = raw.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "");
    return aliasMap[slug] || slug || raw;
  }

  function featureMeta(key) {
    const normalized = normalizeFeatureKey(key);
    return featureMetaByKey[normalized] || null;
  }

  function formatFeatureValue(key, value, fallback) {
    const n = Number(value);
    if (!Number.isFinite(n)) return fallback == null ? "--" : String(fallback);
    const meta = featureMeta(key);
    const decimals = meta && Number.isFinite(meta.decimals) ? meta.decimals : 3;
    return n.toFixed(decimals);
  }

  root.TinyMLFeatureSchema = Object.freeze({
    computedFeatureOrder,
    pwaFeatureOrder,
    csvHeaderOrder,
    featureMetaByKey,
    aliasMap,
    normalizeFeatureKey,
    featureMeta,
    formatFeatureValue,
  });
})(window);
