#pragma once
// Auto-generated by m2cgen from scikit-learn RandomForest
// Generated on: 2026-03-20 00:10:27.941899

#define ARC_THRESHOLD 0.4800

// Input Feature Order:
// [0] cycle_nmse
// [1] zcv
// [2] zc_dwell_ratio
// [3] pulse_count_per_cycle
// [4] peak_fluct_cv
// [5] midband_residual_rms
// [6] hf_band_energy_ratio
// [7] wpe_entropy
// [8] spec_entropy
// [9] thd_i

// output[0] = Probability of Normal
// output[1] = Probability of Arc Fault

#include <string.h>
static inline void add_vectors(double *v1, double *v2, int size, double *result) {
    for(int i = 0; i < size; ++i)
        result[i] = v1[i] + v2[i];
}
static inline void mul_vector_number(double *v1, double num, int size, double *result) {
    for(int i = 0; i < size; ++i)
        result[i] = v1[i] * num;
}
static inline void set_output2(double *dst, double a, double b) {
    dst[0] = a;
    dst[1] = b;
}
static inline void arc_rf_predict(double * input, double * output) {
    double var0[2];
    double var1[2];
    double var2[2];
    double var3[2];
    double var4[2];
    double var5[2];
    double var6[2];
    double var7[2];
    double var8[2];
    double var9[2];
    double var10[2];
    double var11[2];
    double var12[2];
    double var13[2];
    double var14[2];
    double var15[2];
    double var16[2];
    double var17[2];
    double var18[2];
    double var19[2];
    double var20[2];
    double var21[2];
    double var22[2];
    double var23[2];
    double var24[2];
    double var25[2];
    double var26[2];
    double var27[2];
    double var28[2];
    double var29[2];
    double var30[2];
    double var31[2];
    double var32[2];
    double var33[2];
    double var34[2];
    double var35[2];
    double var36[2];
    double var37[2];
    double var38[2];
    double var39[2];
    double var40[2];
    double var41[2];
    double var42[2];
    double var43[2];
    double var44[2];
    double var45[2];
    double var46[2];
    double var47[2];
    double var48[2];
    double var49[2];
    double var50[2];
    double var51[2];
    double var52[2];
    double var53[2];
    double var54[2];
    double var55[2];
    double var56[2];
    double var57[2];
    double var58[2];
    double var59[2];
    double var60[2];
    double var61[2];
    double var62[2];
    double var63[2];
    double var64[2];
    double var65[2];
    double var66[2];
    double var67[2];
    double var68[2];
    double var69[2];
    double var70[2];
    double var71[2];
    double var72[2];
    double var73[2];
    double var74[2];
    double var75[2];
    double var76[2];
    double var77[2];
    double var78[2];
    double var79[2];
    double var80[2];
    if (input[4] <= 0.07953581213951111) {
        set_output2(var80, 1.0, 0.0);
    } else {
        if (input[0] <= 0.9269236028194427) {
            if (input[3] <= 0.5765829384326935) {
                set_output2(var80, 1.0, 0.0);
            } else {
                set_output2(var80, 0.00022836263987212568, 0.9997716373601279);
            }
        } else {
            set_output2(var80, 1.0, 0.0);
        }
    }
    double var81[2];
    if (input[4] <= 0.07905081659555435) {
        set_output2(var81, 1.0, 0.0);
    } else {
        if (input[0] <= 0.9269236028194427) {
            if (input[5] <= 0.019184625707566738) {
                set_output2(var81, 1.0, 0.0);
            } else {
                set_output2(var81, 0.0004514672686230371, 0.999548532731377);
            }
        } else {
            set_output2(var81, 1.0, 0.0);
        }
    }
    add_vectors(var80, var81, 2, var79);
    double var82[2];
    if (input[4] <= 0.07953581213951111) {
        set_output2(var82, 1.0, 0.0);
    } else {
        if (input[1] <= 1.2461987137794495) {
            set_output2(var82, 0.0011373976342129277, 0.9988626023657871);
        } else {
            set_output2(var82, 1.0, 0.0);
        }
    }
    add_vectors(var79, var82, 2, var78);
    double var83[2];
    if (input[4] <= 0.07953581213951111) {
        set_output2(var83, 1.0, 0.0);
    } else {
        if (input[0] <= 0.9267512559890747) {
            set_output2(var83, 0.0018441678192715578, 0.9981558321807285);
        } else {
            set_output2(var83, 1.0, 0.0);
        }
    }
    add_vectors(var78, var83, 2, var77);
    double var84[2];
    if (input[4] <= 0.07953581213951111) {
        set_output2(var84, 1.0, 0.0);
    } else {
        if (input[0] <= 1.0033953189849854) {
            if (input[3] <= 0.5676846504211426) {
                set_output2(var84, 1.0, 0.0);
            } else {
                set_output2(var84, 0.00045248868778280675, 0.9995475113122172);
            }
        } else {
            set_output2(var84, 1.0, 0.0);
        }
    }
    add_vectors(var77, var84, 2, var76);
    double var85[2];
    if (input[5] <= 0.10738740861415863) {
        if (input[4] <= 0.07905081659555435) {
            set_output2(var85, 1.0, 0.0);
        } else {
            if (input[2] <= 0.6999269127845764) {
                if (input[1] <= 1.4063482880592346) {
                    set_output2(var85, 0.0009979478976208309, 0.9990020521023791);
                } else {
                    set_output2(var85, 1.0, 0.0);
                }
            } else {
                set_output2(var85, 1.0, 0.0);
            }
        }
    } else {
        if (input[6] <= 0.07975787669420242) {
            set_output2(var85, 1.0, 0.0);
        } else {
            if (input[3] <= 0.4808056205511093) {
                set_output2(var85, 1.0, 0.0);
            } else {
                set_output2(var85, 0.0, 1.0);
            }
        }
    }
    add_vectors(var76, var85, 2, var75);
    double var86[2];
    if (input[4] <= 0.07905081659555435) {
        set_output2(var86, 1.0, 0.0);
    } else {
        if (input[1] <= 1.2736269235610962) {
            if (input[3] <= 0.5101128667593002) {
                set_output2(var86, 1.0, 0.0);
            } else {
                if (input[0] <= 1.0966343581676483) {
                    set_output2(var86, 0.0, 1.0);
                } else {
                    set_output2(var86, 1.0, 0.0);
                }
            }
        } else {
            set_output2(var86, 1.0, 0.0);
        }
    }
    add_vectors(var75, var86, 2, var74);
    double var87[2];
    if (input[3] <= 0.8029036819934845) {
        set_output2(var87, 1.0, 0.0);
    } else {
        if (input[5] <= 0.019384993240237236) {
            set_output2(var87, 1.0, 0.0);
        } else {
            if (input[6] <= 0.07989658787846565) {
                set_output2(var87, 1.0, 0.0);
            } else {
                if (input[4] <= 0.08037269115447998) {
                    set_output2(var87, 0.769019151412549, 0.23098084858745105);
                } else {
                    set_output2(var87, 0.0006870338401032397, 0.9993129661598967);
                }
            }
        }
    }
    add_vectors(var74, var87, 2, var73);
    double var88[2];
    if (input[0] <= 0.15004785358905792) {
        set_output2(var88, 1.0, 0.0);
    } else {
        if (input[4] <= 0.07811815664172173) {
            set_output2(var88, 1.0, 0.0);
        } else {
            if (input[0] <= 1.0356282889842987) {
                if (input[1] <= 1.2455509901046753) {
                    set_output2(var88, 0.00046232085067035637, 0.9995376791493297);
                } else {
                    set_output2(var88, 1.0, 0.0);
                }
            } else {
                set_output2(var88, 1.0, 0.0);
            }
        }
    }
    add_vectors(var73, var88, 2, var72);
    double var89[2];
    if (input[4] <= 0.07905081659555435) {
        set_output2(var89, 1.0, 0.0);
    } else {
        if (input[1] <= 1.2456412315368652) {
            if (input[4] <= 0.7918736636638641) {
                set_output2(var89, 0.00023153507756424764, 0.9997684649224358);
            } else {
                set_output2(var89, 1.0, 0.0);
            }
        } else {
            set_output2(var89, 1.0, 0.0);
        }
    }
    add_vectors(var72, var89, 2, var71);
    double var90[2];
    if (input[3] <= 0.8029036819934845) {
        set_output2(var90, 0.9997006091263315, 0.0002993908736685542);
    } else {
        if (input[0] <= 0.14526618272066116) {
            set_output2(var90, 1.0, 0.0);
        } else {
            if (input[6] <= 0.0827268660068512) {
                if (input[3] <= 2.807291030883789) {
                    set_output2(var90, 1.0, 0.0);
                } else {
                    set_output2(var90, 0.0, 1.0);
                }
            } else {
                if (input[2] <= 0.7047765254974365) {
                    if (input[1] <= 1.524968147277832) {
                        set_output2(var90, 0.0, 1.0);
                    } else {
                        set_output2(var90, 1.0, 0.0);
                    }
                } else {
                    set_output2(var90, 1.0, 0.0);
                }
            }
        }
    }
    add_vectors(var71, var90, 2, var70);
    double var91[2];
    if (input[4] <= 0.07932865619659424) {
        set_output2(var91, 1.0, 0.0);
    } else {
        if (input[1] <= 1.2461987137794495) {
            if (input[3] <= 0.48797841370105743) {
                set_output2(var91, 1.0, 0.0);
            } else {
                set_output2(var91, 0.0006824385805277696, 0.9993175614194723);
            }
        } else {
            set_output2(var91, 1.0, 0.0);
        }
    }
    add_vectors(var70, var91, 2, var69);
    double var92[2];
    if (input[3] <= 0.822015792131424) {
        set_output2(var92, 0.997939569351555, 0.0020604306484450006);
    } else {
        if (input[4] <= 0.07955105602741241) {
            set_output2(var92, 1.0, 0.0);
        } else {
            if (input[0] <= 1.180185467004776) {
                set_output2(var92, 0.0002324055167653109, 0.9997675944832347);
            } else {
                set_output2(var92, 1.0, 0.0);
            }
        }
    }
    add_vectors(var69, var92, 2, var68);
    double var93[2];
    if (input[4] <= 0.07809646427631378) {
        set_output2(var93, 1.0, 0.0);
    } else {
        if (input[2] <= 0.6998740434646606) {
            if (input[1] <= 1.397711455821991) {
                set_output2(var93, 0.0006933210076265167, 0.9993066789923735);
            } else {
                set_output2(var93, 1.0, 0.0);
            }
        } else {
            set_output2(var93, 1.0, 0.0);
        }
    }
    add_vectors(var68, var93, 2, var67);
    double var94[2];
    if (input[5] <= 0.10885711386799812) {
        if (input[4] <= 0.07905081659555435) {
            set_output2(var94, 1.0, 0.0);
        } else {
            if (input[2] <= 0.6999269127845764) {
                if (input[1] <= 1.3973665237426758) {
                    set_output2(var94, 0.0019244340345575663, 0.9980755659654424);
                } else {
                    set_output2(var94, 1.0, 0.0);
                }
            } else {
                set_output2(var94, 1.0, 0.0);
            }
        }
    } else {
        if (input[3] <= 0.4808056205511093) {
            set_output2(var94, 1.0, 0.0);
        } else {
            set_output2(var94, 0.0, 1.0);
        }
    }
    add_vectors(var67, var94, 2, var66);
    double var95[2];
    if (input[0] <= 0.15004785358905792) {
        set_output2(var95, 1.0, 0.0);
    } else {
        if (input[4] <= 0.07955105602741241) {
            set_output2(var95, 1.0, 0.0);
        } else {
            if (input[0] <= 0.9269236028194427) {
                set_output2(var95, 0.0020325203252032934, 0.9979674796747967);
            } else {
                set_output2(var95, 1.0, 0.0);
            }
        }
    }
    add_vectors(var66, var95, 2, var65);
    double var96[2];
    if (input[4] <= 0.07953581213951111) {
        set_output2(var96, 1.0, 0.0);
    } else {
        if (input[0] <= 0.9269213378429413) {
            if (input[1] <= 1.2461987137794495) {
                set_output2(var96, 0.00022742779167614672, 0.9997725722083238);
            } else {
                set_output2(var96, 1.0, 0.0);
            }
        } else {
            set_output2(var96, 1.0, 0.0);
        }
    }
    add_vectors(var65, var96, 2, var64);
    double var97[2];
    if (input[4] <= 0.07953581213951111) {
        set_output2(var97, 1.0, 0.0);
    } else {
        if (input[0] <= 0.9269236028194427) {
            if (input[1] <= 1.2461987137794495) {
                set_output2(var97, 0.0, 1.0);
            } else {
                set_output2(var97, 1.0, 0.0);
            }
        } else {
            set_output2(var97, 1.0, 0.0);
        }
    }
    add_vectors(var64, var97, 2, var63);
    double var98[2];
    if (input[4] <= 0.079813651740551) {
        set_output2(var98, 1.0, 0.0);
    } else {
        if (input[0] <= 1.003565400838852) {
            if (input[1] <= 1.397446632385254) {
                set_output2(var98, 0.0009252833680314363, 0.9990747166319686);
            } else {
                set_output2(var98, 1.0, 0.0);
            }
        } else {
            set_output2(var98, 1.0, 0.0);
        }
    }
    add_vectors(var63, var98, 2, var62);
    double var99[2];
    if (input[4] <= 0.07906606048345566) {
        set_output2(var99, 1.0, 0.0);
    } else {
        if (input[2] <= 0.6999712586402893) {
            if (input[1] <= 1.397711455821991) {
                set_output2(var99, 0.0009155413138018042, 0.9990844586861982);
            } else {
                set_output2(var99, 1.0, 0.0);
            }
        } else {
            set_output2(var99, 1.0, 0.0);
        }
    }
    add_vectors(var62, var99, 2, var61);
    double var100[2];
    if (input[5] <= 0.1088753342628479) {
        if (input[4] <= 0.07953581213951111) {
            set_output2(var100, 1.0, 0.0);
        } else {
            if (input[1] <= 1.2461987137794495) {
                if (input[3] <= 0.511388473212719) {
                    set_output2(var100, 1.0, 0.0);
                } else {
                    set_output2(var100, 0.003800094558549701, 0.9961999054414502);
                }
            } else {
                set_output2(var100, 1.0, 0.0);
            }
        }
    } else {
        if (input[4] <= 0.06203093379735947) {
            set_output2(var100, 1.0, 0.0);
        } else {
            set_output2(var100, 0.0, 1.0);
        }
    }
    add_vectors(var61, var100, 2, var60);
    double var101[2];
    if (input[4] <= 0.079813651740551) {
        set_output2(var101, 1.0, 0.0);
    } else {
        if (input[0] <= 0.9269213378429413) {
            if (input[3] <= 0.5676846504211426) {
                set_output2(var101, 1.0, 0.0);
            } else {
                set_output2(var101, 0.00022701475595914518, 0.9997729852440409);
            }
        } else {
            set_output2(var101, 1.0, 0.0);
        }
    }
    add_vectors(var60, var101, 2, var59);
    double var102[2];
    if (input[4] <= 0.07955105602741241) {
        set_output2(var102, 1.0, 0.0);
    } else {
        if (input[1] <= 1.268185794353485) {
            if (input[0] <= 1.0346777737140656) {
                set_output2(var102, 0.0, 1.0);
            } else {
                set_output2(var102, 1.0, 0.0);
            }
        } else {
            set_output2(var102, 1.0, 0.0);
        }
    }
    add_vectors(var59, var102, 2, var58);
    double var103[2];
    if (input[3] <= 0.8029036819934845) {
        set_output2(var103, 0.9993922114966327, 0.0006077885033673007);
    } else {
        if (input[0] <= 0.14062601327896118) {
            set_output2(var103, 1.0, 0.0);
        } else {
            if (input[4] <= 0.07953581213951111) {
                set_output2(var103, 1.0, 0.0);
            } else {
                if (input[2] <= 0.7765327990055084) {
                    set_output2(var103, 0.0011318524430648008, 0.9988681475569352);
                } else {
                    set_output2(var103, 1.0, 0.0);
                }
            }
        }
    }
    add_vectors(var58, var103, 2, var57);
    double var104[2];
    if (input[4] <= 0.07905081659555435) {
        set_output2(var104, 1.0, 0.0);
    } else {
        if (input[1] <= 1.2458537817001343) {
            if (input[2] <= 0.7263642251491547) {
                set_output2(var104, 0.00045620437956204546, 0.9995437956204379);
            } else {
                set_output2(var104, 1.0, 0.0);
            }
        } else {
            set_output2(var104, 1.0, 0.0);
        }
    }
    add_vectors(var57, var104, 2, var56);
    double var105[2];
    if (input[4] <= 0.07905081659555435) {
        set_output2(var105, 1.0, 0.0);
    } else {
        if (input[0] <= 1.0035676658153534) {
            if (input[3] <= 0.5674223899841309) {
                set_output2(var105, 1.0, 0.0);
            } else {
                set_output2(var105, 0.0006904487917146191, 0.9993095512082854);
            }
        } else {
            set_output2(var105, 1.0, 0.0);
        }
    }
    add_vectors(var56, var105, 2, var55);
    double var106[2];
    if (input[3] <= 0.8025951087474823) {
        set_output2(var106, 0.9997008406072629, 0.00029915939273705155);
    } else {
        if (input[4] <= 0.07810291275382042) {
            set_output2(var106, 1.0, 0.0);
        } else {
            if (input[1] <= 1.2461987137794495) {
                set_output2(var106, 0.0006823173807340467, 0.999317682619266);
            } else {
                set_output2(var106, 1.0, 0.0);
            }
        }
    }
    add_vectors(var55, var106, 2, var54);
    double var107[2];
    if (input[5] <= 0.10310163348913193) {
        if (input[4] <= 0.07905081659555435) {
            set_output2(var107, 1.0, 0.0);
        } else {
            if (input[0] <= 0.9269213378429413) {
                if (input[3] <= 0.5674223899841309) {
                    set_output2(var107, 1.0, 0.0);
                } else {
                    set_output2(var107, 0.0010628563874015818, 0.9989371436125984);
                }
            } else {
                set_output2(var107, 1.0, 0.0);
            }
        }
    } else {
        if (input[4] <= 0.060634005814790726) {
            set_output2(var107, 1.0, 0.0);
        } else {
            set_output2(var107, 0.0, 1.0);
        }
    }
    add_vectors(var54, var107, 2, var53);
    double var108[2];
    if (input[3] <= 0.822015792131424) {
        if (input[8] <= 0.7975841164588928) {
            set_output2(var108, 0.9990719748433413, 0.0009280251566587142);
        } else {
            set_output2(var108, 0.23968458976276258, 0.7603154102372374);
        }
    } else {
        if (input[4] <= 0.07810291275382042) {
            set_output2(var108, 1.0, 0.0);
        } else {
            if (input[0] <= 1.1801877319812775) {
                set_output2(var108, 0.0011188563016614592, 0.9988811436983386);
            } else {
                set_output2(var108, 1.0, 0.0);
            }
        }
    }
    add_vectors(var53, var108, 2, var52);
    double var109[2];
    if (input[4] <= 0.07810291275382042) {
        set_output2(var109, 1.0, 0.0);
    } else {
        if (input[2] <= 0.6999269127845764) {
            if (input[1] <= 1.4063482880592346) {
                if (input[3] <= 0.4251395668834448) {
                    set_output2(var109, 1.0, 0.0);
                } else {
                    set_output2(var109, 0.0, 1.0);
                }
            } else {
                set_output2(var109, 1.0, 0.0);
            }
        } else {
            set_output2(var109, 1.0, 0.0);
        }
    }
    add_vectors(var52, var109, 2, var51);
    double var110[2];
    if (input[4] <= 0.079813651740551) {
        set_output2(var110, 1.0, 0.0);
    } else {
        if (input[1] <= 1.2709996700286865) {
            if (input[3] <= 0.5111879855394363) {
                set_output2(var110, 1.0, 0.0);
            } else {
                set_output2(var110, 0.000676742612226489, 0.9993232573877735);
            }
        } else {
            set_output2(var110, 1.0, 0.0);
        }
    }
    add_vectors(var51, var110, 2, var50);
    double var111[2];
    if (input[4] <= 0.07955105602741241) {
        set_output2(var111, 1.0, 0.0);
    } else {
        if (input[2] <= 0.7064260542392731) {
            if (input[1] <= 1.612504243850708) {
                set_output2(var111, 0.0006735518634934863, 0.9993264481365065);
            } else {
                set_output2(var111, 1.0, 0.0);
            }
        } else {
            set_output2(var111, 1.0, 0.0);
        }
    }
    add_vectors(var50, var111, 2, var49);
    double var112[2];
    if (input[3] <= 0.8025951087474823) {
        set_output2(var112, 0.999696577186684, 0.0003034228133159338);
    } else {
        if (input[5] <= 0.02103789895772934) {
            set_output2(var112, 0.9958954500369157, 0.004104549963084211);
        } else {
            if (input[6] <= 0.07989658787846565) {
                set_output2(var112, 1.0, 0.0);
            } else {
                set_output2(var112, 0.0011349315980480367, 0.9988650684019519);
            }
        }
    }
    add_vectors(var49, var112, 2, var48);
    double var113[2];
    if (input[3] <= 0.8025951087474823) {
        set_output2(var113, 1.0, 0.0);
    } else {
        if (input[4] <= 0.07953581213951111) {
            set_output2(var113, 1.0, 0.0);
        } else {
            if (input[5] <= 0.018722696229815483) {
                set_output2(var113, 1.0, 0.0);
            } else {
                set_output2(var113, 0.0006898137502873929, 0.9993101862497127);
            }
        }
    }
    add_vectors(var48, var113, 2, var47);
    double var114[2];
    if (input[4] <= 0.07905081659555435) {
        set_output2(var114, 1.0, 0.0);
    } else {
        if (input[0] <= 0.9269236028194427) {
            if (input[1] <= 1.6125843524932861) {
                set_output2(var114, 0.0004527960153950558, 0.999547203984605);
            } else {
                set_output2(var114, 1.0, 0.0);
            }
        } else {
            set_output2(var114, 1.0, 0.0);
        }
    }
    add_vectors(var47, var114, 2, var46);
    double var115[2];
    if (input[4] <= 0.079813651740551) {
        set_output2(var115, 1.0, 0.0);
    } else {
        if (input[1] <= 1.2458537817001343) {
            if (input[3] <= 0.48797841370105743) {
                set_output2(var115, 1.0, 0.0);
            } else {
                set_output2(var115, 0.00045766590389016086, 0.9995423340961099);
            }
        } else {
            set_output2(var115, 1.0, 0.0);
        }
    }
    add_vectors(var46, var115, 2, var45);
    double var116[2];
    if (input[5] <= 0.10356488451361656) {
        if (input[4] <= 0.08990694209933281) {
            set_output2(var116, 0.9985539528687015, 0.0014460471312985413);
        } else {
            if (input[2] <= 0.6995376944541931) {
                if (input[1] <= 1.612127423286438) {
                    set_output2(var116, 0.0010756306379235774, 0.9989243693620764);
                } else {
                    set_output2(var116, 1.0, 0.0);
                }
            } else {
                set_output2(var116, 1.0, 0.0);
            }
        }
    } else {
        if (input[3] <= 0.4808056205511093) {
            set_output2(var116, 1.0, 0.0);
        } else {
            set_output2(var116, 0.0, 1.0);
        }
    }
    add_vectors(var45, var116, 2, var44);
    double var117[2];
    if (input[5] <= 0.1088753342628479) {
        if (input[3] <= 0.8357453346252441) {
            set_output2(var117, 0.9990855983940626, 0.0009144016059374211);
        } else {
            if (input[4] <= 0.07953581213951111) {
                set_output2(var117, 1.0, 0.0);
            } else {
                if (input[2] <= 0.7873090505599976) {
                    set_output2(var117, 0.0019146027965461182, 0.9980853972034539);
                } else {
                    set_output2(var117, 1.0, 0.0);
                }
            }
        }
    } else {
        if (input[6] <= 0.07975787669420242) {
            set_output2(var117, 1.0, 0.0);
        } else {
            if (input[3] <= 0.4808056205511093) {
                set_output2(var117, 1.0, 0.0);
            } else {
                set_output2(var117, 0.0, 1.0);
            }
        }
    }
    add_vectors(var44, var117, 2, var43);
    double var118[2];
    if (input[4] <= 0.07906606048345566) {
        set_output2(var118, 1.0, 0.0);
    } else {
        if (input[3] <= 0.7910895943641663) {
            set_output2(var118, 1.0, 0.0);
        } else {
            if (input[5] <= 0.01834828406572342) {
                set_output2(var118, 1.0, 0.0);
            } else {
                set_output2(var118, 0.00022629554197782395, 0.9997737044580222);
            }
        }
    }
    add_vectors(var43, var118, 2, var42);
    double var119[2];
    if (input[4] <= 0.07953581213951111) {
        set_output2(var119, 1.0, 0.0);
    } else {
        if (input[1] <= 1.2709996700286865) {
            if (input[2] <= 0.7995963990688324) {
                set_output2(var119, 0.0006960556844547671, 0.9993039443155453);
            } else {
                set_output2(var119, 1.0, 0.0);
            }
        } else {
            set_output2(var119, 1.0, 0.0);
        }
    }
    add_vectors(var42, var119, 2, var41);
    double var120[2];
    if (input[3] <= 0.7939420342445374) {
        set_output2(var120, 1.0, 0.0);
    } else {
        if (input[4] <= 0.07810291275382042) {
            set_output2(var120, 1.0, 0.0);
        } else {
            if (input[0] <= 1.096838265657425) {
                set_output2(var120, 0.0006782726656115925, 0.9993217273343885);
            } else {
                set_output2(var120, 1.0, 0.0);
            }
        }
    }
    add_vectors(var41, var120, 2, var40);
    double var121[2];
    if (input[3] <= 0.7979046404361725) {
        set_output2(var121, 1.0, 0.0);
    } else {
        if (input[4] <= 0.07955105602741241) {
            set_output2(var121, 1.0, 0.0);
        } else {
            if (input[0] <= 1.0035676658153534) {
                set_output2(var121, 0.0009189065012634939, 0.9990810934987365);
            } else {
                set_output2(var121, 1.0, 0.0);
            }
        }
    }
    add_vectors(var40, var121, 2, var39);
    double var122[2];
    if (input[4] <= 0.07953581213951111) {
        set_output2(var122, 1.0, 0.0);
    } else {
        if (input[2] <= 0.7002420723438263) {
            if (input[1] <= 1.397711455821991) {
                set_output2(var122, 0.0009090909090909243, 0.999090909090909);
            } else {
                set_output2(var122, 1.0, 0.0);
            }
        } else {
            set_output2(var122, 1.0, 0.0);
        }
    }
    add_vectors(var39, var122, 2, var38);
    double var123[2];
    if (input[4] <= 0.07953581213951111) {
        set_output2(var123, 1.0, 0.0);
    } else {
        if (input[1] <= 1.2459338903427124) {
            if (input[0] <= 1.034495323896408) {
                set_output2(var123, 0.00046425255338903963, 0.999535747446611);
            } else {
                set_output2(var123, 1.0, 0.0);
            }
        } else {
            set_output2(var123, 1.0, 0.0);
        }
    }
    add_vectors(var38, var123, 2, var37);
    double var124[2];
    if (input[4] <= 0.07953581213951111) {
        set_output2(var124, 1.0, 0.0);
    } else {
        if (input[2] <= 0.6998740434646606) {
            if (input[3] <= 0.5286388546228409) {
                set_output2(var124, 1.0, 0.0);
            } else {
                set_output2(var124, 0.0009126169290440147, 0.999087383070956);
            }
        } else {
            set_output2(var124, 1.0, 0.0);
        }
    }
    add_vectors(var37, var124, 2, var36);
    double var125[2];
    if (input[4] <= 0.07953581213951111) {
        set_output2(var125, 1.0, 0.0);
    } else {
        if (input[1] <= 1.268185794353485) {
            set_output2(var125, 0.001832340815391695, 0.9981676591846084);
        } else {
            set_output2(var125, 1.0, 0.0);
        }
    }
    add_vectors(var36, var125, 2, var35);
    double var126[2];
    if (input[4] <= 0.07953581213951111) {
        set_output2(var126, 1.0, 0.0);
    } else {
        if (input[0] <= 0.9269236028194427) {
            if (input[3] <= 0.576996773481369) {
                set_output2(var126, 1.0, 0.0);
            } else {
                if (input[5] <= 0.020835748873651028) {
                    set_output2(var126, 0.8527512444504238, 0.14724875554957623);
                } else {
                    set_output2(var126, 0.0, 1.0);
                }
            }
        } else {
            set_output2(var126, 1.0, 0.0);
        }
    }
    add_vectors(var35, var126, 2, var34);
    double var127[2];
    if (input[4] <= 0.07953581213951111) {
        set_output2(var127, 1.0, 0.0);
    } else {
        if (input[0] <= 1.0035676658153534) {
            if (input[3] <= 0.5765829384326935) {
                set_output2(var127, 1.0, 0.0);
            } else {
                set_output2(var127, 0.0009174311926605383, 0.9990825688073395);
            }
        } else {
            set_output2(var127, 1.0, 0.0);
        }
    }
    add_vectors(var34, var127, 2, var33);
    double var128[2];
    if (input[3] <= 0.8369672894477844) {
        if (input[5] <= 0.14751402288675308) {
            set_output2(var128, 0.999089396752971, 0.0009106032470290146);
        } else {
            set_output2(var128, 0.21233527246824174, 0.7876647275317583);
        }
    } else {
        if (input[5] <= 0.019207855686545372) {
            set_output2(var128, 1.0, 0.0);
        } else {
            if (input[4] <= 0.07475796341896057) {
                set_output2(var128, 1.0, 0.0);
            } else {
                if (input[0] <= 1.0968405306339264) {
                    set_output2(var128, 0.0, 1.0);
                } else {
                    set_output2(var128, 1.0, 0.0);
                }
            }
        }
    }
    add_vectors(var33, var128, 2, var32);
    double var129[2];
    if (input[4] <= 0.07953581213951111) {
        set_output2(var129, 1.0, 0.0);
    } else {
        if (input[1] <= 1.2459338903427124) {
            if (input[0] <= 1.0356282889842987) {
                set_output2(var129, 0.0006898137502873938, 0.9993101862497126);
            } else {
                set_output2(var129, 1.0, 0.0);
            }
        } else {
            set_output2(var129, 1.0, 0.0);
        }
    }
    add_vectors(var32, var129, 2, var31);
    double var130[2];
    if (input[5] <= 0.10087666288018227) {
        if (input[8] <= 0.6341888010501862) {
            if (input[4] <= 0.10689615085721016) {
                if (input[3] <= 2.8970917463302612) {
                    set_output2(var130, 1.0, 0.0);
                } else {
                    set_output2(var130, 0.0, 1.0);
                }
            } else {
                if (input[3] <= 0.9744134545326233) {
                    set_output2(var130, 1.0, 0.0);
                } else {
                    set_output2(var130, 0.003696811185997386, 0.9963031888140026);
                }
            }
        } else {
            if (input[5] <= 0.019286664202809334) {
                set_output2(var130, 1.0, 0.0);
            } else {
                if (input[4] <= 0.07623115181922913) {
                    set_output2(var130, 1.0, 0.0);
                } else {
                    set_output2(var130, 0.0, 1.0);
                }
            }
        }
    } else {
        if (input[3] <= 0.45497072860598564) {
            set_output2(var130, 1.0, 0.0);
        } else {
            set_output2(var130, 0.0, 1.0);
        }
    }
    add_vectors(var31, var130, 2, var30);
    double var131[2];
    if (input[5] <= 0.1088753342628479) {
        if (input[0] <= 0.15112484991550446) {
            set_output2(var131, 1.0, 0.0);
        } else {
            if (input[6] <= 0.14430081844329834) {
                if (input[2] <= 0.5315946042537689) {
                    if (input[4] <= 0.058499832171946764) {
                        set_output2(var131, 1.0, 0.0);
                    } else {
                        set_output2(var131, 0.0, 1.0);
                    }
                } else {
                    if (input[3] <= 3.921802282333374) {
                        if (input[8] <= 0.6776309311389923) {
                            set_output2(var131, 0.9956298199869817, 0.004370180013018339);
                        } else {
                            set_output2(var131, 0.25043849090346326, 0.7495615090965367);
                        }
                    } else {
                        set_output2(var131, 0.0, 1.0);
                    }
                }
            } else {
                if (input[5] <= 0.014901888091117144) {
                    set_output2(var131, 1.0, 0.0);
                } else {
                    if (input[4] <= 0.07177181914448738) {
                        set_output2(var131, 1.0, 0.0);
                    } else {
                        set_output2(var131, 0.0, 1.0);
                    }
                }
            }
        }
    } else {
        if (input[4] <= 0.05730892904102802) {
            set_output2(var131, 1.0, 0.0);
        } else {
            set_output2(var131, 0.0, 1.0);
        }
    }
    add_vectors(var30, var131, 2, var29);
    double var132[2];
    if (input[4] <= 0.07955105602741241) {
        set_output2(var132, 1.0, 0.0);
    } else {
        if (input[0] <= 1.0035676658153534) {
            if (input[3] <= 0.5680984854698181) {
                set_output2(var132, 1.0, 0.0);
            } else {
                set_output2(var132, 0.0002289901534234028, 0.9997710098465766);
            }
        } else {
            set_output2(var132, 1.0, 0.0);
        }
    }
    add_vectors(var29, var132, 2, var28);
    double var133[2];
    if (input[3] <= 0.8220329582691193) {
        set_output2(var133, 0.998536158524601, 0.0014638414753990875);
    } else {
        if (input[4] <= 0.07810291275382042) {
            set_output2(var133, 1.0, 0.0);
        } else {
            if (input[1] <= 1.2736269235610962) {
                set_output2(var133, 0.0004672639832770891, 0.9995327360167229);
            } else {
                set_output2(var133, 1.0, 0.0);
            }
        }
    }
    add_vectors(var28, var133, 2, var27);
    double var134[2];
    if (input[4] <= 0.07808122038841248) {
        set_output2(var134, 1.0, 0.0);
    } else {
        if (input[1] <= 1.2461987137794495) {
            if (input[0] <= 1.0346777737140656) {
                set_output2(var134, 0.0006816632583503852, 0.9993183367416497);
            } else {
                set_output2(var134, 1.0, 0.0);
            }
        } else {
            set_output2(var134, 1.0, 0.0);
        }
    }
    add_vectors(var27, var134, 2, var26);
    double var135[2];
    if (input[4] <= 0.07953581213951111) {
        set_output2(var135, 1.0, 0.0);
    } else {
        if (input[0] <= 0.9269236028194427) {
            if (input[3] <= 0.5687597692012787) {
                set_output2(var135, 1.0, 0.0);
            } else {
                if (input[5] <= 0.015780042856931686) {
                    set_output2(var135, 1.0, 0.0);
                } else {
                    set_output2(var135, 0.0, 1.0);
                }
            }
        } else {
            set_output2(var135, 1.0, 0.0);
        }
    }
    add_vectors(var26, var135, 2, var25);
    double var136[2];
    if (input[3] <= 0.7979046404361725) {
        set_output2(var136, 1.0, 0.0);
    } else {
        if (input[4] <= 0.07953581213951111) {
            set_output2(var136, 1.0, 0.0);
        } else {
            if (input[5] <= 0.018225657753646374) {
                set_output2(var136, 1.0, 0.0);
            } else {
                set_output2(var136, 0.0011431184270690776, 0.998856881572931);
            }
        }
    }
    add_vectors(var25, var136, 2, var24);
    double var137[2];
    if (input[3] <= 0.7939420342445374) {
        set_output2(var137, 1.0, 0.0);
    } else {
        if (input[5] <= 0.021220472641289234) {
            set_output2(var137, 0.9792098282572076, 0.020790171742792452);
        } else {
            if (input[1] <= 1.2137935757637024) {
                if (input[6] <= 0.07194136455655098) {
                    set_output2(var137, 1.0, 0.0);
                } else {
                    set_output2(var137, 0.0006989416520490306, 0.9993010583479509);
                }
            } else {
                set_output2(var137, 1.0, 0.0);
            }
        }
    }
    add_vectors(var24, var137, 2, var23);
    double var138[2];
    if (input[4] <= 0.07953581213951111) {
        set_output2(var138, 1.0, 0.0);
    } else {
        if (input[3] <= 0.7910895943641663) {
            set_output2(var138, 1.0, 0.0);
        } else {
            if (input[0] <= 1.0035676658153534) {
                set_output2(var138, 0.0009130335539831287, 0.9990869664460168);
            } else {
                set_output2(var138, 1.0, 0.0);
            }
        }
    }
    add_vectors(var23, var138, 2, var22);
    double var139[2];
    if (input[4] <= 0.07906606048345566) {
        set_output2(var139, 1.0, 0.0);
    } else {
        if (input[2] <= 0.7001797258853912) {
            if (input[3] <= 0.5518315583467484) {
                set_output2(var139, 1.0, 0.0);
            } else {
                set_output2(var139, 0.0006790402897238437, 0.9993209597102762);
            }
        } else {
            set_output2(var139, 1.0, 0.0);
        }
    }
    add_vectors(var22, var139, 2, var21);
    double var140[2];
    if (input[4] <= 0.079813651740551) {
        set_output2(var140, 1.0, 0.0);
    } else {
        if (input[1] <= 1.2719085216522217) {
            if (input[0] <= 1.034675508737564) {
                set_output2(var140, 0.0009291521486643666, 0.9990708478513357);
            } else {
                set_output2(var140, 1.0, 0.0);
            }
        } else {
            set_output2(var140, 1.0, 0.0);
        }
    }
    add_vectors(var21, var140, 2, var20);
    double var141[2];
    if (input[4] <= 0.07905081659555435) {
        set_output2(var141, 1.0, 0.0);
    } else {
        if (input[3] <= 0.7845554351806641) {
            set_output2(var141, 1.0, 0.0);
        } else {
            if (input[1] <= 1.2455509901046753) {
                set_output2(var141, 0.0009193288899103998, 0.9990806711100896);
            } else {
                set_output2(var141, 1.0, 0.0);
            }
        }
    }
    add_vectors(var20, var141, 2, var19);
    double var142[2];
    if (input[4] <= 0.07953581213951111) {
        set_output2(var142, 1.0, 0.0);
    } else {
        if (input[1] <= 1.267920970916748) {
            if (input[3] <= 0.511388473212719) {
                set_output2(var142, 1.0, 0.0);
            } else {
                set_output2(var142, 0.0006944444444444618, 0.9993055555555554);
            }
        } else {
            set_output2(var142, 1.0, 0.0);
        }
    }
    add_vectors(var19, var142, 2, var18);
    double var143[2];
    if (input[4] <= 0.07906606048345566) {
        set_output2(var143, 1.0, 0.0);
    } else {
        if (input[1] <= 1.2459338903427124) {
            set_output2(var143, 0.0016117890858853188, 0.9983882109141147);
        } else {
            set_output2(var143, 1.0, 0.0);
        }
    }
    add_vectors(var18, var143, 2, var17);
    double var144[2];
    if (input[4] <= 0.07953581213951111) {
        set_output2(var144, 1.0, 0.0);
    } else {
        if (input[3] <= 0.7939943969249725) {
            set_output2(var144, 1.0, 0.0);
        } else {
            if (input[0] <= 1.0035676658153534) {
                set_output2(var144, 0.0006936416184971051, 0.999306358381503);
            } else {
                set_output2(var144, 1.0, 0.0);
            }
        }
    }
    add_vectors(var17, var144, 2, var16);
    double var145[2];
    if (input[4] <= 0.07953581213951111) {
        set_output2(var145, 1.0, 0.0);
    } else {
        if (input[0] <= 0.9269236028194427) {
            if (input[3] <= 0.576996773481369) {
                set_output2(var145, 1.0, 0.0);
            } else {
                set_output2(var145, 0.00114311842706908, 0.998856881572931);
            }
        } else {
            set_output2(var145, 1.0, 0.0);
        }
    }
    add_vectors(var16, var145, 2, var15);
    double var146[2];
    if (input[4] <= 0.07932865619659424) {
        set_output2(var146, 1.0, 0.0);
    } else {
        if (input[2] <= 0.6999269127845764) {
            if (input[3] <= 0.5687597692012787) {
                set_output2(var146, 1.0, 0.0);
            } else {
                set_output2(var146, 0.0009078529278256714, 0.9990921470721743);
            }
        } else {
            set_output2(var146, 1.0, 0.0);
        }
    }
    add_vectors(var15, var146, 2, var14);
    double var147[2];
    if (input[4] <= 0.07986529171466827) {
        set_output2(var147, 1.0, 0.0);
    } else {
        if (input[2] <= 0.706363707780838) {
            if (input[1] <= 1.6125843524932861) {
                set_output2(var147, 0.00045599635202917536, 0.9995440036479708);
            } else {
                set_output2(var147, 1.0, 0.0);
            }
        } else {
            set_output2(var147, 1.0, 0.0);
        }
    }
    add_vectors(var14, var147, 2, var13);
    double var148[2];
    if (input[3] <= 0.7979046404361725) {
        set_output2(var148, 1.0, 0.0);
    } else {
        if (input[5] <= 0.01916403789073229) {
            set_output2(var148, 1.0, 0.0);
        } else {
            if (input[6] <= 0.0799555853009224) {
                set_output2(var148, 1.0, 0.0);
            } else {
                if (input[0] <= 1.0281347334384918) {
                    set_output2(var148, 0.0, 1.0);
                } else {
                    set_output2(var148, 1.0, 0.0);
                }
            }
        }
    }
    add_vectors(var13, var148, 2, var12);
    double var149[2];
    if (input[5] <= 0.10087666288018227) {
        if (input[4] <= 0.08995156735181808) {
            set_output2(var149, 0.9994190011872585, 0.0005809988127415402);
        } else {
            if (input[1] <= 1.268185794353485) {
                set_output2(var149, 0.004350274805305758, 0.9956497251946942);
            } else {
                set_output2(var149, 1.0, 0.0);
            }
        }
    } else {
        if (input[4] <= 0.06296445056796074) {
            set_output2(var149, 1.0, 0.0);
        } else {
            set_output2(var149, 0.0, 1.0);
        }
    }
    add_vectors(var12, var149, 2, var11);
    double var150[2];
    if (input[3] <= 0.8012422621250153) {
        set_output2(var150, 1.0, 0.0);
    } else {
        if (input[4] <= 0.07477320730686188) {
            set_output2(var150, 1.0, 0.0);
        } else {
            if (input[5] <= 0.016158430371433496) {
                set_output2(var150, 1.0, 0.0);
            } else {
                if (input[4] <= 0.7386963367462158) {
                    set_output2(var150, 0.0, 1.0);
                } else {
                    set_output2(var150, 1.0, 0.0);
                }
            }
        }
    }
    add_vectors(var11, var150, 2, var10);
    double var151[2];
    if (input[4] <= 0.07906606048345566) {
        set_output2(var151, 1.0, 0.0);
    } else {
        if (input[2] <= 0.6999269127845764) {
            set_output2(var151, 0.0015938069216757565, 0.9984061930783242);
        } else {
            set_output2(var151, 1.0, 0.0);
        }
    }
    add_vectors(var10, var151, 2, var9);
    double var152[2];
    if (input[4] <= 0.07808122038841248) {
        set_output2(var152, 1.0, 0.0);
    } else {
        if (input[3] <= 0.6935315430164337) {
            set_output2(var152, 1.0, 0.0);
        } else {
            if (input[5] <= 0.018225657753646374) {
                set_output2(var152, 1.0, 0.0);
            } else {
                if (input[2] <= 0.7765327990055084) {
                    set_output2(var152, 0.00023518344308560087, 0.9997648165569144);
                } else {
                    set_output2(var152, 1.0, 0.0);
                }
            }
        }
    }
    add_vectors(var9, var152, 2, var8);
    double var153[2];
    if (input[4] <= 0.07953581213951111) {
        set_output2(var153, 1.0, 0.0);
    } else {
        if (input[2] <= 0.6999269127845764) {
            if (input[1] <= 1.4057908058166504) {
                set_output2(var153, 0.0004531037607612251, 0.9995468962392389);
            } else {
                set_output2(var153, 1.0, 0.0);
            }
        } else {
            set_output2(var153, 1.0, 0.0);
        }
    }
    add_vectors(var8, var153, 2, var7);
    double var154[2];
    if (input[4] <= 0.07906606048345566) {
        set_output2(var154, 1.0, 0.0);
    } else {
        if (input[3] <= 0.7910895943641663) {
            set_output2(var154, 1.0, 0.0);
        } else {
            if (input[5] <= 0.018722696229815483) {
                set_output2(var154, 1.0, 0.0);
            } else {
                set_output2(var154, 0.0004553734061930682, 0.9995446265938069);
            }
        }
    }
    add_vectors(var7, var154, 2, var6);
    double var155[2];
    if (input[4] <= 0.07905081659555435) {
        set_output2(var155, 1.0, 0.0);
    } else {
        if (input[0] <= 0.9267512559890747) {
            if (input[9] <= 15.183160305023193) {
                set_output2(var155, 1.0, 0.0);
            } else {
                set_output2(var155, 0.0018285714285714853, 0.9981714285714286);
            }
        } else {
            set_output2(var155, 1.0, 0.0);
        }
    }
    add_vectors(var6, var155, 2, var5);
    double var156[2];
    if (input[4] <= 0.07953581213951111) {
        set_output2(var156, 1.0, 0.0);
    } else {
        if (input[1] <= 1.2461987137794495) {
            if (input[4] <= 0.7918736636638641) {
                set_output2(var156, 0.0013574660633484052, 0.9986425339366516);
            } else {
                set_output2(var156, 1.0, 0.0);
            }
        } else {
            set_output2(var156, 1.0, 0.0);
        }
    }
    add_vectors(var5, var156, 2, var4);
    double var157[2];
    if (input[5] <= 0.10388287156820297) {
        if (input[0] <= 0.15458323061466217) {
            set_output2(var157, 0.9992277759878866, 0.0007722240121134284);
        } else {
            if (input[3] <= 1.0364072918891907) {
                if (input[2] <= 0.5100589841604233) {
                    if (input[4] <= 0.07816053181886673) {
                        set_output2(var157, 1.0, 0.0);
                    } else {
                        set_output2(var157, 0.04774418448749748, 0.9522558155125026);
                    }
                } else {
                    set_output2(var157, 0.99753276904017, 0.002467230959830105);
                }
            } else {
                if (input[4] <= 0.07419385015964508) {
                    set_output2(var157, 1.0, 0.0);
                } else {
                    if (input[5] <= 0.018722696229815483) {
                        set_output2(var157, 1.0, 0.0);
                    } else {
                        set_output2(var157, 0.003960498448915997, 0.9960395015510839);
                    }
                }
            }
        }
    } else {
        if (input[4] <= 0.060354193672537804) {
            set_output2(var157, 1.0, 0.0);
        } else {
            set_output2(var157, 0.0, 1.0);
        }
    }
    add_vectors(var4, var157, 2, var3);
    double var158[2];
    if (input[4] <= 0.07808122038841248) {
        set_output2(var158, 1.0, 0.0);
    } else {
        if (input[0] <= 0.9269236028194427) {
            if (input[3] <= 0.576996773481369) {
                set_output2(var158, 1.0, 0.0);
            } else {
                set_output2(var158, 0.001135589370883504, 0.9988644106291165);
            }
        } else {
            set_output2(var158, 1.0, 0.0);
        }
    }
    add_vectors(var3, var158, 2, var2);
    double var159[2];
    if (input[4] <= 0.07810291275382042) {
        set_output2(var159, 1.0, 0.0);
    } else {
        if (input[1] <= 1.268185794353485) {
            if (input[0] <= 1.0354582071304321) {
                set_output2(var159, 0.0006729475100942324, 0.9993270524899058);
            } else {
                set_output2(var159, 1.0, 0.0);
            }
        } else {
            set_output2(var159, 1.0, 0.0);
        }
    }
    add_vectors(var2, var159, 2, var1);
    mul_vector_number(var1, 0.0125, 2, var0);
    memcpy(output, var0, 2 * sizeof(double));
}

