#pragma once
// Auto-generated by m2cgen from scikit-learn RandomForest
// Generated on: 2026-03-30 21:12:52.914550

#define ARC_THRESHOLD 0.0500

// Input Feature Order:
// [0] cycle_nmse
// [1] zcv
// [2] zc_dwell_ratio
// [3] pulse_count_per_cycle
// [4] peak_fluct_cv
// [5] midband_residual_rms
// [6] hf_band_energy_ratio
// [7] wpe_entropy
// [8] spec_entropy
// [9] thd_i

// output[0] = Probability of Normal
// output[1] = Probability of Arc Fault

#include <string.h>
static inline void add_vectors(double *v1, double *v2, int size, double *result) {
    for(int i = 0; i < size; ++i)
        result[i] = v1[i] + v2[i];
}
static inline void mul_vector_number(double *v1, double num, int size, double *result) {
    for(int i = 0; i < size; ++i)
        result[i] = v1[i] * num;
}
static inline void set_output2(double *dst, double a, double b) {
    dst[0] = a;
    dst[1] = b;
}
static inline void arc_rf_predict(double * input, double * output) {
    double var0[2];
    double var1[2];
    double var2[2];
    double var3[2];
    double var4[2];
    double var5[2];
    double var6[2];
    double var7[2];
    double var8[2];
    double var9[2];
    double var10[2];
    double var11[2];
    double var12[2];
    double var13[2];
    double var14[2];
    double var15[2];
    double var16[2];
    double var17[2];
    double var18[2];
    double var19[2];
    double var20[2];
    double var21[2];
    double var22[2];
    double var23[2];
    double var24[2];
    double var25[2];
    double var26[2];
    double var27[2];
    double var28[2];
    double var29[2];
    double var30[2];
    double var31[2];
    double var32[2];
    double var33[2];
    double var34[2];
    double var35[2];
    double var36[2];
    double var37[2];
    double var38[2];
    double var39[2];
    double var40[2];
    double var41[2];
    double var42[2];
    double var43[2];
    double var44[2];
    double var45[2];
    double var46[2];
    double var47[2];
    double var48[2];
    double var49[2];
    double var50[2];
    double var51[2];
    double var52[2];
    double var53[2];
    double var54[2];
    double var55[2];
    double var56[2];
    double var57[2];
    double var58[2];
    double var59[2];
    double var60[2];
    double var61[2];
    double var62[2];
    double var63[2];
    double var64[2];
    double var65[2];
    double var66[2];
    double var67[2];
    double var68[2];
    double var69[2];
    double var70[2];
    double var71[2];
    double var72[2];
    double var73[2];
    double var74[2];
    double var75[2];
    double var76[2];
    double var77[2];
    double var78[2];
    double var79[2];
    double var80[2];
    if (input[4] <= 0.07767600193619728) {
        set_output2(var80, 1.0, 0.0);
    } else {
        if (input[3] <= 0.390000485694884) {
            set_output2(var80, 1.0, 0.0);
        } else {
            set_output2(var80, 0.0, 1.0);
        }
    }
    double var81[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var81, 1.0, 0.0);
    } else {
        set_output2(var81, 0.0, 1.0);
    }
    add_vectors(var80, var81, 2, var79);
    double var82[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var82, 1.0, 0.0);
    } else {
        set_output2(var82, 0.0, 1.0);
    }
    add_vectors(var79, var82, 2, var78);
    double var83[2];
    if (input[4] <= 0.07655100151896477) {
        set_output2(var83, 1.0, 0.0);
    } else {
        if (input[3] <= 0.390000485694884) {
            set_output2(var83, 1.0, 0.0);
        } else {
            set_output2(var83, 0.0, 1.0);
        }
    }
    add_vectors(var78, var83, 2, var77);
    double var84[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var84, 1.0, 0.0);
    } else {
        set_output2(var84, 0.0, 1.0);
    }
    add_vectors(var77, var84, 2, var76);
    double var85[2];
    if (input[0] <= 0.21372900158166885) {
        if (input[3] <= 0.390000485694884) {
            set_output2(var85, 1.0, 0.0);
        } else {
            set_output2(var85, 0.0, 1.0);
        }
    } else {
        if (input[3] <= 0.390000485694884) {
            set_output2(var85, 1.0, 0.0);
        } else {
            set_output2(var85, 0.0, 1.0);
        }
    }
    add_vectors(var76, var85, 2, var75);
    double var86[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var86, 1.0, 0.0);
    } else {
        set_output2(var86, 0.0, 1.0);
    }
    add_vectors(var75, var86, 2, var74);
    double var87[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var87, 1.0, 0.0);
    } else {
        set_output2(var87, 0.0, 1.0);
    }
    add_vectors(var74, var87, 2, var73);
    double var88[2];
    if (input[0] <= 0.2139120027422905) {
        if (input[3] <= 0.390000485694884) {
            set_output2(var88, 1.0, 0.0);
        } else {
            set_output2(var88, 0.0, 1.0);
        }
    } else {
        if (input[3] <= 0.390000485694884) {
            set_output2(var88, 1.0, 0.0);
        } else {
            set_output2(var88, 0.0, 1.0);
        }
    }
    add_vectors(var73, var88, 2, var72);
    double var89[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var89, 1.0, 0.0);
    } else {
        set_output2(var89, 0.0, 1.0);
    }
    add_vectors(var72, var89, 2, var71);
    double var90[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var90, 1.0, 0.0);
    } else {
        set_output2(var90, 0.0, 1.0);
    }
    add_vectors(var71, var90, 2, var70);
    double var91[2];
    if (input[4] <= 0.07706550136208534) {
        set_output2(var91, 1.0, 0.0);
    } else {
        if (input[3] <= 0.390000485694884) {
            set_output2(var91, 1.0, 0.0);
        } else {
            set_output2(var91, 0.0, 1.0);
        }
    }
    add_vectors(var70, var91, 2, var69);
    double var92[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var92, 1.0, 0.0);
    } else {
        set_output2(var92, 0.0, 1.0);
    }
    add_vectors(var69, var92, 2, var68);
    double var93[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var93, 1.0, 0.0);
    } else {
        set_output2(var93, 0.0, 1.0);
    }
    add_vectors(var68, var93, 2, var67);
    double var94[2];
    if (input[0] <= 0.21574299782514572) {
        if (input[4] <= 0.07655100151896477) {
            set_output2(var94, 1.0, 0.0);
        } else {
            if (input[1] <= 1.003843992948532) {
                if (input[3] <= 0.38999998569488525) {
                    set_output2(var94, 1.0, 0.0);
                } else {
                    set_output2(var94, 0.0, 1.0);
                }
            } else {
                set_output2(var94, 1.0, 0.0);
            }
        }
    } else {
        if (input[3] <= 0.390000485694884) {
            set_output2(var94, 1.0, 0.0);
        } else {
            set_output2(var94, 0.0, 1.0);
        }
    }
    add_vectors(var67, var94, 2, var66);
    double var95[2];
    if (input[0] <= 0.21485299617052078) {
        if (input[4] <= 0.07706550136208534) {
            set_output2(var95, 1.0, 0.0);
        } else {
            if (input[0] <= 0.1554820016026497) {
                set_output2(var95, 1.0, 0.0);
            } else {
                set_output2(var95, 0.0, 1.0);
            }
        }
    } else {
        if (input[4] <= 0.06993300095200539) {
            set_output2(var95, 1.0, 0.0);
        } else {
            if (input[3] <= 0.38999998569488525) {
                set_output2(var95, 1.0, 0.0);
            } else {
                set_output2(var95, 0.0, 1.0);
            }
        }
    }
    add_vectors(var66, var95, 2, var65);
    double var96[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var96, 1.0, 0.0);
    } else {
        set_output2(var96, 0.0, 1.0);
    }
    add_vectors(var65, var96, 2, var64);
    double var97[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var97, 1.0, 0.0);
    } else {
        set_output2(var97, 0.0, 1.0);
    }
    add_vectors(var64, var97, 2, var63);
    double var98[2];
    if (input[4] <= 0.07767600193619728) {
        set_output2(var98, 1.0, 0.0);
    } else {
        if (input[0] <= 0.1482814997434616) {
            set_output2(var98, 1.0, 0.0);
        } else {
            if (input[3] <= 0.390000485694884) {
                set_output2(var98, 1.0, 0.0);
            } else {
                set_output2(var98, 0.0, 1.0);
            }
        }
    }
    add_vectors(var63, var98, 2, var62);
    double var99[2];
    if (input[4] <= 0.07522749900817871) {
        set_output2(var99, 1.0, 0.0);
    } else {
        if (input[7] <= 0.19864200055599213) {
            set_output2(var99, 0.9638106186507391, 0.03618938134926089);
        } else {
            if (input[3] <= 0.390000485694884) {
                set_output2(var99, 1.0, 0.0);
            } else {
                set_output2(var99, 0.0, 1.0);
            }
        }
    }
    add_vectors(var62, var99, 2, var61);
    double var100[2];
    if (input[0] <= 0.216389000415802) {
        if (input[4] <= 0.07767600193619728) {
            set_output2(var100, 1.0, 0.0);
        } else {
            if (input[3] <= 0.390000485694884) {
                set_output2(var100, 1.0, 0.0);
            } else {
                set_output2(var100, 0.0, 1.0);
            }
        }
    } else {
        if (input[3] <= 0.390000485694884) {
            set_output2(var100, 1.0, 0.0);
        } else {
            set_output2(var100, 0.0, 1.0);
        }
    }
    add_vectors(var61, var100, 2, var60);
    double var101[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var101, 1.0, 0.0);
    } else {
        set_output2(var101, 0.0, 1.0);
    }
    add_vectors(var60, var101, 2, var59);
    double var102[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var102, 1.0, 0.0);
    } else {
        set_output2(var102, 0.0, 1.0);
    }
    add_vectors(var59, var102, 2, var58);
    double var103[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var103, 1.0, 0.0);
    } else {
        set_output2(var103, 0.0, 1.0);
    }
    add_vectors(var58, var103, 2, var57);
    double var104[2];
    if (input[4] <= 0.07767600193619728) {
        set_output2(var104, 1.0, 0.0);
    } else {
        if (input[3] <= 0.390000485694884) {
            set_output2(var104, 1.0, 0.0);
        } else {
            set_output2(var104, 0.0, 1.0);
        }
    }
    add_vectors(var57, var104, 2, var56);
    double var105[2];
    if (input[4] <= 0.07706550136208534) {
        set_output2(var105, 1.0, 0.0);
    } else {
        if (input[1] <= 2.1456010341644287) {
            if (input[0] <= 0.1554820016026497) {
                set_output2(var105, 1.0, 0.0);
            } else {
                if (input[3] <= 0.390000485694884) {
                    set_output2(var105, 1.0, 0.0);
                } else {
                    set_output2(var105, 0.0, 1.0);
                }
            }
        } else {
            set_output2(var105, 1.0, 0.0);
        }
    }
    add_vectors(var56, var105, 2, var55);
    double var106[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var106, 1.0, 0.0);
    } else {
        set_output2(var106, 0.0, 1.0);
    }
    add_vectors(var55, var106, 2, var54);
    double var107[2];
    if (input[0] <= 0.20991649478673935) {
        if (input[3] <= 0.390000485694884) {
            set_output2(var107, 1.0, 0.0);
        } else {
            set_output2(var107, 0.0, 1.0);
        }
    } else {
        if (input[4] <= 0.06993300095200539) {
            set_output2(var107, 1.0, 0.0);
        } else {
            if (input[3] <= 0.390000485694884) {
                set_output2(var107, 1.0, 0.0);
            } else {
                set_output2(var107, 0.0, 1.0);
            }
        }
    }
    add_vectors(var54, var107, 2, var53);
    double var108[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var108, 1.0, 0.0);
    } else {
        set_output2(var108, 0.0, 1.0);
    }
    add_vectors(var53, var108, 2, var52);
    double var109[2];
    if (input[4] <= 0.07706550136208534) {
        set_output2(var109, 1.0, 0.0);
    } else {
        if (input[3] <= 0.390000485694884) {
            set_output2(var109, 1.0, 0.0);
        } else {
            set_output2(var109, 0.0, 1.0);
        }
    }
    add_vectors(var52, var109, 2, var51);
    double var110[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var110, 1.0, 0.0);
    } else {
        set_output2(var110, 0.0, 1.0);
    }
    add_vectors(var51, var110, 2, var50);
    double var111[2];
    if (input[4] <= 0.07767600193619728) {
        set_output2(var111, 1.0, 0.0);
    } else {
        if (input[3] <= 0.390000485694884) {
            set_output2(var111, 1.0, 0.0);
        } else {
            set_output2(var111, 0.0, 1.0);
        }
    }
    add_vectors(var50, var111, 2, var49);
    double var112[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var112, 1.0, 0.0);
    } else {
        set_output2(var112, 0.0, 1.0);
    }
    add_vectors(var49, var112, 2, var48);
    double var113[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var113, 1.0, 0.0);
    } else {
        set_output2(var113, 0.0, 1.0);
    }
    add_vectors(var48, var113, 2, var47);
    double var114[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var114, 1.0, 0.0);
    } else {
        set_output2(var114, 0.0, 1.0);
    }
    add_vectors(var47, var114, 2, var46);
    double var115[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var115, 1.0, 0.0);
    } else {
        set_output2(var115, 0.0, 1.0);
    }
    add_vectors(var46, var115, 2, var45);
    double var116[2];
    if (input[7] <= 0.30133649706840515) {
        if (input[3] <= 0.390000485694884) {
            set_output2(var116, 1.0, 0.0);
        } else {
            set_output2(var116, 0.0, 1.0);
        }
    } else {
        if (input[4] <= 0.06564650125801563) {
            set_output2(var116, 1.0, 0.0);
        } else {
            if (input[1] <= 2.2808135747909546) {
                set_output2(var116, 0.001798781359562907, 0.9982012186404371);
            } else {
                set_output2(var116, 1.0, 0.0);
            }
        }
    }
    add_vectors(var45, var116, 2, var44);
    double var117[2];
    if (input[0] <= 0.22000399976968765) {
        if (input[3] <= 0.390000485694884) {
            set_output2(var117, 1.0, 0.0);
        } else {
            set_output2(var117, 0.0, 1.0);
        }
    } else {
        if (input[4] <= 0.06993300095200539) {
            set_output2(var117, 1.0, 0.0);
        } else {
            if (input[0] <= 0.9964255094528198) {
                if (input[8] <= 0.4676255136728287) {
                    set_output2(var117, 1.0, 0.0);
                } else {
                    set_output2(var117, 0.0011524578467009092, 0.9988475421532992);
                }
            } else {
                set_output2(var117, 1.0, 0.0);
            }
        }
    }
    add_vectors(var44, var117, 2, var43);
    double var118[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var118, 1.0, 0.0);
    } else {
        set_output2(var118, 0.0, 1.0);
    }
    add_vectors(var43, var118, 2, var42);
    double var119[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var119, 1.0, 0.0);
    } else {
        set_output2(var119, 0.0, 1.0);
    }
    add_vectors(var42, var119, 2, var41);
    double var120[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var120, 1.0, 0.0);
    } else {
        set_output2(var120, 0.0, 1.0);
    }
    add_vectors(var41, var120, 2, var40);
    double var121[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var121, 1.0, 0.0);
    } else {
        set_output2(var121, 0.0, 1.0);
    }
    add_vectors(var40, var121, 2, var39);
    double var122[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var122, 1.0, 0.0);
    } else {
        set_output2(var122, 0.0, 1.0);
    }
    add_vectors(var39, var122, 2, var38);
    double var123[2];
    if (input[4] <= 0.07767600193619728) {
        set_output2(var123, 1.0, 0.0);
    } else {
        if (input[3] <= 0.390000485694884) {
            set_output2(var123, 1.0, 0.0);
        } else {
            set_output2(var123, 0.0, 1.0);
        }
    }
    add_vectors(var38, var123, 2, var37);
    double var124[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var124, 1.0, 0.0);
    } else {
        set_output2(var124, 0.0, 1.0);
    }
    add_vectors(var37, var124, 2, var36);
    double var125[2];
    if (input[4] <= 0.07767600193619728) {
        set_output2(var125, 1.0, 0.0);
    } else {
        if (input[3] <= 0.390000485694884) {
            set_output2(var125, 1.0, 0.0);
        } else {
            set_output2(var125, 0.0, 1.0);
        }
    }
    add_vectors(var36, var125, 2, var35);
    double var126[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var126, 1.0, 0.0);
    } else {
        set_output2(var126, 0.0, 1.0);
    }
    add_vectors(var35, var126, 2, var34);
    double var127[2];
    if (input[4] <= 0.07767600193619728) {
        set_output2(var127, 1.0, 0.0);
    } else {
        if (input[3] <= 0.390000485694884) {
            set_output2(var127, 1.0, 0.0);
        } else {
            set_output2(var127, 0.0, 1.0);
        }
    }
    add_vectors(var34, var127, 2, var33);
    double var128[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var128, 1.0, 0.0);
    } else {
        set_output2(var128, 0.0, 1.0);
    }
    add_vectors(var33, var128, 2, var32);
    double var129[2];
    if (input[4] <= 0.07706550136208534) {
        set_output2(var129, 1.0, 0.0);
    } else {
        if (input[7] <= 0.2109529972076416) {
            set_output2(var129, 0.8908917996824465, 0.10910820031755362);
        } else {
            if (input[3] <= 0.38999998569488525) {
                set_output2(var129, 1.0, 0.0);
            } else {
                set_output2(var129, 0.0, 1.0);
            }
        }
    }
    add_vectors(var32, var129, 2, var31);
    double var130[2];
    if (input[0] <= 0.2159854993224144) {
        if (input[0] <= 0.15999049693346024) {
            set_output2(var130, 1.0, 0.0);
        } else {
            if (input[3] <= 0.390000485694884) {
                set_output2(var130, 1.0, 0.0);
            } else {
                set_output2(var130, 0.0, 1.0);
            }
        }
    } else {
        if (input[3] <= 0.390000485694884) {
            set_output2(var130, 1.0, 0.0);
        } else {
            set_output2(var130, 0.0, 1.0);
        }
    }
    add_vectors(var31, var130, 2, var30);
    double var131[2];
    if (input[0] <= 0.21640999615192413) {
        if (input[0] <= 0.15999049693346024) {
            set_output2(var131, 1.0, 0.0);
        } else {
            if (input[2] <= 0.5096569955348969) {
                set_output2(var131, 0.02507857311638858, 0.9749214268836115);
            } else {
                set_output2(var131, 1.0, 0.0);
            }
        }
    } else {
        if (input[4] <= 0.06993300095200539) {
            set_output2(var131, 1.0, 0.0);
        } else {
            if (input[3] <= 0.38999998569488525) {
                set_output2(var131, 1.0, 0.0);
            } else {
                set_output2(var131, 0.0, 1.0);
            }
        }
    }
    add_vectors(var30, var131, 2, var29);
    double var132[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var132, 1.0, 0.0);
    } else {
        set_output2(var132, 0.0, 1.0);
    }
    add_vectors(var29, var132, 2, var28);
    double var133[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var133, 1.0, 0.0);
    } else {
        set_output2(var133, 0.0, 1.0);
    }
    add_vectors(var28, var133, 2, var27);
    double var134[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var134, 1.0, 0.0);
    } else {
        set_output2(var134, 0.0, 1.0);
    }
    add_vectors(var27, var134, 2, var26);
    double var135[2];
    if (input[4] <= 0.07767600193619728) {
        set_output2(var135, 1.0, 0.0);
    } else {
        if (input[7] <= 0.17392800003290176) {
            set_output2(var135, 1.0, 0.0);
        } else {
            if (input[0] <= 0.9964255094528198) {
                if (input[3] <= 0.38999998569488525) {
                    set_output2(var135, 1.0, 0.0);
                } else {
                    set_output2(var135, 0.0, 1.0);
                }
            } else {
                set_output2(var135, 1.0, 0.0);
            }
        }
    }
    add_vectors(var26, var135, 2, var25);
    double var136[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var136, 1.0, 0.0);
    } else {
        set_output2(var136, 0.0, 1.0);
    }
    add_vectors(var25, var136, 2, var24);
    double var137[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var137, 1.0, 0.0);
    } else {
        set_output2(var137, 0.0, 1.0);
    }
    add_vectors(var24, var137, 2, var23);
    double var138[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var138, 1.0, 0.0);
    } else {
        set_output2(var138, 0.0, 1.0);
    }
    add_vectors(var23, var138, 2, var22);
    double var139[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var139, 1.0, 0.0);
    } else {
        set_output2(var139, 0.0, 1.0);
    }
    add_vectors(var22, var139, 2, var21);
    double var140[2];
    if (input[4] <= 0.07706550136208534) {
        set_output2(var140, 1.0, 0.0);
    } else {
        if (input[3] <= 0.38999998569488525) {
            set_output2(var140, 1.0, 0.0);
        } else {
            set_output2(var140, 0.0, 1.0);
        }
    }
    add_vectors(var21, var140, 2, var20);
    double var141[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var141, 1.0, 0.0);
    } else {
        set_output2(var141, 0.0, 1.0);
    }
    add_vectors(var20, var141, 2, var19);
    double var142[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var142, 1.0, 0.0);
    } else {
        set_output2(var142, 0.0, 1.0);
    }
    add_vectors(var19, var142, 2, var18);
    double var143[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var143, 1.0, 0.0);
    } else {
        set_output2(var143, 0.0, 1.0);
    }
    add_vectors(var18, var143, 2, var17);
    double var144[2];
    if (input[4] <= 0.07767600193619728) {
        set_output2(var144, 1.0, 0.0);
    } else {
        if (input[3] <= 0.390000485694884) {
            set_output2(var144, 1.0, 0.0);
        } else {
            set_output2(var144, 0.0, 1.0);
        }
    }
    add_vectors(var17, var144, 2, var16);
    double var145[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var145, 1.0, 0.0);
    } else {
        set_output2(var145, 0.0, 1.0);
    }
    add_vectors(var16, var145, 2, var15);
    double var146[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var146, 1.0, 0.0);
    } else {
        set_output2(var146, 0.0, 1.0);
    }
    add_vectors(var15, var146, 2, var14);
    double var147[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var147, 1.0, 0.0);
    } else {
        set_output2(var147, 0.0, 1.0);
    }
    add_vectors(var14, var147, 2, var13);
    double var148[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var148, 1.0, 0.0);
    } else {
        set_output2(var148, 0.0, 1.0);
    }
    add_vectors(var13, var148, 2, var12);
    double var149[2];
    if (input[0] <= 0.19616400450468063) {
        if (input[3] <= 0.390000485694884) {
            set_output2(var149, 1.0, 0.0);
        } else {
            set_output2(var149, 0.0, 1.0);
        }
    } else {
        if (input[3] <= 0.390000485694884) {
            set_output2(var149, 1.0, 0.0);
        } else {
            set_output2(var149, 0.0, 1.0);
        }
    }
    add_vectors(var12, var149, 2, var11);
    double var150[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var150, 1.0, 0.0);
    } else {
        set_output2(var150, 0.0, 1.0);
    }
    add_vectors(var11, var150, 2, var10);
    double var151[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var151, 1.0, 0.0);
    } else {
        set_output2(var151, 0.0, 1.0);
    }
    add_vectors(var10, var151, 2, var9);
    double var152[2];
    if (input[4] <= 0.07767600193619728) {
        set_output2(var152, 1.0, 0.0);
    } else {
        if (input[3] <= 0.390000485694884) {
            set_output2(var152, 1.0, 0.0);
        } else {
            set_output2(var152, 0.0, 1.0);
        }
    }
    add_vectors(var9, var152, 2, var8);
    double var153[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var153, 1.0, 0.0);
    } else {
        set_output2(var153, 0.0, 1.0);
    }
    add_vectors(var8, var153, 2, var7);
    double var154[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var154, 1.0, 0.0);
    } else {
        set_output2(var154, 0.0, 1.0);
    }
    add_vectors(var7, var154, 2, var6);
    double var155[2];
    if (input[4] <= 0.07655100151896477) {
        set_output2(var155, 1.0, 0.0);
    } else {
        if (input[7] <= 0.19787800312042236) {
            set_output2(var155, 0.9492602328599513, 0.050739767140048714);
        } else {
            if (input[0] <= 1.0221894979476929) {
                if (input[8] <= 0.5079770088195801) {
                    set_output2(var155, 0.9383492362108844, 0.061650763789115604);
                } else {
                    set_output2(var155, 0.0006268899476799836, 0.99937311005232);
                }
            } else {
                set_output2(var155, 1.0, 0.0);
            }
        }
    }
    add_vectors(var6, var155, 2, var5);
    double var156[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var156, 1.0, 0.0);
    } else {
        set_output2(var156, 0.0, 1.0);
    }
    add_vectors(var5, var156, 2, var4);
    double var157[2];
    if (input[0] <= 0.21518699824810028) {
        if (input[6] <= 0.057053498923778534) {
            if (input[0] <= 0.1282219998538494) {
                set_output2(var157, 1.0, 0.0);
            } else {
                set_output2(var157, 0.0, 1.0);
            }
        } else {
            if (input[3] <= 0.390000485694884) {
                set_output2(var157, 1.0, 0.0);
            } else {
                set_output2(var157, 0.0, 1.0);
            }
        }
    } else {
        if (input[3] <= 0.390000485694884) {
            set_output2(var157, 1.0, 0.0);
        } else {
            set_output2(var157, 0.0, 1.0);
        }
    }
    add_vectors(var4, var157, 2, var3);
    double var158[2];
    if (input[4] <= 0.07767600193619728) {
        set_output2(var158, 1.0, 0.0);
    } else {
        if (input[3] <= 0.390000485694884) {
            set_output2(var158, 1.0, 0.0);
        } else {
            set_output2(var158, 0.0, 1.0);
        }
    }
    add_vectors(var3, var158, 2, var2);
    double var159[2];
    if (input[3] <= 0.390000485694884) {
        set_output2(var159, 1.0, 0.0);
    } else {
        set_output2(var159, 0.0, 1.0);
    }
    add_vectors(var2, var159, 2, var1);
    mul_vector_number(var1, 0.0125, 2, var0);
    memcpy(output, var0, 2 * sizeof(double));
}

