#pragma once
// Auto-generated by m2cgen from scikit-learn RandomForest
// Generated on: 2026-03-25 07:03:41.260676

#define ARC_THRESHOLD 0.5500

// Input Feature Order:
// [0] cycle_nmse
// [1] zcv
// [2] zc_dwell_ratio
// [3] pulse_count_per_cycle
// [4] peak_fluct_cv
// [5] midband_residual_rms
// [6] hf_band_energy_ratio
// [7] wpe_entropy
// [8] spec_entropy
// [9] thd_i

// output[0] = Probability of Normal
// output[1] = Probability of Arc Fault

#include <string.h>
static inline void add_vectors(double *v1, double *v2, int size, double *result) {
    for(int i = 0; i < size; ++i)
        result[i] = v1[i] + v2[i];
}
static inline void mul_vector_number(double *v1, double num, int size, double *result) {
    for(int i = 0; i < size; ++i)
        result[i] = v1[i] * num;
}
static inline void set_output2(double *dst, double a, double b) {
    dst[0] = a;
    dst[1] = b;
}
static inline void arc_rf_predict(double * input, double * output) {
    double var0[2];
    double var1[2];
    double var2[2];
    double var3[2];
    double var4[2];
    double var5[2];
    double var6[2];
    double var7[2];
    double var8[2];
    double var9[2];
    double var10[2];
    double var11[2];
    double var12[2];
    double var13[2];
    double var14[2];
    double var15[2];
    double var16[2];
    double var17[2];
    double var18[2];
    double var19[2];
    double var20[2];
    double var21[2];
    double var22[2];
    double var23[2];
    double var24[2];
    double var25[2];
    double var26[2];
    double var27[2];
    double var28[2];
    double var29[2];
    double var30[2];
    double var31[2];
    double var32[2];
    double var33[2];
    double var34[2];
    double var35[2];
    double var36[2];
    double var37[2];
    double var38[2];
    double var39[2];
    double var40[2];
    double var41[2];
    double var42[2];
    double var43[2];
    double var44[2];
    double var45[2];
    double var46[2];
    double var47[2];
    double var48[2];
    double var49[2];
    double var50[2];
    double var51[2];
    double var52[2];
    double var53[2];
    double var54[2];
    double var55[2];
    double var56[2];
    double var57[2];
    double var58[2];
    double var59[2];
    double var60[2];
    double var61[2];
    double var62[2];
    double var63[2];
    double var64[2];
    double var65[2];
    double var66[2];
    double var67[2];
    double var68[2];
    double var69[2];
    double var70[2];
    double var71[2];
    double var72[2];
    double var73[2];
    double var74[2];
    double var75[2];
    double var76[2];
    double var77[2];
    double var78[2];
    double var79[2];
    double var80[2];
    if (input[4] <= 0.07958531379699707) {
        set_output2(var80, 1.0, 0.0);
    } else {
        if (input[3] <= 0.7845554351806641) {
            set_output2(var80, 1.0, 0.0);
        } else {
            if (input[0] <= 1.003672182559967) {
                set_output2(var80, 0.0007528860632424275, 0.9992471139367576);
            } else {
                set_output2(var80, 1.0, 0.0);
            }
        }
    }
    double var81[2];
    if (input[4] <= 0.07932857051491737) {
        set_output2(var81, 1.0, 0.0);
    } else {
        if (input[0] <= 0.926703691482544) {
            if (input[7] <= 0.3358839303255081) {
                set_output2(var81, 1.0, 0.0);
            } else {
                set_output2(var81, 0.001099365750528537, 0.9989006342494715);
            }
        } else {
            set_output2(var81, 1.0, 0.0);
        }
    }
    add_vectors(var80, var81, 2, var79);
    double var82[2];
    if (input[4] <= 0.07932857051491737) {
        set_output2(var82, 1.0, 0.0);
    } else {
        if (input[0] <= 0.8913437128067017) {
            if (input[7] <= 0.30872292816638947) {
                set_output2(var82, 1.0, 0.0);
            } else {
                if (input[1] <= 1.6128491759300232) {
                    set_output2(var82, 0.0004238724991522816, 0.9995761275008477);
                } else {
                    set_output2(var82, 1.0, 0.0);
                }
            }
        } else {
            set_output2(var82, 1.0, 0.0);
        }
    }
    add_vectors(var79, var82, 2, var78);
    double var83[2];
    if (input[4] <= 0.07957006990909576) {
        set_output2(var83, 1.0, 0.0);
    } else {
        if (input[3] <= 0.7910895943641663) {
            set_output2(var83, 1.0, 0.0);
        } else {
            if (input[0] <= 1.096898466348648) {
                set_output2(var83, 0.000417188151856467, 0.9995828118481435);
            } else {
                set_output2(var83, 1.0, 0.0);
            }
        }
    }
    add_vectors(var78, var83, 2, var77);
    double var84[2];
    if (input[4] <= 0.07957006990909576) {
        set_output2(var84, 1.0, 0.0);
    } else {
        if (input[3] <= 0.7845554351806641) {
            set_output2(var84, 1.0, 0.0);
        } else {
            if (input[0] <= 1.003672182559967) {
                set_output2(var84, 0.0005871990604814962, 0.9994128009395186);
            } else {
                set_output2(var84, 1.0, 0.0);
            }
        }
    }
    add_vectors(var77, var84, 2, var76);
    double var85[2];
    if (input[0] <= 0.15004785358905792) {
        set_output2(var85, 1.0, 0.0);
    } else {
        if (input[4] <= 0.07810291275382042) {
            set_output2(var85, 1.0, 0.0);
        } else {
            if (input[3] <= 0.7910895943641663) {
                set_output2(var85, 1.0, 0.0);
            } else {
                if (input[0] <= 1.003672182559967) {
                    set_output2(var85, 0.000587544065804931, 0.999412455934195);
                } else {
                    set_output2(var85, 1.0, 0.0);
                }
            }
        }
    }
    add_vectors(var76, var85, 2, var75);
    double var86[2];
    if (input[4] <= 0.07957006990909576) {
        set_output2(var86, 1.0, 0.0);
    } else {
        if (input[3] <= 0.7910895943641663) {
            set_output2(var86, 1.0, 0.0);
        } else {
            if (input[2] <= 0.7823151051998138) {
                set_output2(var86, 0.00025252525252522856, 0.9997474747474748);
            } else {
                set_output2(var86, 1.0, 0.0);
            }
        }
    }
    add_vectors(var75, var86, 2, var74);
    double var87[2];
    if (input[3] <= 0.8029036819934845) {
        set_output2(var87, 0.9997184790949407, 0.00028152090505935944);
    } else {
        if (input[0] <= 0.1453876867890358) {
            set_output2(var87, 1.0, 0.0);
        } else {
            if (input[4] <= 0.07810291275382042) {
                set_output2(var87, 1.0, 0.0);
            } else {
                if (input[1] <= 1.2709996700286865) {
                    set_output2(var87, 0.000417228920871137, 0.9995827710791289);
                } else {
                    set_output2(var87, 1.0, 0.0);
                }
            }
        }
    }
    add_vectors(var74, var87, 2, var73);
    double var88[2];
    if (input[0] <= 0.15004785358905792) {
        set_output2(var88, 1.0, 0.0);
    } else {
        if (input[4] <= 0.07810291275382042) {
            set_output2(var88, 1.0, 0.0);
        } else {
            if (input[0] <= 0.8913437128067017) {
                if (input[3] <= 0.49276767671108246) {
                    set_output2(var88, 1.0, 0.0);
                } else {
                    set_output2(var88, 0.0005920162381596202, 0.9994079837618404);
                }
            } else {
                set_output2(var88, 1.0, 0.0);
            }
        }
    }
    add_vectors(var73, var88, 2, var72);
    double var89[2];
    if (input[4] <= 0.07957006990909576) {
        set_output2(var89, 1.0, 0.0);
    } else {
        if (input[3] <= 0.7910895943641663) {
            set_output2(var89, 1.0, 0.0);
        } else {
            if (input[2] <= 0.7768287360668182) {
                set_output2(var89, 0.0009248360517908176, 0.9990751639482092);
            } else {
                set_output2(var89, 1.0, 0.0);
            }
        }
    }
    add_vectors(var72, var89, 2, var71);
    double var90[2];
    if (input[3] <= 0.7979046404361725) {
        set_output2(var90, 1.0, 0.0);
    } else {
        if (input[4] <= 0.07810291275382042) {
            set_output2(var90, 1.0, 0.0);
        } else {
            if (input[0] <= 1.003672182559967) {
                set_output2(var90, 0.00025395750444426264, 0.9997460424955558);
            } else {
                set_output2(var90, 1.0, 0.0);
            }
        }
    }
    add_vectors(var71, var90, 2, var70);
    double var91[2];
    if (input[4] <= 0.07957006990909576) {
        set_output2(var91, 1.0, 0.0);
    } else {
        if (input[3] <= 0.7910895943641663) {
            set_output2(var91, 1.0, 0.0);
        } else {
            if (input[0] <= 1.003625601530075) {
                set_output2(var91, 0.00033388981636059287, 0.9996661101836395);
            } else {
                set_output2(var91, 1.0, 0.0);
            }
        }
    }
    add_vectors(var70, var91, 2, var69);
    double var92[2];
    if (input[3] <= 0.7979046404361725) {
        set_output2(var92, 1.0, 0.0);
    } else {
        if (input[4] <= 0.07568269595503807) {
            set_output2(var92, 1.0, 0.0);
        } else {
            if (input[2] <= 0.7768287360668182) {
                set_output2(var92, 0.0004204860819107045, 0.9995795139180892);
            } else {
                set_output2(var92, 1.0, 0.0);
            }
        }
    }
    add_vectors(var69, var92, 2, var68);
    double var93[2];
    if (input[4] <= 0.07957006990909576) {
        set_output2(var93, 1.0, 0.0);
    } else {
        if (input[0] <= 0.8913437128067017) {
            if (input[1] <= 1.4063482880592346) {
                if (input[3] <= 0.4251395668834448) {
                    set_output2(var93, 1.0, 0.0);
                } else {
                    set_output2(var93, 0.0, 1.0);
                }
            } else {
                set_output2(var93, 1.0, 0.0);
            }
        } else {
            set_output2(var93, 1.0, 0.0);
        }
    }
    add_vectors(var68, var93, 2, var67);
    double var94[2];
    if (input[0] <= 0.15000467002391815) {
        set_output2(var94, 1.0, 0.0);
    } else {
        if (input[4] <= 0.07810291275382042) {
            set_output2(var94, 1.0, 0.0);
        } else {
            if (input[1] <= 1.268185794353485) {
                if (input[4] <= 0.7918736636638641) {
                    set_output2(var94, 0.0010805419333388192, 0.9989194580666612);
                } else {
                    set_output2(var94, 1.0, 0.0);
                }
            } else {
                set_output2(var94, 1.0, 0.0);
            }
        }
    }
    add_vectors(var67, var94, 2, var66);
    double var95[2];
    if (input[0] <= 0.15000467002391815) {
        set_output2(var95, 1.0, 0.0);
    } else {
        if (input[4] <= 0.07811815664172173) {
            set_output2(var95, 1.0, 0.0);
        } else {
            if (input[0] <= 0.8913437128067017) {
                set_output2(var95, 0.0017431725740848134, 0.9982568274259153);
            } else {
                set_output2(var95, 1.0, 0.0);
            }
        }
    }
    add_vectors(var66, var95, 2, var65);
    double var96[2];
    if (input[4] <= 0.07934381440281868) {
        set_output2(var96, 1.0, 0.0);
    } else {
        if (input[3] <= 0.7910895943641663) {
            set_output2(var96, 1.0, 0.0);
        } else {
            if (input[0] <= 1.003672182559967) {
                set_output2(var96, 0.000584648793117813, 0.9994153512068822);
            } else {
                set_output2(var96, 1.0, 0.0);
            }
        }
    }
    add_vectors(var65, var96, 2, var64);
    double var97[2];
    if (input[4] <= 0.07957006990909576) {
        set_output2(var97, 1.0, 0.0);
    } else {
        if (input[3] <= 0.6935315430164337) {
            set_output2(var97, 1.0, 0.0);
        } else {
            if (input[0] <= 1.09694504737854) {
                set_output2(var97, 0.0004992926687193218, 0.9995007073312807);
            } else {
                set_output2(var97, 1.0, 0.0);
            }
        }
    }
    add_vectors(var64, var97, 2, var63);
    double var98[2];
    if (input[4] <= 0.07958531379699707) {
        set_output2(var98, 1.0, 0.0);
    } else {
        if (input[3] <= 0.7845554351806641) {
            set_output2(var98, 1.0, 0.0);
        } else {
            if (input[2] <= 0.7768287360668182) {
                set_output2(var98, 0.0006714225765841318, 0.9993285774234159);
            } else {
                set_output2(var98, 1.0, 0.0);
            }
        }
    }
    add_vectors(var63, var98, 2, var62);
    double var99[2];
    if (input[4] <= 0.07958531379699707) {
        set_output2(var99, 1.0, 0.0);
    } else {
        if (input[0] <= 0.8912971317768097) {
            if (input[7] <= 0.3002794235944748) {
                set_output2(var99, 1.0, 0.0);
            } else {
                if (input[1] <= 1.6128491759300232) {
                    set_output2(var99, 0.0005068851905043489, 0.9994931148094957);
                } else {
                    set_output2(var99, 1.0, 0.0);
                }
            }
        } else {
            set_output2(var99, 1.0, 0.0);
        }
    }
    add_vectors(var62, var99, 2, var61);
    double var100[2];
    if (input[0] <= 0.15017057210206985) {
        set_output2(var100, 1.0, 0.0);
    } else {
        if (input[4] <= 0.07810291275382042) {
            set_output2(var100, 1.0, 0.0);
        } else {
            if (input[0] <= 0.8913437128067017) {
                if (input[3] <= 0.5110464096069336) {
                    set_output2(var100, 1.0, 0.0);
                } else {
                    set_output2(var100, 0.0002518045996307105, 0.9997481954003692);
                }
            } else {
                set_output2(var100, 1.0, 0.0);
            }
        }
    }
    add_vectors(var61, var100, 2, var60);
    double var101[2];
    if (input[4] <= 0.07957006990909576) {
        set_output2(var101, 1.0, 0.0);
    } else {
        if (input[3] <= 0.7910895943641663) {
            set_output2(var101, 1.0, 0.0);
        } else {
            if (input[0] <= 1.003625601530075) {
                set_output2(var101, 0.0005913161006926816, 0.9994086838993073);
            } else {
                set_output2(var101, 1.0, 0.0);
            }
        }
    }
    add_vectors(var60, var101, 2, var59);
    double var102[2];
    if (input[4] <= 0.07957006990909576) {
        set_output2(var102, 1.0, 0.0);
    } else {
        if (input[3] <= 0.7910895943641663) {
            set_output2(var102, 1.0, 0.0);
        } else {
            if (input[1] <= 1.2709996700286865) {
                set_output2(var102, 0.0007525712852245513, 0.9992474287147755);
            } else {
                set_output2(var102, 1.0, 0.0);
            }
        }
    }
    add_vectors(var59, var102, 2, var58);
    double var103[2];
    if (input[3] <= 0.8029036819934845) {
        set_output2(var103, 0.9998574762047729, 0.00014252379522709403);
    } else {
        if (input[4] <= 0.07810291275382042) {
            set_output2(var103, 1.0, 0.0);
        } else {
            if (input[2] <= 0.7823151051998138) {
                set_output2(var103, 0.00033103320075917773, 0.9996689667992409);
            } else {
                set_output2(var103, 1.0, 0.0);
            }
        }
    }
    add_vectors(var58, var103, 2, var57);
    double var104[2];
    if (input[4] <= 0.07932857051491737) {
        set_output2(var104, 1.0, 0.0);
    } else {
        if (input[3] <= 0.7910895943641663) {
            set_output2(var104, 1.0, 0.0);
        } else {
            if (input[2] <= 0.7768287360668182) {
                set_output2(var104, 0.000500083347224537, 0.9994999166527755);
            } else {
                set_output2(var104, 1.0, 0.0);
            }
        }
    }
    add_vectors(var57, var104, 2, var56);
    double var105[2];
    if (input[4] <= 0.07906606048345566) {
        set_output2(var105, 1.0, 0.0);
    } else {
        if (input[1] <= 1.268185794353485) {
            if (input[0] <= 1.0347822904586792) {
                if (input[3] <= 0.4251395668834448) {
                    set_output2(var105, 1.0, 0.0);
                } else {
                    set_output2(var105, 0.0, 1.0);
                }
            } else {
                set_output2(var105, 1.0, 0.0);
            }
        } else {
            set_output2(var105, 1.0, 0.0);
        }
    }
    add_vectors(var56, var105, 2, var55);
    double var106[2];
    if (input[3] <= 0.8029036819934845) {
        set_output2(var106, 0.9995810620078102, 0.0004189379921897753);
    } else {
        if (input[4] <= 0.07810291275382042) {
            set_output2(var106, 1.0, 0.0);
        } else {
            if (input[2] <= 0.7823151051998138) {
                set_output2(var106, 0.0004191712714649697, 0.9995808287285349);
            } else {
                set_output2(var106, 1.0, 0.0);
            }
        }
    }
    add_vectors(var55, var106, 2, var54);
    double var107[2];
    if (input[0] <= 0.15004785358905792) {
        set_output2(var107, 1.0, 0.0);
    } else {
        if (input[4] <= 0.07810291275382042) {
            set_output2(var107, 1.0, 0.0);
        } else {
            if (input[0] <= 0.926657110452652) {
                if (input[5] <= 0.014472305309027433) {
                    set_output2(var107, 1.0, 0.0);
                } else {
                    if (input[3] <= 0.493181511759758) {
                        set_output2(var107, 1.0, 0.0);
                    } else {
                        set_output2(var107, 0.0, 1.0);
                    }
                }
            } else {
                set_output2(var107, 1.0, 0.0);
            }
        }
    }
    add_vectors(var54, var107, 2, var53);
    double var108[2];
    if (input[3] <= 0.7939420342445374) {
        set_output2(var108, 1.0, 0.0);
    } else {
        if (input[4] <= 0.07810291275382042) {
            set_output2(var108, 1.0, 0.0);
        } else {
            if (input[5] <= 0.018722696229815483) {
                set_output2(var108, 1.0, 0.0);
            } else {
                if (input[0] <= 1.096898466348648) {
                    set_output2(var108, 0.0, 1.0);
                } else {
                    set_output2(var108, 1.0, 0.0);
                }
            }
        }
    }
    add_vectors(var53, var108, 2, var52);
    double var109[2];
    if (input[4] <= 0.07934381440281868) {
        set_output2(var109, 1.0, 0.0);
    } else {
        if (input[1] <= 1.2709996700286865) {
            if (input[3] <= 0.511388473212719) {
                set_output2(var109, 1.0, 0.0);
            } else {
                set_output2(var109, 0.0007500625052087399, 0.9992499374947913);
            }
        } else {
            set_output2(var109, 1.0, 0.0);
        }
    }
    add_vectors(var52, var109, 2, var51);
    double var110[2];
    if (input[4] <= 0.07932857051491737) {
        set_output2(var110, 1.0, 0.0);
    } else {
        if (input[3] <= 0.7910895943641663) {
            set_output2(var110, 1.0, 0.0);
        } else {
            if (input[1] <= 1.2709996700286865) {
                set_output2(var110, 0.0005025125628140514, 0.9994974874371859);
            } else {
                set_output2(var110, 1.0, 0.0);
            }
        }
    }
    add_vectors(var51, var110, 2, var50);
    double var111[2];
    if (input[4] <= 0.07932857051491737) {
        set_output2(var111, 1.0, 0.0);
    } else {
        if (input[3] <= 0.7910895943641663) {
            set_output2(var111, 1.0, 0.0);
        } else {
            if (input[0] <= 1.003672182559967) {
                set_output2(var111, 0.0002516567402063399, 0.9997483432597937);
            } else {
                set_output2(var111, 1.0, 0.0);
            }
        }
    }
    add_vectors(var50, var111, 2, var49);
    double var112[2];
    if (input[3] <= 0.7979046404361725) {
        set_output2(var112, 1.0, 0.0);
    } else {
        if (input[5] <= 0.019193409010767937) {
            set_output2(var112, 1.0, 0.0);
        } else {
            if (input[1] <= 1.2068321108818054) {
                if (input[6] <= 0.07543772086501122) {
                    set_output2(var112, 1.0, 0.0);
                } else {
                    set_output2(var112, 0.00016816614815437655, 0.9998318338518456);
                }
            } else {
                set_output2(var112, 1.0, 0.0);
            }
        }
    }
    add_vectors(var49, var112, 2, var48);
    double var113[2];
    if (input[3] <= 0.7979046404361725) {
        set_output2(var113, 1.0, 0.0);
    } else {
        if (input[4] <= 0.07783930376172066) {
            set_output2(var113, 1.0, 0.0);
        } else {
            if (input[0] <= 1.003625601530075) {
                set_output2(var113, 0.00025263157894736077, 0.9997473684210526);
            } else {
                set_output2(var113, 1.0, 0.0);
            }
        }
    }
    add_vectors(var48, var113, 2, var47);
    double var114[2];
    if (input[4] <= 0.07957006990909576) {
        set_output2(var114, 1.0, 0.0);
    } else {
        if (input[3] <= 0.7910895943641663) {
            set_output2(var114, 1.0, 0.0);
        } else {
            if (input[2] <= 0.7768287360668182) {
                set_output2(var114, 0.0005078720162519014, 0.9994921279837482);
            } else {
                set_output2(var114, 1.0, 0.0);
            }
        }
    }
    add_vectors(var47, var114, 2, var46);
    double var115[2];
    if (input[4] <= 0.07932857051491737) {
        set_output2(var115, 1.0, 0.0);
    } else {
        if (input[3] <= 0.7910895943641663) {
            set_output2(var115, 1.0, 0.0);
        } else {
            if (input[2] <= 0.7768159508705139) {
                set_output2(var115, 0.000592818428184249, 0.9994071815718159);
            } else {
                set_output2(var115, 1.0, 0.0);
            }
        }
    }
    add_vectors(var46, var115, 2, var45);
    double var116[2];
    if (input[7] <= 0.34911051392555237) {
        set_output2(var116, 1.0, 0.0);
    } else {
        if (input[4] <= 0.07905081659555435) {
            set_output2(var116, 1.0, 0.0);
        } else {
            if (input[2] <= 0.7066691219806671) {
                if (input[0] <= 0.8913437128067017) {
                    set_output2(var116, 0.0009995835068721882, 0.9990004164931279);
                } else {
                    set_output2(var116, 1.0, 0.0);
                }
            } else {
                set_output2(var116, 1.0, 0.0);
            }
        }
    }
    add_vectors(var45, var116, 2, var44);
    double var117[2];
    if (input[0] <= 0.15004785358905792) {
        set_output2(var117, 1.0, 0.0);
    } else {
        if (input[3] <= 0.8030266463756561) {
            set_output2(var117, 0.9993014079025285, 0.0006985920974714707);
        } else {
            if (input[4] <= 0.07810291275382042) {
                set_output2(var117, 1.0, 0.0);
            } else {
                if (input[0] <= 1.003672182559967) {
                    set_output2(var117, 0.0007528592106007198, 0.9992471407893992);
                } else {
                    set_output2(var117, 1.0, 0.0);
                }
            }
        }
    }
    add_vectors(var44, var117, 2, var43);
    double var118[2];
    if (input[4] <= 0.07958531379699707) {
        set_output2(var118, 1.0, 0.0);
    } else {
        if (input[3] <= 0.7910895943641663) {
            set_output2(var118, 1.0, 0.0);
        } else {
            if (input[0] <= 1.003672182559967) {
                set_output2(var118, 0.0006656681644200146, 0.99933433183558);
            } else {
                set_output2(var118, 1.0, 0.0);
            }
        }
    }
    add_vectors(var43, var118, 2, var42);
    double var119[2];
    if (input[4] <= 0.07957006990909576) {
        set_output2(var119, 1.0, 0.0);
    } else {
        if (input[1] <= 1.268185794353485) {
            if (input[2] <= 0.7192434370517731) {
                set_output2(var119, 0.0008400537634408799, 0.9991599462365591);
            } else {
                set_output2(var119, 1.0, 0.0);
            }
        } else {
            set_output2(var119, 1.0, 0.0);
        }
    }
    add_vectors(var42, var119, 2, var41);
    double var120[2];
    if (input[3] <= 0.8030266463756561) {
        set_output2(var120, 0.9991727141930269, 0.0008272858069731139);
    } else {
        if (input[4] <= 0.07811815664172173) {
            set_output2(var120, 1.0, 0.0);
        } else {
            if (input[0] <= 1.003672182559967) {
                set_output2(var120, 0.0005071514831531312, 0.9994928485168468);
            } else {
                set_output2(var120, 1.0, 0.0);
            }
        }
    }
    add_vectors(var41, var120, 2, var40);
    double var121[2];
    if (input[3] <= 0.7979046404361725) {
        set_output2(var121, 1.0, 0.0);
    } else {
        if (input[4] <= 0.07810291275382042) {
            set_output2(var121, 1.0, 0.0);
        } else {
            if (input[0] <= 1.003672182559967) {
                set_output2(var121, 0.00016818028927010028, 0.9998318197107299);
            } else {
                set_output2(var121, 1.0, 0.0);
            }
        }
    }
    add_vectors(var40, var121, 2, var39);
    double var122[2];
    if (input[4] <= 0.07957006990909576) {
        set_output2(var122, 1.0, 0.0);
    } else {
        if (input[3] <= 0.7910895943641663) {
            set_output2(var122, 1.0, 0.0);
        } else {
            if (input[0] <= 1.003672182559967) {
                set_output2(var122, 0.00033627574611181337, 0.9996637242538882);
            } else {
                set_output2(var122, 1.0, 0.0);
            }
        }
    }
    add_vectors(var39, var122, 2, var38);
    double var123[2];
    if (input[4] <= 0.07957006990909576) {
        set_output2(var123, 1.0, 0.0);
    } else {
        if (input[1] <= 1.2680765390396118) {
            if (input[5] <= 0.018225657753646374) {
                set_output2(var123, 1.0, 0.0);
            } else {
                if (input[3] <= 0.511388473212719) {
                    set_output2(var123, 1.0, 0.0);
                } else {
                    set_output2(var123, 0.0004998333888703828, 0.9995001666111296);
                }
            }
        } else {
            set_output2(var123, 1.0, 0.0);
        }
    }
    add_vectors(var38, var123, 2, var37);
    double var124[2];
    if (input[4] <= 0.07932857051491737) {
        set_output2(var124, 1.0, 0.0);
    } else {
        if (input[0] <= 0.9270281195640564) {
            if (input[3] <= 0.5765829384326935) {
                set_output2(var124, 1.0, 0.0);
            } else {
                set_output2(var124, 0.0009241367722423154, 0.9990758632277577);
            }
        } else {
            set_output2(var124, 1.0, 0.0);
        }
    }
    add_vectors(var37, var124, 2, var36);
    double var125[2];
    if (input[4] <= 0.07905081659555435) {
        set_output2(var125, 1.0, 0.0);
    } else {
        if (input[3] <= 0.7910895943641663) {
            set_output2(var125, 1.0, 0.0);
        } else {
            if (input[0] <= 1.09694504737854) {
                set_output2(var125, 0.0005845023380093976, 0.9994154976619907);
            } else {
                set_output2(var125, 1.0, 0.0);
            }
        }
    }
    add_vectors(var36, var125, 2, var35);
    double var126[2];
    if (input[4] <= 0.07957006990909576) {
        set_output2(var126, 1.0, 0.0);
    } else {
        if (input[0] <= 0.8913437128067017) {
            if (input[3] <= 0.5110464096069336) {
                set_output2(var126, 1.0, 0.0);
            } else {
                set_output2(var126, 0.00025079418157499266, 0.999749205818425);
            }
        } else {
            set_output2(var126, 1.0, 0.0);
        }
    }
    add_vectors(var35, var126, 2, var34);
    double var127[2];
    if (input[4] <= 0.07921133190393448) {
        set_output2(var127, 1.0, 0.0);
    } else {
        if (input[3] <= 0.7910895943641663) {
            set_output2(var127, 1.0, 0.0);
        } else {
            if (input[0] <= 1.09694504737854) {
                set_output2(var127, 0.0007565568258238122, 0.9992434431741762);
            } else {
                set_output2(var127, 1.0, 0.0);
            }
        }
    }
    add_vectors(var34, var127, 2, var33);
    double var128[2];
    if (input[3] <= 0.8029036819934845) {
        set_output2(var128, 0.9997193300994477, 0.00028066990055234596);
    } else {
        if (input[4] <= 0.07811815664172173) {
            set_output2(var128, 1.0, 0.0);
        } else {
            if (input[0] <= 1.003672182559967) {
                set_output2(var128, 0.0006688489742456398, 0.9993311510257543);
            } else {
                set_output2(var128, 1.0, 0.0);
            }
        }
    }
    add_vectors(var33, var128, 2, var32);
    double var129[2];
    if (input[4] <= 0.07957006990909576) {
        set_output2(var129, 1.0, 0.0);
    } else {
        if (input[0] <= 0.8913437128067017) {
            if (input[1] <= 1.4062390327453613) {
                if (input[3] <= 0.4184413366019726) {
                    set_output2(var129, 1.0, 0.0);
                } else {
                    set_output2(var129, 0.0, 1.0);
                }
            } else {
                set_output2(var129, 1.0, 0.0);
            }
        } else {
            set_output2(var129, 1.0, 0.0);
        }
    }
    add_vectors(var32, var129, 2, var31);
    double var130[2];
    if (input[0] <= 0.15017057210206985) {
        set_output2(var130, 1.0, 0.0);
    } else {
        if (input[6] <= 0.09852923825383186) {
            if (input[4] <= 0.07964450865983963) {
                set_output2(var130, 1.0, 0.0);
            } else {
                if (input[0] <= 1.0019291639328003) {
                    set_output2(var130, 0.015341949866703099, 0.9846580501332969);
                } else {
                    set_output2(var130, 1.0, 0.0);
                }
            }
        } else {
            if (input[3] <= 0.7910895943641663) {
                set_output2(var130, 1.0, 0.0);
            } else {
                if (input[5] <= 0.018795186653733253) {
                    set_output2(var130, 1.0, 0.0);
                } else {
                    set_output2(var130, 0.0, 1.0);
                }
            }
        }
    }
    add_vectors(var31, var130, 2, var30);
    double var131[2];
    if (input[0] <= 0.15017057210206985) {
        set_output2(var131, 1.0, 0.0);
    } else {
        if (input[6] <= 0.09829960763454437) {
            if (input[2] <= 0.5622232556343079) {
                if (input[1] <= 1.7895079851150513) {
                    set_output2(var131, 0.010799415280277645, 0.9892005847197224);
                } else {
                    set_output2(var131, 1.0, 0.0);
                }
            } else {
                if (input[8] <= 0.6550301909446716) {
                    set_output2(var131, 0.9934964771222362, 0.006503522877763835);
                } else {
                    set_output2(var131, 0.18226843954869598, 0.8177315604513039);
                }
            }
        } else {
            if (input[4] <= 0.07415657117962837) {
                set_output2(var131, 1.0, 0.0);
            } else {
                if (input[3] <= 0.7910895943641663) {
                    set_output2(var131, 1.0, 0.0);
                } else {
                    set_output2(var131, 0.0008599753457896505, 0.9991400246542103);
                }
            }
        }
    }
    add_vectors(var30, var131, 2, var29);
    double var132[2];
    if (input[4] <= 0.07957006990909576) {
        set_output2(var132, 1.0, 0.0);
    } else {
        if (input[3] <= 0.7910895943641663) {
            set_output2(var132, 1.0, 0.0);
        } else {
            if (input[0] <= 1.003672182559967) {
                set_output2(var132, 0.0003353735222604253, 0.9996646264777396);
            } else {
                set_output2(var132, 1.0, 0.0);
            }
        }
    }
    add_vectors(var29, var132, 2, var28);
    double var133[2];
    if (input[3] <= 0.8012422621250153) {
        set_output2(var133, 0.9998614087472307, 0.00013859125276926732);
    } else {
        if (input[4] <= 0.07810291275382042) {
            set_output2(var133, 1.0, 0.0);
        } else {
            if (input[1] <= 1.2757344841957092) {
                set_output2(var133, 0.0009239470969869661, 0.999076052903013);
            } else {
                set_output2(var133, 1.0, 0.0);
            }
        }
    }
    add_vectors(var28, var133, 2, var27);
    double var134[2];
    if (input[4] <= 0.07958531379699707) {
        set_output2(var134, 1.0, 0.0);
    } else {
        if (input[1] <= 1.267920970916748) {
            if (input[3] <= 0.511388473212719) {
                set_output2(var134, 1.0, 0.0);
            } else {
                if (input[2] <= 0.8012124598026276) {
                    set_output2(var134, 0.0, 1.0);
                } else {
                    set_output2(var134, 1.0, 0.0);
                }
            }
        } else {
            set_output2(var134, 1.0, 0.0);
        }
    }
    add_vectors(var27, var134, 2, var26);
    double var135[2];
    if (input[4] <= 0.07957006990909576) {
        set_output2(var135, 1.0, 0.0);
    } else {
        if (input[0] <= 0.8913437128067017) {
            if (input[3] <= 0.5765829384326935) {
                set_output2(var135, 1.0, 0.0);
            } else {
                set_output2(var135, 0.0005867068979967928, 0.9994132931020031);
            }
        } else {
            set_output2(var135, 1.0, 0.0);
        }
    }
    add_vectors(var26, var135, 2, var25);
    double var136[2];
    if (input[3] <= 0.8029036819934845) {
        set_output2(var136, 0.9995805579761482, 0.0004194420238517947);
    } else {
        if (input[4] <= 0.07811815664172173) {
            set_output2(var136, 1.0, 0.0);
        } else {
            if (input[1] <= 1.2708904147148132) {
                if (input[0] <= 1.096898466348648) {
                    set_output2(var136, 0.0, 1.0);
                } else {
                    set_output2(var136, 1.0, 0.0);
                }
            } else {
                set_output2(var136, 1.0, 0.0);
            }
        }
    }
    add_vectors(var25, var136, 2, var24);
    double var137[2];
    if (input[3] <= 0.7979046404361725) {
        set_output2(var137, 1.0, 0.0);
    } else {
        if (input[4] <= 0.07475796341896057) {
            set_output2(var137, 1.0, 0.0);
        } else {
            if (input[2] <= 0.7768287360668182) {
                set_output2(var137, 0.00033548603539378737, 0.9996645139646062);
            } else {
                set_output2(var137, 1.0, 0.0);
            }
        }
    }
    add_vectors(var24, var137, 2, var23);
    double var138[2];
    if (input[4] <= 0.07932857051491737) {
        set_output2(var138, 1.0, 0.0);
    } else {
        if (input[3] <= 0.7910895943641663) {
            set_output2(var138, 1.0, 0.0);
        } else {
            if (input[0] <= 1.0035676658153534) {
                set_output2(var138, 0.0003370123852051416, 0.9996629876147949);
            } else {
                set_output2(var138, 1.0, 0.0);
            }
        }
    }
    add_vectors(var23, var138, 2, var22);
    double var139[2];
    if (input[4] <= 0.07957006990909576) {
        set_output2(var139, 1.0, 0.0);
    } else {
        if (input[3] <= 0.7910895943641663) {
            set_output2(var139, 1.0, 0.0);
        } else {
            if (input[0] <= 1.003672182559967) {
                set_output2(var139, 0.00042286874154261265, 0.9995771312584575);
            } else {
                set_output2(var139, 1.0, 0.0);
            }
        }
    }
    add_vectors(var22, var139, 2, var21);
    double var140[2];
    if (input[4] <= 0.07957006990909576) {
        set_output2(var140, 1.0, 0.0);
    } else {
        if (input[3] <= 0.7910895943641663) {
            set_output2(var140, 1.0, 0.0);
        } else {
            if (input[0] <= 1.003625601530075) {
                set_output2(var140, 0.0005031868500502814, 0.9994968131499498);
            } else {
                set_output2(var140, 1.0, 0.0);
            }
        }
    }
    add_vectors(var21, var140, 2, var20);
    double var141[2];
    if (input[4] <= 0.07957006990909576) {
        set_output2(var141, 1.0, 0.0);
    } else {
        if (input[3] <= 0.7910895943641663) {
            set_output2(var141, 1.0, 0.0);
        } else {
            if (input[0] <= 1.003625601530075) {
                set_output2(var141, 0.00025012506253125076, 0.9997498749374687);
            } else {
                set_output2(var141, 1.0, 0.0);
            }
        }
    }
    add_vectors(var20, var141, 2, var19);
    double var142[2];
    if (input[4] <= 0.07957006990909576) {
        set_output2(var142, 1.0, 0.0);
    } else {
        if (input[3] <= 0.7915034294128418) {
            set_output2(var142, 1.0, 0.0);
        } else {
            if (input[0] <= 1.003672182559967) {
                set_output2(var142, 0.0005078290308929292, 0.999492170969107);
            } else {
                set_output2(var142, 1.0, 0.0);
            }
        }
    }
    add_vectors(var19, var142, 2, var18);
    double var143[2];
    if (input[4] <= 0.08053837716579437) {
        set_output2(var143, 0.9998662391925959, 0.00013376080740410025);
    } else {
        if (input[3] <= 0.7910895943641663) {
            set_output2(var143, 1.0, 0.0);
        } else {
            if (input[2] <= 0.7768287360668182) {
                set_output2(var143, 0.00008381224035296247, 0.9999161877596471);
            } else {
                set_output2(var143, 1.0, 0.0);
            }
        }
    }
    add_vectors(var18, var143, 2, var17);
    double var144[2];
    if (input[4] <= 0.07957006990909576) {
        set_output2(var144, 1.0, 0.0);
    } else {
        if (input[3] <= 0.7915034294128418) {
            set_output2(var144, 1.0, 0.0);
        } else {
            if (input[0] <= 1.003672182559967) {
                set_output2(var144, 0.0005857740585773715, 0.9994142259414226);
            } else {
                set_output2(var144, 1.0, 0.0);
            }
        }
    }
    add_vectors(var17, var144, 2, var16);
    double var145[2];
    if (input[4] <= 0.07957006990909576) {
        set_output2(var145, 1.0, 0.0);
    } else {
        if (input[0] <= 0.8913437128067017) {
            if (input[3] <= 0.5765829384326935) {
                set_output2(var145, 1.0, 0.0);
            } else {
                set_output2(var145, 0.0004166666666666679, 0.9995833333333334);
            }
        } else {
            set_output2(var145, 1.0, 0.0);
        }
    }
    add_vectors(var16, var145, 2, var15);
    double var146[2];
    if (input[4] <= 0.07957006990909576) {
        set_output2(var146, 1.0, 0.0);
    } else {
        if (input[3] <= 0.7910895943641663) {
            set_output2(var146, 1.0, 0.0);
        } else {
            if (input[0] <= 1.003625601530075) {
                set_output2(var146, 0.00016712626389238025, 0.9998328737361076);
            } else {
                set_output2(var146, 1.0, 0.0);
            }
        }
    }
    add_vectors(var15, var146, 2, var14);
    double var147[2];
    if (input[4] <= 0.07957006990909576) {
        set_output2(var147, 1.0, 0.0);
    } else {
        if (input[2] <= 0.7001699805259705) {
            if (input[3] <= 0.5687597692012787) {
                set_output2(var147, 1.0, 0.0);
            } else {
                set_output2(var147, 0.0007528860632424265, 0.9992471139367576);
            }
        } else {
            set_output2(var147, 1.0, 0.0);
        }
    }
    add_vectors(var14, var147, 2, var13);
    double var148[2];
    if (input[3] <= 0.8029036819934845) {
        set_output2(var148, 0.9995782209537875, 0.0004217790462125982);
    } else {
        if (input[4] <= 0.07811815664172173) {
            set_output2(var148, 1.0, 0.0);
        } else {
            if (input[0] <= 1.096898466348648) {
                set_output2(var148, 0.00041711025594916426, 0.9995828897440509);
            } else {
                set_output2(var148, 1.0, 0.0);
            }
        }
    }
    add_vectors(var13, var148, 2, var12);
    double var149[2];
    if (input[0] <= 0.15000467002391815) {
        set_output2(var149, 1.0, 0.0);
    } else {
        if (input[4] <= 0.07811815664172173) {
            set_output2(var149, 1.0, 0.0);
        } else {
            if (input[0] <= 0.9270281195640564) {
                if (input[3] <= 0.49276767671108246) {
                    set_output2(var149, 1.0, 0.0);
                } else {
                    set_output2(var149, 0.0004966887417218679, 0.9995033112582782);
                }
            } else {
                set_output2(var149, 1.0, 0.0);
            }
        }
    }
    add_vectors(var12, var149, 2, var11);
    double var150[2];
    if (input[3] <= 0.8030266463756561) {
        set_output2(var150, 0.9997201751382148, 0.0002798248617852153);
    } else {
        if (input[4] <= 0.07810291275382042) {
            set_output2(var150, 1.0, 0.0);
        } else {
            if (input[0] <= 1.096898466348648) {
                set_output2(var150, 0.0003349282581422744, 0.9996650717418577);
            } else {
                set_output2(var150, 1.0, 0.0);
            }
        }
    }
    add_vectors(var11, var150, 2, var10);
    double var151[2];
    if (input[4] <= 0.07957006990909576) {
        set_output2(var151, 1.0, 0.0);
    } else {
        if (input[3] <= 0.7910895943641663) {
            set_output2(var151, 1.0, 0.0);
        } else {
            if (input[2] <= 0.7768287360668182) {
                set_output2(var151, 0.0005860192549183655, 0.9994139807450816);
            } else {
                set_output2(var151, 1.0, 0.0);
            }
        }
    }
    add_vectors(var10, var151, 2, var9);
    double var152[2];
    if (input[4] <= 0.07958531379699707) {
        set_output2(var152, 1.0, 0.0);
    } else {
        if (input[3] <= 0.7910895943641663) {
            set_output2(var152, 1.0, 0.0);
        } else {
            if (input[2] <= 0.7768287360668182) {
                set_output2(var152, 0.00033658700774149544, 0.9996634129922585);
            } else {
                set_output2(var152, 1.0, 0.0);
            }
        }
    }
    add_vectors(var9, var152, 2, var8);
    double var153[2];
    if (input[4] <= 0.07957006990909576) {
        set_output2(var153, 1.0, 0.0);
    } else {
        if (input[1] <= 1.2709996700286865) {
            if (input[7] <= 0.30872292816638947) {
                set_output2(var153, 1.0, 0.0);
            } else {
                if (input[2] <= 0.7192434370517731) {
                    set_output2(var153, 0.00008373806732540482, 0.9999162619326747);
                } else {
                    set_output2(var153, 1.0, 0.0);
                }
            }
        } else {
            set_output2(var153, 1.0, 0.0);
        }
    }
    add_vectors(var8, var153, 2, var7);
    double var154[2];
    if (input[4] <= 0.07957006990909576) {
        set_output2(var154, 1.0, 0.0);
    } else {
        if (input[3] <= 0.7910895943641663) {
            set_output2(var154, 1.0, 0.0);
        } else {
            if (input[2] <= 0.7768287360668182) {
                if (input[1] <= 1.6128491759300232) {
                    set_output2(var154, 0.0, 1.0);
                } else {
                    set_output2(var154, 1.0, 0.0);
                }
            } else {
                set_output2(var154, 1.0, 0.0);
            }
        }
    }
    add_vectors(var7, var154, 2, var6);
    double var155[2];
    if (input[4] <= 0.07905081659555435) {
        set_output2(var155, 1.0, 0.0);
    } else {
        if (input[1] <= 1.268185794353485) {
            if (input[3] <= 0.5118023082613945) {
                set_output2(var155, 1.0, 0.0);
            } else {
                set_output2(var155, 0.0009178139340843027, 0.9990821860659157);
            }
        } else {
            set_output2(var155, 1.0, 0.0);
        }
    }
    add_vectors(var6, var155, 2, var5);
    double var156[2];
    if (input[4] <= 0.07957006990909576) {
        set_output2(var156, 1.0, 0.0);
    } else {
        if (input[1] <= 1.268185794353485) {
            if (input[2] <= 0.7192434370517731) {
                if (input[3] <= 0.4184413366019726) {
                    set_output2(var156, 1.0, 0.0);
                } else {
                    set_output2(var156, 0.0, 1.0);
                }
            } else {
                set_output2(var156, 1.0, 0.0);
            }
        } else {
            set_output2(var156, 1.0, 0.0);
        }
    }
    add_vectors(var5, var156, 2, var4);
    double var157[2];
    if (input[0] <= 0.15000467002391815) {
        set_output2(var157, 1.0, 0.0);
    } else {
        if (input[6] <= 0.09829960763454437) {
            if (input[2] <= 0.5374401211738586) {
                set_output2(var157, 0.022385584626051756, 0.9776144153739483);
            } else {
                if (input[5] <= 0.13877633959054947) {
                    set_output2(var157, 0.9903048990471307, 0.009695100952869315);
                } else {
                    set_output2(var157, 0.0, 1.0);
                }
            }
        } else {
            if (input[3] <= 0.7915034294128418) {
                set_output2(var157, 1.0, 0.0);
            } else {
                if (input[4] <= 0.07318032905459404) {
                    set_output2(var157, 1.0, 0.0);
                } else {
                    set_output2(var157, 0.001027464937674472, 0.9989725350623255);
                }
            }
        }
    }
    add_vectors(var4, var157, 2, var3);
    double var158[2];
    if (input[4] <= 0.07932857051491737) {
        set_output2(var158, 1.0, 0.0);
    } else {
        if (input[1] <= 1.268185794353485) {
            if (input[3] <= 0.511388473212719) {
                set_output2(var158, 1.0, 0.0);
            } else {
                set_output2(var158, 0.0010026737967914884, 0.9989973262032085);
            }
        } else {
            set_output2(var158, 1.0, 0.0);
        }
    }
    add_vectors(var3, var158, 2, var2);
    double var159[2];
    if (input[4] <= 0.07932857051491737) {
        set_output2(var159, 1.0, 0.0);
    } else {
        if (input[3] <= 0.7910895943641663) {
            set_output2(var159, 1.0, 0.0);
        } else {
            if (input[2] <= 0.7768287360668182) {
                set_output2(var159, 0.0005038629492778065, 0.9994961370507222);
            } else {
                set_output2(var159, 1.0, 0.0);
            }
        }
    }
    add_vectors(var2, var159, 2, var1);
    mul_vector_number(var1, 0.0125, 2, var0);
    memcpy(output, var0, 2 * sizeof(double));
}

