#pragma once
// Auto-generated by m2cgen from scikit-learn RandomForest
#define ARC_MODEL_FEATURE_VERSION 2
#define ARC_THRESHOLD 0.6100

// Input Feature Order:
// [0] cycle_nmse
// [1] zcv
// [2] zc_dwell_ratio
// [3] cycle_rms_drop_ratio
// [4] peak_fluct_cv
// [5] midband_residual_rms
// [6] hf_band_energy_ratio
// [7] spec_entropy
// [8] neg_dip_event_ratio
// [9] pre_dip_spike_ratio

#include <string.h>
#include <string.h>
static inline void add_vectors(double *v1, double *v2, int size, double *result) {
    for(int i = 0; i < size; ++i)
        result[i] = v1[i] + v2[i];
}
static inline void mul_vector_number(double *v1, double num, int size, double *result) {
    for(int i = 0; i < size; ++i)
        result[i] = v1[i] * num;
}
static inline void set_output2(double *dst, double a, double b) {
    dst[0] = a;
    dst[1] = b;
}
static inline void arc_rf_predict(double * input, double * output) {
    double var0[2];
    double var1[2];
    double var2[2];
    double var3[2];
    double var4[2];
    double var5[2];
    double var6[2];
    double var7[2];
    double var8[2];
    double var9[2];
    double var10[2];
    double var11[2];
    double var12[2];
    double var13[2];
    double var14[2];
    double var15[2];
    double var16[2];
    double var17[2];
    double var18[2];
    double var19[2];
    double var20[2];
    double var21[2];
    double var22[2];
    double var23[2];
    double var24[2];
    double var25[2];
    double var26[2];
    double var27[2];
    double var28[2];
    double var29[2];
    double var30[2];
    double var31[2];
    double var32[2];
    double var33[2];
    double var34[2];
    double var35[2];
    double var36[2];
    double var37[2];
    double var38[2];
    double var39[2];
    double var40[2];
    if (input[1] <= 0.10328653082251549) {
        if (input[8] <= 0.1246187649667263) {
            if (input[5] <= 0.08992069587111473) {
                if (input[2] <= 0.15617519617080688) {
                    set_output2(var40, 0.9989579356809013, 0.0010420643190986523);
                } else {
                    set_output2(var40, 0.0, 1.0);
                }
            } else {
                set_output2(var40, 0.06543291473892926, 0.9345670852610707);
            }
        } else {
            if (input[0] <= 0.0454917810857296) {
                set_output2(var40, 0.49499999999999994, 0.505);
            } else {
                set_output2(var40, 0.010185971139748479, 0.9898140288602515);
            }
        }
    } else {
        if (input[8] <= 0.0898721031844616) {
            if (input[5] <= 0.051133835688233376) {
                if (input[3] <= 0.10705305263400078) {
                    set_output2(var40, 0.9592248687928946, 0.04077513120710538);
                } else {
                    set_output2(var40, 0.0, 1.0);
                }
            } else {
                set_output2(var40, 0.01961172741679873, 0.9803882725832013);
            }
        } else {
            set_output2(var40, 0.0006859423392712449, 0.9993140576607288);
        }
    }
    double var41[2];
    if (input[3] <= 0.09945501759648323) {
        if (input[8] <= 0.13073370605707169) {
            if (input[9] <= 0.09944100305438042) {
                if (input[5] <= 0.09862225502729416) {
                    set_output2(var41, 0.9989638716813655, 0.0010361283186345546);
                } else {
                    set_output2(var41, 0.07392437577909568, 0.9260756242209043);
                }
            } else {
                set_output2(var41, 0.03838082723724725, 0.9616191727627528);
            }
        } else {
            if (input[5] <= 0.035146208480000496) {
                if (input[2] <= 0.08452756702899933) {
                    if (input[1] <= 0.1489248238503933) {
                        set_output2(var41, 1.0, 0.0);
                    } else {
                        set_output2(var41, 0.0, 1.0);
                    }
                } else {
                    set_output2(var41, 0.0, 1.0);
                }
            } else {
                set_output2(var41, 0.0, 1.0);
            }
        }
    } else {
        if (input[8] <= 0.07149341329932213) {
            if (input[0] <= 0.13445129990577698) {
                if (input[6] <= 0.19088667631149292) {
                    set_output2(var41, 0.9451823231103598, 0.054817676889640184);
                } else {
                    set_output2(var41, 0.0, 1.0);
                }
            } else {
                set_output2(var41, 0.0, 1.0);
            }
        } else {
            set_output2(var41, 0.0006335527189026716, 0.9993664472810974);
        }
    }
    add_vectors(var40, var41, 2, var39);
    double var42[2];
    if (input[8] <= 0.12339957058429718) {
        if (input[9] <= 0.0998707264661789) {
            if (input[0] <= 0.14014939218759537) {
                if (input[2] <= 0.1642260029911995) {
                    set_output2(var42, 1.0, 0.0);
                } else {
                    set_output2(var42, 0.0, 1.0);
                }
            } else {
                set_output2(var42, 0.0, 1.0);
            }
        } else {
            set_output2(var42, 0.02837769113409048, 0.9716223088659095);
        }
    } else {
        if (input[2] <= 0.07432404533028603) {
            if (input[9] <= 0.07129894196987152) {
                if (input[8] <= 0.16042568534612656) {
                    set_output2(var42, 1.0, 0.0);
                } else {
                    set_output2(var42, 0.07004602785581923, 0.9299539721441809);
                }
            } else {
                set_output2(var42, 0.0, 1.0);
            }
        } else {
            set_output2(var42, 0.0, 1.0);
        }
    }
    add_vectors(var39, var42, 2, var38);
    double var43[2];
    if (input[0] <= 0.12035641819238663) {
        if (input[9] <= 0.11036918684840202) {
            if (input[2] <= 0.15022487193346024) {
                if (input[5] <= 0.09381444379687309) {
                    if (input[8] <= 0.25554415583610535) {
                        set_output2(var43, 1.0, 0.0);
                    } else {
                        set_output2(var43, 0.0, 1.0);
                    }
                } else {
                    set_output2(var43, 0.19729380161177992, 0.8027061983882201);
                }
            } else {
                set_output2(var43, 0.0, 1.0);
            }
        } else {
            set_output2(var43, 0.003344216512300923, 0.9966557834876991);
        }
    } else {
        set_output2(var43, 0.004775828958851845, 0.9952241710411482);
    }
    add_vectors(var38, var43, 2, var37);
    double var44[2];
    if (input[9] <= 0.09865714982151985) {
        if (input[3] <= 0.10793893411755562) {
            if (input[5] <= 0.09119129180908203) {
                if (input[8] <= 0.1439053788781166) {
                    if (input[0] <= 0.1624719351530075) {
                        set_output2(var44, 1.0, 0.0);
                    } else {
                        set_output2(var44, 0.0, 1.0);
                    }
                } else {
                    set_output2(var44, 0.09576138147566719, 0.9042386185243328);
                }
            } else {
                set_output2(var44, 0.0, 1.0);
            }
        } else {
            set_output2(var44, 0.02152181582970722, 0.9784781841702928);
        }
    } else {
        set_output2(var44, 0.0023594940625846095, 0.9976405059374154);
    }
    add_vectors(var37, var44, 2, var36);
    double var45[2];
    if (input[8] <= 0.1235240176320076) {
        if (input[9] <= 0.10407570376992226) {
            if (input[3] <= 0.17681533843278885) {
                if (input[2] <= 0.17294561862945557) {
                    if (input[6] <= 0.3405145853757858) {
                        if (input[1] <= 0.15970198810100555) {
                            set_output2(var45, 0.9995058573976763, 0.0004941426023236803);
                        } else {
                            set_output2(var45, 0.0, 1.0);
                        }
                    } else {
                        set_output2(var45, 0.0, 1.0);
                    }
                } else {
                    set_output2(var45, 0.0, 1.0);
                }
            } else {
                set_output2(var45, 0.0, 1.0);
            }
        } else {
            set_output2(var45, 0.0059329160048584425, 0.9940670839951415);
        }
    } else {
        set_output2(var45, 0.00452299336686995, 0.9954770066331301);
    }
    add_vectors(var36, var45, 2, var35);
    double var46[2];
    if (input[3] <= 0.09469049423933029) {
        if (input[0] <= 0.12547452002763748) {
            if (input[8] <= 0.17543292045593262) {
                set_output2(var46, 0.9980053948012483, 0.0019946051987516345);
            } else {
                set_output2(var46, 0.0, 1.0);
            }
        } else {
            set_output2(var46, 0.012660524565046434, 0.9873394754349536);
        }
    } else {
        if (input[8] <= 0.09212770685553551) {
            if (input[3] <= 0.11369077488780022) {
                if (input[9] <= 0.08319173380732536) {
                    set_output2(var46, 1.0, 0.0);
                } else {
                    set_output2(var46, 0.0, 1.0);
                }
            } else {
                set_output2(var46, 0.022465849926801625, 0.9775341500731984);
            }
        } else {
            set_output2(var46, 0.0013671927333136964, 0.9986328072666864);
        }
    }
    add_vectors(var35, var46, 2, var34);
    double var47[2];
    if (input[0] <= 0.1166360154747963) {
        if (input[9] <= 0.10025211796164513) {
            if (input[8] <= 0.13852764666080475) {
                if (input[4] <= 0.12974658608436584) {
                    set_output2(var47, 1.0, 0.0);
                } else {
                    set_output2(var47, 0.0, 1.0);
                }
            } else {
                if (input[7] <= 0.5265457332134247) {
                    set_output2(var47, 0.7954820492133925, 0.2045179507866075);
                } else {
                    set_output2(var47, 0.0, 1.0);
                }
            }
        } else {
            set_output2(var47, 0.01801637187545678, 0.9819836281245432);
        }
    } else {
        if (input[0] <= 0.13764116913080215) {
            if (input[8] <= 0.09518758207559586) {
                if (input[9] <= 0.18168149143457413) {
                    set_output2(var47, 1.0, 0.0);
                } else {
                    set_output2(var47, 0.0, 1.0);
                }
            } else {
                set_output2(var47, 0.0, 1.0);
            }
        } else {
            set_output2(var47, 0.0, 1.0);
        }
    }
    add_vectors(var34, var47, 2, var33);
    double var48[2];
    if (input[8] <= 0.12339957058429718) {
        if (input[0] <= 0.13882482796907425) {
            if (input[3] <= 0.11525356024503708) {
                if (input[1] <= 0.16866866499185562) {
                    set_output2(var48, 0.997990843931195, 0.0020091560688050756);
                } else {
                    set_output2(var48, 0.0, 1.0);
                }
            } else {
                if (input[9] <= 0.012161458376795053) {
                    set_output2(var48, 1.0, 0.0);
                } else {
                    set_output2(var48, 0.0, 1.0);
                }
            }
        } else {
            set_output2(var48, 0.0, 1.0);
        }
    } else {
        if (input[1] <= 0.09731943532824516) {
            if (input[4] <= 0.042684078216552734) {
                if (input[3] <= 0.06623283587396145) {
                    set_output2(var48, 0.9171238570241065, 0.0828761429758936);
                } else {
                    set_output2(var48, 0.0, 1.0);
                }
            } else {
                if (input[8] <= 0.13358647376298904) {
                    if (input[5] <= 0.08862545154988766) {
                        set_output2(var48, 1.0, 0.0);
                    } else {
                        set_output2(var48, 0.0, 1.0);
                    }
                } else {
                    set_output2(var48, 0.0, 1.0);
                }
            }
        } else {
            set_output2(var48, 0.0, 1.0);
        }
    }
    add_vectors(var33, var48, 2, var32);
    double var49[2];
    if (input[1] <= 0.10889927297830582) {
        if (input[0] <= 0.12560392171144485) {
            if (input[0] <= 0.08715024217963219) {
                if (input[5] <= 0.09236285835504532) {
                    if (input[9] <= 0.19270336255431175) {
                        set_output2(var49, 1.0, 0.0);
                    } else {
                        set_output2(var49, 0.0, 1.0);
                    }
                } else {
                    set_output2(var49, 0.06356305909033641, 0.9364369409096636);
                }
            } else {
                if (input[8] <= 0.13464264199137688) {
                    set_output2(var49, 0.993272050836411, 0.006727949163588968);
                } else {
                    set_output2(var49, 0.0, 1.0);
                }
            }
        } else {
            if (input[5] <= 0.02783055603504181) {
                if (input[9] <= 0.024090849794447422) {
                    set_output2(var49, 0.8906543087277943, 0.10934569127220567);
                } else {
                    set_output2(var49, 0.019204050170343163, 0.9807959498296569);
                }
            } else {
                set_output2(var49, 0.0, 1.0);
            }
        }
    } else {
        if (input[9] <= 0.05929337441921234) {
            if (input[0] <= 0.07616405561566353) {
                if (input[2] <= 0.09238068759441376) {
                    set_output2(var49, 0.9468589967021477, 0.053141003297852374);
                } else {
                    set_output2(var49, 0.0, 1.0);
                }
            } else {
                set_output2(var49, 0.010387497941031143, 0.9896125020589689);
            }
        } else {
            set_output2(var49, 0.0014809259236156047, 0.9985190740763844);
        }
    }
    add_vectors(var32, var49, 2, var31);
    double var50[2];
    if (input[0] <= 0.11845816671848297) {
        if (input[5] <= 0.07744541391730309) {
            if (input[9] <= 0.11179910972714424) {
                if (input[1] <= 0.16972000896930695) {
                    set_output2(var50, 0.9979804343792209, 0.0020195656207790437);
                } else {
                    set_output2(var50, 0.0, 1.0);
                }
            } else {
                set_output2(var50, 0.0, 1.0);
            }
        } else {
            if (input[8] <= 0.06377519108355045) {
                set_output2(var50, 0.8834900272383798, 0.11650997276162024);
            } else {
                set_output2(var50, 0.0044537954709041585, 0.9955462045290958);
            }
        }
    } else {
        if (input[3] <= 0.0665876567363739) {
            if (input[0] <= 0.13502423465251923) {
                if (input[8] <= 0.1153409294784069) {
                    set_output2(var50, 0.9450187969924811, 0.0549812030075188);
                } else {
                    set_output2(var50, 0.0, 1.0);
                }
            } else {
                set_output2(var50, 0.0, 1.0);
            }
        } else {
            set_output2(var50, 0.0006882595111406737, 0.9993117404888594);
        }
    }
    add_vectors(var31, var50, 2, var30);
    double var51[2];
    if (input[4] <= 0.08245954662561417) {
        if (input[8] <= 0.13669385761022568) {
            if (input[3] <= 0.10812636837363243) {
                if (input[1] <= 0.16833826154470444) {
                    if (input[5] <= 0.12238334491848946) {
                        set_output2(var51, 0.9994905563916271, 0.0005094436083728838);
                    } else {
                        set_output2(var51, 0.0, 1.0);
                    }
                } else {
                    set_output2(var51, 0.0, 1.0);
                }
            } else {
                set_output2(var51, 0.03993788758444024, 0.9600621124155597);
            }
        } else {
            set_output2(var51, 0.010504955904159863, 0.9894950440958401);
        }
    } else {
        if (input[4] <= 0.10277236998081207) {
            if (input[1] <= 0.05995854735374451) {
                if (input[5] <= 0.05101793073117733) {
                    set_output2(var51, 0.9520936362647062, 0.047906363735293764);
                } else {
                    set_output2(var51, 0.0, 1.0);
                }
            } else {
                if (input[8] <= 0.06805901974439621) {
                    if (input[1] <= 0.1273007169365883) {
                        set_output2(var51, 1.0, 0.0);
                    } else {
                        set_output2(var51, 0.0, 1.0);
                    }
                } else {
                    set_output2(var51, 0.0, 1.0);
                }
            }
        } else {
            if (input[2] <= 0.04476154409348965) {
                if (input[9] <= 0.011699943337589502) {
                    if (input[3] <= 0.07510770112276077) {
                        set_output2(var51, 1.0, 0.0);
                    } else {
                        set_output2(var51, 0.0, 1.0);
                    }
                } else {
                    set_output2(var51, 0.0, 1.0);
                }
            } else {
                set_output2(var51, 0.0, 1.0);
            }
        }
    }
    add_vectors(var30, var51, 2, var29);
    double var52[2];
    if (input[0] <= 0.11277221515774727) {
        if (input[9] <= 0.10937808826565742) {
            if (input[8] <= 0.14203226566314697) {
                if (input[1] <= 0.16866866499185562) {
                    if (input[4] <= 0.11198868229985237) {
                        set_output2(var52, 1.0, 0.0);
                    } else {
                        set_output2(var52, 0.24275810844268386, 0.7572418915573162);
                    }
                } else {
                    set_output2(var52, 0.0, 1.0);
                }
            } else {
                set_output2(var52, 0.028318507393715348, 0.9716814926062847);
            }
        } else {
            set_output2(var52, 0.0, 1.0);
        }
    } else {
        if (input[1] <= 0.058144696056842804) {
            if (input[0] <= 0.1271747127175331) {
                if (input[8] <= 0.15918374806642532) {
                    set_output2(var52, 1.0, 0.0);
                } else {
                    set_output2(var52, 0.0, 1.0);
                }
            } else {
                set_output2(var52, 0.012283606615566761, 0.9877163933844333);
            }
        } else {
            set_output2(var52, 0.0013275317285837234, 0.9986724682714163);
        }
    }
    add_vectors(var29, var52, 2, var28);
    double var53[2];
    if (input[0] <= 0.10428427904844284) {
        if (input[9] <= 0.10937808826565742) {
            if (input[8] <= 0.14203226566314697) {
                if (input[2] <= 0.1642260029911995) {
                    set_output2(var53, 0.9989407860030514, 0.0010592139969486628);
                } else {
                    set_output2(var53, 0.0, 1.0);
                }
            } else {
                set_output2(var53, 0.04071766446477319, 0.9592823355352268);
            }
        } else {
            set_output2(var53, 0.009367209971236828, 0.9906327900287631);
        }
    } else {
        if (input[8] <= 0.09042618423700333) {
            if (input[0] <= 0.1391584575176239) {
                if (input[9] <= 0.18168149143457413) {
                    set_output2(var53, 0.9687876615154613, 0.03121233848453877);
                } else {
                    set_output2(var53, 0.0, 1.0);
                }
            } else {
                set_output2(var53, 0.0, 1.0);
            }
        } else {
            set_output2(var53, 0.0012028819919824383, 0.9987971180080176);
        }
    }
    add_vectors(var28, var53, 2, var27);
    double var54[2];
    if (input[1] <= 0.10897014290094376) {
        if (input[9] <= 0.10904313251376152) {
            if (input[4] <= 0.1033453643321991) {
                if (input[8] <= 0.1786959245800972) {
                    if (input[0] <= 0.2416713535785675) {
                        set_output2(var54, 1.0, 0.0);
                    } else {
                        set_output2(var54, 0.0, 1.0);
                    }
                } else {
                    set_output2(var54, 0.0, 1.0);
                }
            } else {
                set_output2(var54, 0.01705091050650981, 0.9829490894934902);
            }
        } else {
            set_output2(var54, 0.002807788300454704, 0.9971922116995453);
        }
    } else {
        if (input[1] <= 0.13138365000486374) {
            if (input[4] <= 0.07269137352705002) {
                if (input[0] <= 0.11536538600921631) {
                    set_output2(var54, 0.9337112240064035, 0.06628877599359656);
                } else {
                    set_output2(var54, 0.0, 1.0);
                }
            } else {
                set_output2(var54, 0.0, 1.0);
            }
        } else {
            set_output2(var54, 0.00135017802004715, 0.9986498219799529);
        }
    }
    add_vectors(var27, var54, 2, var26);
    double var55[2];
    if (input[8] <= 0.12412488460540771) {
        if (input[0] <= 0.12325871363282204) {
            if (input[9] <= 0.10845974087715149) {
                if (input[4] <= 0.14707347005605698) {
                    set_output2(var55, 0.9989673400522523, 0.0010326599477477186);
                } else {
                    set_output2(var55, 0.0, 1.0);
                }
            } else {
                set_output2(var55, 0.0, 1.0);
            }
        } else {
            if (input[2] <= 0.007264822255820036) {
                set_output2(var55, 0.8261275008477451, 0.173872499152255);
            } else {
                set_output2(var55, 0.016784168283749217, 0.9832158317162508);
            }
        }
    } else {
        set_output2(var55, 0.0037866792047390172, 0.996213320795261);
    }
    add_vectors(var26, var55, 2, var25);
    double var56[2];
    if (input[0] <= 0.11286244541406631) {
        if (input[3] <= 0.10614725202322006) {
            if (input[9] <= 0.11128753423690796) {
                if (input[5] <= 0.09862225502729416) {
                    set_output2(var56, 0.9994938370206077, 0.0005061629793922988);
                } else {
                    set_output2(var56, 0.1440860215053763, 0.8559139784946236);
                }
            } else {
                set_output2(var56, 0.02348405187521905, 0.976515948124781);
            }
        } else {
            if (input[8] <= 0.06741613894701004) {
                if (input[4] <= 0.09615587256848812) {
                    set_output2(var56, 1.0, 0.0);
                } else {
                    set_output2(var56, 0.0, 1.0);
                }
            } else {
                set_output2(var56, 0.0, 1.0);
            }
        }
    } else {
        if (input[0] <= 0.12321760132908821) {
            if (input[8] <= 0.09849413856863976) {
                if (input[2] <= 0.16687234863638878) {
                    set_output2(var56, 1.0, 0.0);
                } else {
                    set_output2(var56, 0.0, 1.0);
                }
            } else {
                set_output2(var56, 0.0, 1.0);
            }
        } else {
            set_output2(var56, 0.0035773824002277776, 0.9964226175997722);
        }
    }
    add_vectors(var25, var56, 2, var24);
    double var57[2];
    if (input[1] <= 0.10849321261048317) {
        if (input[9] <= 0.10860471054911613) {
            if (input[0] <= 0.13669975847005844) {
                if (input[4] <= 0.14081713557243347) {
                    if (input[8] <= 0.27996035665273666) {
                        set_output2(var57, 0.9995083051407931, 0.0004916948592068811);
                    } else {
                        set_output2(var57, 0.0, 1.0);
                    }
                } else {
                    set_output2(var57, 0.0, 1.0);
                }
            } else {
                set_output2(var57, 0.0, 1.0);
            }
        } else {
            set_output2(var57, 0.0, 1.0);
        }
    } else {
        if (input[5] <= 0.04108956642448902) {
            if (input[0] <= 0.07604565471410751) {
                if (input[8] <= 0.13279536366462708) {
                    set_output2(var57, 1.0, 0.0);
                } else {
                    set_output2(var57, 0.0, 1.0);
                }
            } else {
                set_output2(var57, 0.0, 1.0);
            }
        } else {
            set_output2(var57, 0.002349800886489972, 0.99765019911351);
        }
    }
    add_vectors(var24, var57, 2, var23);
    double var58[2];
    if (input[4] <= 0.07871978357434273) {
        if (input[1] <= 0.11160993948578835) {
            if (input[0] <= 0.13870444893836975) {
                if (input[0] <= 0.12462874129414558) {
                    if (input[6] <= 0.3641414940357208) {
                        if (input[8] <= 0.20501241087913513) {
                            set_output2(var58, 1.0, 0.0);
                        } else {
                            set_output2(var58, 0.0, 1.0);
                        }
                    } else {
                        set_output2(var58, 0.0, 1.0);
                    }
                } else {
                    if (input[1] <= 0.08391743153333664) {
                        set_output2(var58, 1.0, 0.0);
                    } else {
                        set_output2(var58, 0.0, 1.0);
                    }
                }
            } else {
                set_output2(var58, 0.0, 1.0);
            }
        } else {
            if (input[3] <= 0.05831879749894142) {
                if (input[1] <= 0.13756098598241806) {
                    if (input[3] <= 0.00028814171673730016) {
                        set_output2(var58, 0.17101717750084205, 0.828982822499158);
                    } else {
                        set_output2(var58, 1.0, 0.0);
                    }
                } else {
                    set_output2(var58, 0.022905928925079228, 0.9770940710749207);
                }
            } else {
                set_output2(var58, 0.0, 1.0);
            }
        }
    } else {
        if (input[8] <= 0.08793676644563675) {
            if (input[0] <= 0.10691504925489426) {
                if (input[4] <= 0.1037910096347332) {
                    set_output2(var58, 1.0, 0.0);
                } else {
                    set_output2(var58, 0.17101717750084203, 0.828982822499158);
                }
            } else {
                set_output2(var58, 0.010415758514408216, 0.9895842414855919);
            }
        } else {
            if (input[4] <= 0.08481856435537338) {
                if (input[0] <= 0.0539272241294384) {
                    if (input[5] <= 0.04101188667118549) {
                        set_output2(var58, 1.0, 0.0);
                    } else {
                        set_output2(var58, 0.0, 1.0);
                    }
                } else {
                    set_output2(var58, 0.0, 1.0);
                }
            } else {
                set_output2(var58, 0.0, 1.0);
            }
        }
    }
    add_vectors(var23, var58, 2, var22);
    double var59[2];
    if (input[8] <= 0.10624430328607559) {
        if (input[4] <= 0.10333641245961189) {
            if (input[9] <= 0.1103057935833931) {
                if (input[2] <= 0.16136828809976578) {
                    if (input[5] <= 0.11317537352442741) {
                        if (input[1] <= 0.17662087827920914) {
                            set_output2(var59, 1.0, 0.0);
                        } else {
                            set_output2(var59, 0.0, 1.0);
                        }
                    } else {
                        set_output2(var59, 0.0, 1.0);
                    }
                } else {
                    set_output2(var59, 0.0, 1.0);
                }
            } else {
                set_output2(var59, 0.0, 1.0);
            }
        } else {
            if (input[3] <= 0.0519886240363121) {
                if (input[2] <= 0.05551186203956604) {
                    set_output2(var59, 1.0, 0.0);
                } else {
                    set_output2(var59, 0.0, 1.0);
                }
            } else {
                set_output2(var59, 0.0, 1.0);
            }
        }
    } else {
        if (input[2] <= 0.08151335641741753) {
            if (input[9] <= 0.06802861019968987) {
                if (input[0] <= 0.1256343461573124) {
                    set_output2(var59, 0.9739507569635256, 0.026049243036474327);
                } else {
                    set_output2(var59, 0.0, 1.0);
                }
            } else {
                set_output2(var59, 0.0, 1.0);
            }
        } else {
            set_output2(var59, 0.0021067229547146343, 0.9978932770452854);
        }
    }
    add_vectors(var22, var59, 2, var21);
    double var60[2];
    if (input[9] <= 0.0998707264661789) {
        if (input[3] <= 0.10793893411755562) {
            if (input[5] <= 0.08979031443595886) {
                if (input[8] <= 0.14012110233306885) {
                    set_output2(var60, 0.998502119421865, 0.00149788057813515);
                } else {
                    set_output2(var60, 0.05062113363174569, 0.9493788663682542);
                }
            } else {
                set_output2(var60, 0.0, 1.0);
            }
        } else {
            set_output2(var60, 0.017109141534162153, 0.9828908584658378);
        }
    } else {
        set_output2(var60, 0.004321267252792206, 0.9956787327472079);
    }
    add_vectors(var21, var60, 2, var20);
    double var61[2];
    if (input[8] <= 0.12412488460540771) {
        if (input[0] <= 0.1353471875190735) {
            if (input[6] <= 0.2997284382581711) {
                if (input[5] <= 0.09786032885313034) {
                    set_output2(var61, 0.9970144979955993, 0.002985502004400678);
                } else {
                    set_output2(var61, 0.0, 1.0);
                }
            } else {
                set_output2(var61, 0.10172309552599756, 0.8982769044740024);
            }
        } else {
            set_output2(var61, 0.0, 1.0);
        }
    } else {
        if (input[7] <= 0.5274458825588226) {
            if (input[8] <= 0.15330670773983002) {
                if (input[0] <= 0.11176929250359535) {
                    set_output2(var61, 1.0, 0.0);
                } else {
                    set_output2(var61, 0.0, 1.0);
                }
            } else {
                set_output2(var61, 0.0, 1.0);
            }
        } else {
            set_output2(var61, 0.0, 1.0);
        }
    }
    add_vectors(var20, var61, 2, var19);
    double var62[2];
    if (input[4] <= 0.07322199270129204) {
        if (input[8] <= 0.14125700294971466) {
            if (input[1] <= 0.14272268116474152) {
                if (input[9] <= 0.17018704116344452) {
                    set_output2(var62, 1.0, 0.0);
                } else {
                    set_output2(var62, 0.0, 1.0);
                }
            } else {
                set_output2(var62, 0.026504391337207774, 0.9734956086627923);
            }
        } else {
            set_output2(var62, 0.0, 1.0);
        }
    } else {
        if (input[8] <= 0.0948333702981472) {
            if (input[4] <= 0.1033453643321991) {
                if (input[7] <= 0.6711552143096924) {
                    if (input[1] <= 0.1759355068206787) {
                        set_output2(var62, 0.9772393113907637, 0.022760688609236263);
                    } else {
                        set_output2(var62, 0.0, 1.0);
                    }
                } else {
                    set_output2(var62, 0.2927039861850626, 0.7072960138149373);
                }
            } else {
                set_output2(var62, 0.020075604291481197, 0.9799243957085189);
            }
        } else {
            set_output2(var62, 0.003385048801952371, 0.9966149511980475);
        }
    }
    add_vectors(var19, var62, 2, var18);
    double var63[2];
    if (input[9] <= 0.09912186861038208) {
        if (input[0] <= 0.12309182435274124) {
            if (input[8] <= 0.17402048408985138) {
                if (input[6] <= 0.30616678297519684) {
                    set_output2(var63, 0.9990053268818707, 0.0009946731181292323);
                } else {
                    set_output2(var63, 0.38017046878917027, 0.6198295312108298);
                }
            } else {
                set_output2(var63, 0.0, 1.0);
            }
        } else {
            set_output2(var63, 0.00982717393417444, 0.9901728260658256);
        }
    } else {
        if (input[9] <= 0.10681122913956642) {
            if (input[5] <= 0.028486113529652357) {
                set_output2(var63, 1.0, 0.0);
            } else {
                set_output2(var63, 0.0, 1.0);
            }
        } else {
            set_output2(var63, 0.001246606050293338, 0.9987533939497066);
        }
    }
    add_vectors(var18, var63, 2, var17);
    double var64[2];
    if (input[9] <= 0.07823820412158966) {
        if (input[8] <= 0.1412089467048645) {
            if (input[0] <= 0.1393844336271286) {
                if (input[2] <= 0.18330733478069305) {
                    set_output2(var64, 0.9994919282143736, 0.0005080717856264884);
                } else {
                    set_output2(var64, 0.0, 1.0);
                }
            } else {
                set_output2(var64, 0.0, 1.0);
            }
        } else {
            set_output2(var64, 0.016451233842538167, 0.9835487661574618);
        }
    } else {
        if (input[9] <= 0.1038890853524208) {
            if (input[8] <= 0.08638223633170128) {
                if (input[3] <= 0.11742965131998062) {
                    set_output2(var64, 0.9776254059906172, 0.0223745940093829);
                } else {
                    set_output2(var64, 0.0, 1.0);
                }
            } else {
                set_output2(var64, 0.0, 1.0);
            }
        } else {
            set_output2(var64, 0.0006084546218406333, 0.9993915453781593);
        }
    }
    add_vectors(var17, var64, 2, var16);
    double var65[2];
    if (input[4] <= 0.08618051558732986) {
        if (input[9] <= 0.10700814053416252) {
            if (input[2] <= 0.13544559478759766) {
                if (input[8] <= 0.17808349430561066) {
                    if (input[0] <= 0.1400689035654068) {
                        set_output2(var65, 1.0, 0.0);
                    } else {
                        set_output2(var65, 0.0, 1.0);
                    }
                } else {
                    set_output2(var65, 0.0, 1.0);
                }
            } else {
                set_output2(var65, 0.05154531714181478, 0.9484546828581851);
            }
        } else {
            set_output2(var65, 0.0, 1.0);
        }
    } else {
        if (input[3] <= 0.08378588408231735) {
            if (input[4] <= 0.10332122817635536) {
                if (input[8] <= 0.09832269325852394) {
                    set_output2(var65, 0.8776572143116453, 0.12234278568835463);
                } else {
                    set_output2(var65, 0.0, 1.0);
                }
            } else {
                set_output2(var65, 0.00416310620761651, 0.9958368937923835);
            }
        } else {
            set_output2(var65, 0.0, 1.0);
        }
    }
    add_vectors(var16, var65, 2, var15);
    double var66[2];
    if (input[3] <= 0.09001399204134941) {
        if (input[0] <= 0.12547452002763748) {
            if (input[8] <= 0.18610437214374542) {
                if (input[1] <= 0.13947010040283203) {
                    set_output2(var66, 0.9989896166216575, 0.0010103833783424241);
                } else {
                    set_output2(var66, 0.43864173651407695, 0.5613582634859231);
                }
            } else {
                set_output2(var66, 0.0, 1.0);
            }
        } else {
            set_output2(var66, 0.0142151954937621, 0.985784804506238);
        }
    } else {
        if (input[8] <= 0.0729021318256855) {
            if (input[0] <= 0.1070493832230568) {
                if (input[1] <= 0.10215343162417412) {
                    set_output2(var66, 1.0, 0.0);
                } else {
                    set_output2(var66, 0.0, 1.0);
                }
            } else {
                set_output2(var66, 0.00982497015442678, 0.9901750298455733);
            }
        } else {
            set_output2(var66, 0.0032533476325480445, 0.996746652367452);
        }
    }
    add_vectors(var15, var66, 2, var14);
    double var67[2];
    if (input[8] <= 0.12339957058429718) {
        if (input[9] <= 0.10937808826565742) {
            if (input[0] <= 0.1400689035654068) {
                set_output2(var67, 0.9970447290372728, 0.002955270962727111);
            } else {
                set_output2(var67, 0.0, 1.0);
            }
        } else {
            set_output2(var67, 0.016284410985996367, 0.9837155890140036);
        }
    } else {
        if (input[8] <= 0.14100482314825058) {
            if (input[2] <= 0.07418188825249672) {
                set_output2(var67, 0.8066363815919415, 0.19336361840805846);
            } else {
                set_output2(var67, 0.026044589561757047, 0.973955410438243);
            }
        } else {
            set_output2(var67, 0.002929143978471808, 0.9970708560215282);
        }
    }
    add_vectors(var14, var67, 2, var13);
    double var68[2];
    if (input[1] <= 0.10283876955509186) {
        if (input[8] <= 0.1385461911559105) {
            if (input[3] <= 0.15466037392616272) {
                if (input[2] <= 0.16081956773996353) {
                    set_output2(var68, 0.9979957414629448, 0.002004258537055252);
                } else {
                    set_output2(var68, 0.0, 1.0);
                }
            } else {
                set_output2(var68, 0.0, 1.0);
            }
        } else {
            set_output2(var68, 0.010215454122915338, 0.9897845458770848);
        }
    } else {
        if (input[1] <= 0.1315687894821167) {
            if (input[3] <= 0.10595239698886871) {
                if (input[9] <= 0.11870795860886574) {
                    set_output2(var68, 0.9330351029351348, 0.06696489706486514);
                } else {
                    set_output2(var68, 0.0, 1.0);
                }
            } else {
                set_output2(var68, 0.0, 1.0);
            }
        } else {
            if (input[4] <= 0.028789350762963295) {
                if (input[6] <= 0.08752012997865677) {
                    if (input[1] <= 0.19928105175495148) {
                        set_output2(var68, 1.0, 0.0);
                    } else {
                        set_output2(var68, 0.0, 1.0);
                    }
                } else {
                    set_output2(var68, 0.0, 1.0);
                }
            } else {
                set_output2(var68, 0.0, 1.0);
            }
        }
    }
    add_vectors(var13, var68, 2, var12);
    double var69[2];
    if (input[5] <= 0.05834882706403732) {
        if (input[0] <= 0.11824329942464828) {
            if (input[6] <= 0.3047651946544647) {
                if (input[8] <= 0.14348886162042618) {
                    if (input[4] <= 0.12632597237825394) {
                        set_output2(var69, 1.0, 0.0);
                    } else {
                        set_output2(var69, 0.0, 1.0);
                    }
                } else {
                    set_output2(var69, 0.08929466124812113, 0.9107053387518788);
                }
            } else {
                set_output2(var69, 0.10045090180360722, 0.8995490981963928);
            }
        } else {
            if (input[0] <= 0.1374647170305252) {
                if (input[8] <= 0.09397764503955841) {
                    set_output2(var69, 0.9476171721150058, 0.0523828278849941);
                } else {
                    set_output2(var69, 0.0, 1.0);
                }
            } else {
                set_output2(var69, 0.0, 1.0);
            }
        }
    } else {
        if (input[9] <= 0.04138157702982426) {
            if (input[0] <= 0.10748077929019928) {
                if (input[6] <= 0.20743704587221146) {
                    set_output2(var69, 0.9882932840418978, 0.011706715958102281);
                } else {
                    set_output2(var69, 0.1339121723159125, 0.8660878276840875);
                }
            } else {
                set_output2(var69, 0.0, 1.0);
            }
        } else {
            if (input[3] <= 0.08309749141335487) {
                if (input[8] <= 0.05225217528641224) {
                    if (input[4] <= 0.07241685315966606) {
                        set_output2(var69, 1.0, 0.0);
                    } else {
                        set_output2(var69, 0.0, 1.0);
                    }
                } else {
                    set_output2(var69, 0.0, 1.0);
                }
            } else {
                set_output2(var69, 0.0, 1.0);
            }
        }
    }
    add_vectors(var12, var69, 2, var11);
    double var70[2];
    if (input[0] <= 0.10538701713085175) {
        if (input[8] <= 0.14100482314825058) {
            if (input[4] <= 0.12779322266578674) {
                if (input[2] <= 0.15906240791082382) {
                    set_output2(var70, 0.9994896278159301, 0.0005103721840699349);
                } else {
                    set_output2(var70, 0.0, 1.0);
                }
            } else {
                set_output2(var70, 0.0, 1.0);
            }
        } else {
            set_output2(var70, 0.008437060569762, 0.9915629394302381);
        }
    } else {
        if (input[6] <= 0.15321751683950424) {
            if (input[0] <= 0.1325947865843773) {
                if (input[4] <= 0.10038198158144951) {
                    set_output2(var70, 0.9638443935926774, 0.036155606407322675);
                } else {
                    set_output2(var70, 0.0, 1.0);
                }
            } else {
                if (input[0] <= 0.13882482796907425) {
                    if (input[3] <= 0.0735970102250576) {
                        set_output2(var70, 1.0, 0.0);
                    } else {
                        set_output2(var70, 0.0, 1.0);
                    }
                } else {
                    set_output2(var70, 0.0, 1.0);
                }
            }
        } else {
            if (input[8] <= 0.0517280176281929) {
                if (input[4] <= 0.009858695790171623) {
                    if (input[9] <= 0.08731332421302795) {
                        set_output2(var70, 1.0, 0.0);
                    } else {
                        set_output2(var70, 0.0, 1.0);
                    }
                } else {
                    set_output2(var70, 0.0, 1.0);
                }
            } else {
                set_output2(var70, 0.0007773288676909464, 0.999222671132309);
            }
        }
    }
    add_vectors(var11, var70, 2, var10);
    double var71[2];
    if (input[8] <= 0.10670369118452072) {
        if (input[1] <= 0.12865446507930756) {
            if (input[9] <= 0.12996068596839905) {
                if (input[3] <= 0.22326602041721344) {
                    if (input[0] <= 0.21980439126491547) {
                        set_output2(var71, 0.9989865533428949, 0.0010134466571051332);
                    } else {
                        set_output2(var71, 0.0, 1.0);
                    }
                } else {
                    set_output2(var71, 0.0, 1.0);
                }
            } else {
                set_output2(var71, 0.0, 1.0);
            }
        } else {
            set_output2(var71, 0.0271873638859157, 0.9728126361140843);
        }
    } else {
        if (input[8] <= 0.14100482314825058) {
            if (input[0] <= 0.10118292272090912) {
                set_output2(var71, 0.9725711603765771, 0.02742883962342289);
            } else {
                set_output2(var71, 0.0, 1.0);
            }
        } else {
            set_output2(var71, 0.001157132965959444, 0.9988428670340406);
        }
    }
    add_vectors(var10, var71, 2, var9);
    double var72[2];
    if (input[9] <= 0.09955159202218056) {
        if (input[8] <= 0.12645499408245087) {
            if (input[7] <= 0.7746666073799133) {
                if (input[0] <= 0.14591716974973679) {
                    if (input[2] <= 0.18847092986106873) {
                        set_output2(var72, 1.0, 0.0);
                    } else {
                        set_output2(var72, 0.0, 1.0);
                    }
                } else {
                    set_output2(var72, 0.0, 1.0);
                }
            } else {
                if (input[0] <= 0.10403846576809883) {
                    set_output2(var72, 1.0, 0.0);
                } else {
                    set_output2(var72, 0.0, 1.0);
                }
            }
        } else {
            if (input[3] <= 0.07210483029484749) {
                if (input[0] <= 0.10482248105108738) {
                    set_output2(var72, 0.9250418123764634, 0.07495818762353654);
                } else {
                    set_output2(var72, 0.0, 1.0);
                }
            } else {
                set_output2(var72, 0.0, 1.0);
            }
        }
    } else {
        if (input[5] <= 0.02773563750088215) {
            if (input[9] <= 0.10681122913956642) {
                set_output2(var72, 1.0, 0.0);
            } else {
                set_output2(var72, 0.0, 1.0);
            }
        } else {
            set_output2(var72, 0.0, 1.0);
        }
    }
    add_vectors(var9, var72, 2, var8);
    double var73[2];
    if (input[8] <= 0.10615494102239609) {
        if (input[1] <= 0.12865446507930756) {
            if (input[2] <= 0.14652086794376373) {
                if (input[9] <= 0.13161956891417503) {
                    set_output2(var73, 0.9994970940940532, 0.000502905905946868);
                } else {
                    set_output2(var73, 0.0, 1.0);
                }
            } else {
                set_output2(var73, 0.08596787827557058, 0.9140321217244294);
            }
        } else {
            set_output2(var73, 0.021996323131826537, 0.9780036768681734);
        }
    } else {
        if (input[0] <= 0.08691488951444626) {
            if (input[8] <= 0.14203226566314697) {
                if (input[4] <= 0.10948819294571877) {
                    set_output2(var73, 1.0, 0.0);
                } else {
                    set_output2(var73, 0.0, 1.0);
                }
            } else {
                set_output2(var73, 0.010662053782041202, 0.9893379462179588);
            }
        } else {
            set_output2(var73, 0.0024837985265726433, 0.9975162014734273);
        }
    }
    add_vectors(var8, var73, 2, var7);
    double var74[2];
    if (input[8] <= 0.11413109675049782) {
        if (input[0] <= 0.1344325765967369) {
            if (input[3] <= 0.11546361818909645) {
                if (input[9] <= 0.1753719598054886) {
                    set_output2(var74, 0.998999821760497, 0.0010001782395029498);
                } else {
                    set_output2(var74, 0.0, 1.0);
                }
            } else {
                set_output2(var74, 0.06464312928625857, 0.9353568707137415);
            }
        } else {
            set_output2(var74, 0.0060258079791642, 0.9939741920208358);
        }
    } else {
        if (input[0] <= 0.08095439150929451) {
            if (input[3] <= 0.08105329051613808) {
                if (input[7] <= 0.5804862678050995) {
                    set_output2(var74, 0.9031940063091483, 0.09680599369085174);
                } else {
                    set_output2(var74, 0.16274112757113932, 0.8372588724288608);
                }
            } else {
                set_output2(var74, 0.0, 1.0);
            }
        } else {
            set_output2(var74, 0.0025007676718049624, 0.997499232328195);
        }
    }
    add_vectors(var7, var74, 2, var6);
    double var75[2];
    if (input[8] <= 0.11425164714455605) {
        if (input[4] <= 0.10333641245961189) {
            if (input[5] <= 0.08786574751138687) {
                if (input[0] <= 0.13870424032211304) {
                    set_output2(var75, 0.9989932277448175, 0.0010067722551825235);
                } else {
                    set_output2(var75, 0.0, 1.0);
                }
            } else {
                set_output2(var75, 0.0, 1.0);
            }
        } else {
            if (input[3] <= 0.0519886240363121) {
                if (input[0] <= 0.07485849410295486) {
                    set_output2(var75, 1.0, 0.0);
                } else {
                    set_output2(var75, 0.0, 1.0);
                }
            } else {
                set_output2(var75, 0.0, 1.0);
            }
        }
    } else {
        if (input[8] <= 0.12382469698786736) {
            if (input[0] <= 0.09659845754504204) {
                set_output2(var75, 0.9295599716110716, 0.07044002838892832);
            } else {
                set_output2(var75, 0.0, 1.0);
            }
        } else {
            if (input[8] <= 0.14100482314825058) {
                if (input[3] <= 0.06994679756462574) {
                    set_output2(var75, 0.8766314481044126, 0.12336855189558733);
                } else {
                    set_output2(var75, 0.0, 1.0);
                }
            } else {
                set_output2(var75, 0.0023030709994499785, 0.9976969290005501);
            }
        }
    }
    add_vectors(var6, var75, 2, var5);
    double var76[2];
    if (input[8] <= 0.12419689074158669) {
        if (input[1] <= 0.11498700454831123) {
            if (input[0] <= 0.14104454964399338) {
                if (input[4] <= 0.11222967132925987) {
                    set_output2(var76, 1.0, 0.0);
                } else {
                    set_output2(var76, 0.0, 1.0);
                }
            } else {
                set_output2(var76, 0.0, 1.0);
            }
        } else {
            if (input[3] <= 0.03838389925658703) {
                if (input[0] <= 0.13490768149495125) {
                    set_output2(var76, 0.8812087105456324, 0.11879128945436748);
                } else {
                    set_output2(var76, 0.0, 1.0);
                }
            } else {
                set_output2(var76, 0.0, 1.0);
            }
        }
    } else {
        if (input[0] <= 0.04227904602885246) {
            if (input[7] <= 0.5383969843387604) {
                if (input[2] <= 0.11267765983939171) {
                    set_output2(var76, 1.0, 0.0);
                } else {
                    set_output2(var76, 0.0, 1.0);
                }
            } else {
                set_output2(var76, 0.0, 1.0);
            }
        } else {
            set_output2(var76, 0.0018092615200492556, 0.9981907384799508);
        }
    }
    add_vectors(var5, var76, 2, var4);
    double var77[2];
    if (input[0] <= 0.11845816671848297) {
        if (input[2] <= 0.1173897311091423) {
            if (input[4] <= 0.10267992317676544) {
                if (input[8] <= 0.17956365644931793) {
                    set_output2(var77, 0.9994862685950097, 0.0005137314049903256);
                } else {
                    set_output2(var77, 0.0, 1.0);
                }
            } else {
                if (input[9] <= 0.011699943337589502) {
                    set_output2(var77, 1.0, 0.0);
                } else {
                    set_output2(var77, 0.0, 1.0);
                }
            }
        } else {
            if (input[3] <= 0.06378144770860672) {
                if (input[6] <= 0.13878846168518066) {
                    set_output2(var77, 1.0, 0.0);
                } else {
                    set_output2(var77, 0.03950376747052625, 0.9604962325294737);
                }
            } else {
                set_output2(var77, 0.0, 1.0);
            }
        }
    } else {
        if (input[0] <= 0.12656652182340622) {
            if (input[3] <= 0.12080321088433266) {
                if (input[2] <= 0.10104227811098099) {
                    set_output2(var77, 1.0, 0.0);
                } else {
                    set_output2(var77, 0.0, 1.0);
                }
            } else {
                set_output2(var77, 0.0, 1.0);
            }
        } else {
            set_output2(var77, 0.0024724255184923067, 0.9975275744815076);
        }
    }
    add_vectors(var4, var77, 2, var3);
    double var78[2];
    if (input[4] <= 0.07318073883652687) {
        if (input[0] <= 0.12325871363282204) {
            if (input[2] <= 0.1493745669722557) {
                if (input[9] <= 0.11077576130628586) {
                    set_output2(var78, 1.0, 0.0);
                } else {
                    set_output2(var78, 0.0, 1.0);
                }
            } else {
                set_output2(var78, 0.03559625447535115, 0.9644037455246488);
            }
        } else {
            if (input[2] <= 0.015791398473083973) {
                if (input[3] <= 0.07794222608208656) {
                    set_output2(var78, 0.8652719665271966, 0.13472803347280335);
                } else {
                    set_output2(var78, 0.0, 1.0);
                }
            } else {
                set_output2(var78, 0.009302074524550608, 0.9906979254754494);
            }
        }
    } else {
        if (input[4] <= 0.08882874622941017) {
            if (input[3] <= 0.09310203418135643) {
                if (input[9] <= 0.10049628466367722) {
                    set_output2(var78, 0.9760047692384123, 0.02399523076158776);
                } else {
                    set_output2(var78, 0.0, 1.0);
                }
            } else {
                set_output2(var78, 0.0, 1.0);
            }
        } else {
            if (input[4] <= 0.10036695748567581) {
                if (input[1] <= 0.061448246240615845) {
                    if (input[8] <= 0.13471921905875206) {
                        set_output2(var78, 1.0, 0.0);
                    } else {
                        set_output2(var78, 0.0, 1.0);
                    }
                } else {
                    set_output2(var78, 0.01125895598771749, 0.9887410440122825);
                }
            } else {
                set_output2(var78, 0.0014823947700424423, 0.9985176052299576);
            }
        }
    }
    add_vectors(var3, var78, 2, var2);
    double var79[2];
    if (input[3] <= 0.08750653266906738) {
        if (input[0] <= 0.11759750172495842) {
            if (input[8] <= 0.16452347487211227) {
                set_output2(var79, 0.9989387088866063, 0.0010612911133936855);
            } else {
                set_output2(var79, 0.0, 1.0);
            }
        } else {
            if (input[9] <= 0.07749718055129051) {
                if (input[8] <= 0.08631166443228722) {
                    if (input[2] <= 0.08893020078539848) {
                        set_output2(var79, 1.0, 0.0);
                    } else {
                        set_output2(var79, 0.0, 1.0);
                    }
                } else {
                    set_output2(var79, 0.0, 1.0);
                }
            } else {
                set_output2(var79, 0.0, 1.0);
            }
        }
    } else {
        if (input[3] <= 0.10806801542639732) {
            if (input[2] <= 0.09051911532878876) {
                if (input[5] <= 0.1005745530128479) {
                    set_output2(var79, 0.9579542660437669, 0.04204573395623311);
                } else {
                    set_output2(var79, 0.0, 1.0);
                }
            } else {
                set_output2(var79, 0.030673301001448654, 0.9693266989985514);
            }
        } else {
            set_output2(var79, 0.0030568984846069385, 0.996943101515393);
        }
    }
    add_vectors(var2, var79, 2, var1);
    mul_vector_number(var1, 0.025, 2, var0);
    memcpy(output, var0, 2 * sizeof(double));
}
