#pragma once

#include <stdint.h>

enum TinyMLFeatureId : uint8_t {
  TINYML_FEATURE_ABS_IRMS_ZSCORE_VS_BASELINE = 0,
  TINYML_FEATURE_DELTA_IRMS_ABS = 1,
  TINYML_FEATURE_HALFCYCLE_ASYMMETRY = 2,
  TINYML_FEATURE_SUSPICIOUS_RUN_ENERGY = 3,
  TINYML_FEATURE_DELTA_HF_ENERGY = 4,
  TINYML_FEATURE_DELTA_FLUX = 5,
  TINYML_FEATURE_MIDBAND_RESIDUAL_RATIO = 6,
  TINYML_FEATURE_ZCV = 7,
  TINYML_FEATURE_SPECTRAL_FLUX_MIDHF = 8,
  TINYML_FEATURE_PEAK_FLUCT_CV = 9,
  TINYML_FEATURE_RESIDUAL_CREST_FACTOR = 10,
  TINYML_FEATURE_THD_I = 11,
  TINYML_FEATURE_HF_ENERGY_DELTA = 12,
  TINYML_FEATURE_EDGE_SPIKE_RATIO = 13,
  TINYML_FEATURE_V_SAG_PCT = 14,
  TINYML_FEATURE_CYCLE_NMSE = 15,
  TINYML_FEATURE_CTX_FAMILY_RESISTIVE_LINEAR = 16,
  TINYML_FEATURE_CTX_FAMILY_INDUCTIVE_MOTOR = 17,
  TINYML_FEATURE_CTX_FAMILY_RECTIFIER_SMPS = 18,
  TINYML_FEATURE_CTX_FAMILY_PHASE_ANGLE_CONTROLLED = 19,
  TINYML_FEATURE_CTX_FAMILY_BRUSH_UNIVERSAL_MOTOR = 20,
  TINYML_FEATURE_CTX_FAMILY_OTHER_MIXED = 21,
  TINYML_FEATURE_CONTEXT_FAMILY_CONFIDENCE = 22,
};

static constexpr uint8_t TINYML_COMPUTED_FEATURE_COUNT = 16;
static constexpr uint8_t TINYML_ARC_CONTEXT_INPUT_COUNT = 7;
static constexpr uint8_t TINYML_MODEL_INPUT_FEATURE_COUNT = 23;
