#pragma once
// Auto-generated by m2cgen from scikit-learn RandomForest
#define ARC_THRESHOLD 0.3300

// Input Feature Order:
// [0] cycle_nmse
// [1] zcv
// [2] zc_dwell_ratio
// [3] cycle_rms_drop_ratio
// [4] peak_fluct_cv
// [5] midband_residual_rms
// [6] hf_band_energy_ratio
// [7] wpe_entropy
// [8] spec_entropy
// [9] dip_rebound_ratio

#include <string.h>
#include <string.h>
static inline void add_vectors(double *v1, double *v2, int size, double *result) {
    for(int i = 0; i < size; ++i)
        result[i] = v1[i] + v2[i];
}
static inline void mul_vector_number(double *v1, double num, int size, double *result) {
    for(int i = 0; i < size; ++i)
        result[i] = v1[i] * num;
}
static inline void set_output2(double *dst, double a, double b) {
    dst[0] = a;
    dst[1] = b;
}
static inline void arc_rf_predict(double * input, double * output) {
    double var0[2];
    double var1[2];
    double var2[2];
    double var3[2];
    double var4[2];
    double var5[2];
    double var6[2];
    double var7[2];
    double var8[2];
    double var9[2];
    double var10[2];
    double var11[2];
    double var12[2];
    double var13[2];
    double var14[2];
    double var15[2];
    double var16[2];
    double var17[2];
    double var18[2];
    double var19[2];
    double var20[2];
    double var21[2];
    double var22[2];
    double var23[2];
    double var24[2];
    double var25[2];
    double var26[2];
    double var27[2];
    double var28[2];
    double var29[2];
    double var30[2];
    double var31[2];
    double var32[2];
    double var33[2];
    double var34[2];
    double var35[2];
    double var36[2];
    double var37[2];
    double var38[2];
    double var39[2];
    double var40[2];
    double var41[2];
    double var42[2];
    double var43[2];
    double var44[2];
    double var45[2];
    double var46[2];
    double var47[2];
    double var48[2];
    double var49[2];
    double var50[2];
    double var51[2];
    double var52[2];
    double var53[2];
    double var54[2];
    double var55[2];
    double var56[2];
    double var57[2];
    double var58[2];
    double var59[2];
    double var60[2];
    double var61[2];
    double var62[2];
    double var63[2];
    double var64[2];
    double var65[2];
    double var66[2];
    double var67[2];
    double var68[2];
    double var69[2];
    double var70[2];
    double var71[2];
    double var72[2];
    double var73[2];
    double var74[2];
    double var75[2];
    double var76[2];
    double var77[2];
    double var78[2];
    double var79[2];
    double var80[2];
    if (input[4] <= 0.011796427424997091) {
        set_output2(var80, 0.9994989409021595, 0.000501059097840389);
    } else {
        if (input[2] <= 0.10518356785178185) {
            set_output2(var80, 0.8784554629223343, 0.12154453707766565);
        } else {
            set_output2(var80, 0.0, 1.0);
        }
    }
    double var81[2];
    if (input[4] <= 0.011730728670954704) {
        set_output2(var81, 1.0, 0.0);
    } else {
        set_output2(var81, 0.0009950248756218788, 0.9990049751243781);
    }
    add_vectors(var80, var81, 2, var79);
    double var82[2];
    if (input[4] <= 0.011796427424997091) {
        set_output2(var82, 1.0, 0.0);
    } else {
        set_output2(var82, 0.0010277492291880833, 0.998972250770812);
    }
    add_vectors(var79, var82, 2, var78);
    double var83[2];
    if (input[4] <= 0.011796427424997091) {
        set_output2(var83, 0.9990023747817696, 0.0009976252182304982);
    } else {
        if (input[2] <= 0.1054646447300911) {
            set_output2(var83, 0.8618618618618619, 0.13813813813813813);
        } else {
            set_output2(var83, 0.0, 1.0);
        }
    }
    add_vectors(var78, var83, 2, var77);
    double var84[2];
    if (input[4] <= 0.010405571665614843) {
        set_output2(var84, 1.0, 0.0);
    } else {
        set_output2(var84, 0.0014992503748125806, 0.9985007496251874);
    }
    add_vectors(var77, var84, 2, var76);
    double var85[2];
    if (input[5] <= 0.0633857473731041) {
        if (input[3] <= 0.10272813774645329) {
            set_output2(var85, 1.0, 0.0);
        } else {
            set_output2(var85, 0.0, 1.0);
        }
    } else {
        if (input[3] <= 0.021486299112439156) {
            set_output2(var85, 0.7079258502408409, 0.29207414975915924);
        } else {
            set_output2(var85, 0.0, 1.0);
        }
    }
    add_vectors(var76, var85, 2, var75);
    double var86[2];
    if (input[4] <= 0.011796427424997091) {
        set_output2(var86, 1.0, 0.0);
    } else {
        set_output2(var86, 0.0015075376884422216, 0.9984924623115579);
    }
    add_vectors(var75, var86, 2, var74);
    double var87[2];
    if (input[3] <= 0.03607284277677536) {
        if (input[5] <= 0.08961085602641106) {
            set_output2(var87, 1.0, 0.0);
        } else {
            set_output2(var87, 0.0, 1.0);
        }
    } else {
        if (input[6] <= 0.16281292587518692) {
            set_output2(var87, 0.9104655425219942, 0.08953445747800587);
        } else {
            if (input[7] <= 0.08816269040107727) {
                set_output2(var87, 0.8356463958280764, 0.16435360417192363);
            } else {
                set_output2(var87, 0.0, 1.0);
            }
        }
    }
    add_vectors(var74, var87, 2, var73);
    double var88[2];
    if (input[9] <= 0.010528442915529013) {
        if (input[5] <= 0.11390647292137146) {
            set_output2(var88, 1.0, 0.0);
        } else {
            set_output2(var88, 0.0, 1.0);
        }
    } else {
        if (input[3] <= 0.021547244861721992) {
            set_output2(var88, 1.0, 0.0);
        } else {
            set_output2(var88, 0.0, 1.0);
        }
    }
    add_vectors(var73, var88, 2, var72);
    double var89[2];
    if (input[4] <= 0.011796427424997091) {
        set_output2(var89, 1.0, 0.0);
    } else {
        if (input[3] <= 0.021486299112439156) {
            set_output2(var89, 0.8023443815683103, 0.19765561843168952);
        } else {
            set_output2(var89, 0.0, 1.0);
        }
    }
    add_vectors(var72, var89, 2, var71);
    double var90[2];
    if (input[3] <= 0.04138726182281971) {
        if (input[4] <= 0.018749834969639778) {
            set_output2(var90, 1.0, 0.0);
        } else {
            set_output2(var90, 0.0, 1.0);
        }
    } else {
        set_output2(var90, 0.0005162584381278079, 0.9994837415618721);
    }
    add_vectors(var71, var90, 2, var70);
    double var91[2];
    if (input[4] <= 0.013610146939754486) {
        set_output2(var91, 0.9984833164812943, 0.0015166835187057528);
    } else {
        set_output2(var91, 0.0, 1.0);
    }
    add_vectors(var70, var91, 2, var69);
    double var92[2];
    if (input[5] <= 0.06344390660524368) {
        if (input[3] <= 0.10015424340963364) {
            set_output2(var92, 1.0, 0.0);
        } else {
            set_output2(var92, 0.0, 1.0);
        }
    } else {
        if (input[4] <= 0.008052806369960308) {
            set_output2(var92, 1.0, 0.0);
        } else {
            set_output2(var92, 0.0, 1.0);
        }
    }
    add_vectors(var69, var92, 2, var68);
    double var93[2];
    if (input[4] <= 0.011796427424997091) {
        set_output2(var93, 1.0, 0.0);
    } else {
        set_output2(var93, 0.001013171225937191, 0.9989868287740629);
    }
    add_vectors(var68, var93, 2, var67);
    double var94[2];
    if (input[5] <= 0.06344390660524368) {
        if (input[4] <= 0.018289408646523952) {
            set_output2(var94, 1.0, 0.0);
        } else {
            set_output2(var94, 0.0, 1.0);
        }
    } else {
        if (input[3] <= 0.019548416137695312) {
            set_output2(var94, 1.0, 0.0);
        } else {
            set_output2(var94, 0.0, 1.0);
        }
    }
    add_vectors(var67, var94, 2, var66);
    double var95[2];
    if (input[9] <= 0.010528442915529013) {
        if (input[4] <= 0.02367842197418213) {
            set_output2(var95, 1.0, 0.0);
        } else {
            set_output2(var95, 0.0, 1.0);
        }
    } else {
        if (input[4] <= 0.009442504961043596) {
            set_output2(var95, 1.0, 0.0);
        } else {
            set_output2(var95, 0.0, 1.0);
        }
    }
    add_vectors(var66, var95, 2, var65);
    double var96[2];
    if (input[4] <= 0.0118919862434268) {
        set_output2(var96, 0.9994890203801761, 0.0005109796198239559);
    } else {
        set_output2(var96, 0.001008071003620137, 0.9989919289963799);
    }
    add_vectors(var65, var96, 2, var64);
    double var97[2];
    if (input[4] <= 0.011649401392787695) {
        set_output2(var97, 0.9994974768182191, 0.0005025231817809298);
    } else {
        set_output2(var97, 0.0010251045055685519, 0.9989748954944315);
    }
    add_vectors(var64, var97, 2, var63);
    double var98[2];
    if (input[4] <= 0.011796427424997091) {
        set_output2(var98, 0.999507631708518, 0.0004923682914820278);
    } else {
        set_output2(var98, 0.0, 1.0);
    }
    add_vectors(var63, var98, 2, var62);
    double var99[2];
    if (input[4] <= 0.011796427424997091) {
        set_output2(var99, 1.0, 0.0);
    } else {
        set_output2(var99, 0.000997506234413968, 0.999002493765586);
    }
    add_vectors(var62, var99, 2, var61);
    double var100[2];
    if (input[5] <= 0.06356324627995491) {
        if (input[0] <= 0.12756529450416565) {
            set_output2(var100, 1.0, 0.0);
        } else {
            set_output2(var100, 0.0, 1.0);
        }
    } else {
        if (input[3] <= 0.01707199541851878) {
            set_output2(var100, 1.0, 0.0);
        } else {
            set_output2(var100, 0.0005267729127244751, 0.9994732270872755);
        }
    }
    add_vectors(var61, var100, 2, var60);
    double var101[2];
    if (input[4] <= 0.013739950954914093) {
        if (input[1] <= 0.8098801970481873) {
            set_output2(var101, 1.0, 0.0);
        } else {
            set_output2(var101, 0.24199824275134935, 0.7580017572486506);
        }
    } else {
        set_output2(var101, 0.0, 1.0);
    }
    add_vectors(var60, var101, 2, var59);
    double var102[2];
    if (input[4] <= 0.011796427424997091) {
        set_output2(var102, 0.9994813391601303, 0.000518660839869834);
    } else {
        set_output2(var102, 0.0004967818686985886, 0.9995032181313014);
    }
    add_vectors(var59, var102, 2, var58);
    double var103[2];
    if (input[9] <= 0.01047493889927864) {
        if (input[4] <= 0.02479440625756979) {
            set_output2(var103, 1.0, 0.0);
        } else {
            set_output2(var103, 0.0, 1.0);
        }
    } else {
        if (input[4] <= 0.008533876156434417) {
            set_output2(var103, 1.0, 0.0);
        } else {
            set_output2(var103, 0.0, 1.0);
        }
    }
    add_vectors(var58, var103, 2, var57);
    double var104[2];
    if (input[4] <= 0.013610146939754486) {
        set_output2(var104, 0.9995032290114257, 0.000496770988574273);
    } else {
        set_output2(var104, 0.0, 1.0);
    }
    add_vectors(var57, var104, 2, var56);
    double var105[2];
    if (input[4] <= 0.013010803610086441) {
        set_output2(var105, 1.0, 0.0);
    } else {
        set_output2(var105, 0.00102459016393441, 0.9989754098360657);
    }
    add_vectors(var56, var105, 2, var55);
    double var106[2];
    if (input[3] <= 0.04110341519117355) {
        if (input[4] <= 0.018749834969639778) {
            set_output2(var106, 1.0, 0.0);
        } else {
            set_output2(var106, 0.0, 1.0);
        }
    } else {
        set_output2(var106, 0.0010840088348569798, 0.9989159911651431);
    }
    add_vectors(var55, var106, 2, var54);
    double var107[2];
    if (input[5] <= 0.06344390660524368) {
        if (input[3] <= 0.10272813774645329) {
            set_output2(var107, 1.0, 0.0);
        } else {
            set_output2(var107, 0.0, 1.0);
        }
    } else {
        if (input[4] <= 0.007261339109390974) {
            set_output2(var107, 1.0, 0.0);
        } else {
            set_output2(var107, 0.0, 1.0);
        }
    }
    add_vectors(var54, var107, 2, var53);
    double var108[2];
    if (input[3] <= 0.03910825215280056) {
        if (input[4] <= 0.018749834969639778) {
            set_output2(var108, 1.0, 0.0);
        } else {
            set_output2(var108, 0.0, 1.0);
        }
    } else {
        if (input[4] <= 0.011205219198018312) {
            set_output2(var108, 0.7478050642575391, 0.2521949357424609);
        } else {
            set_output2(var108, 0.0, 1.0);
        }
    }
    add_vectors(var53, var108, 2, var52);
    double var109[2];
    if (input[4] <= 0.011796427424997091) {
        set_output2(var109, 1.0, 0.0);
    } else {
        set_output2(var109, 0.0005144032921810797, 0.9994855967078189);
    }
    add_vectors(var52, var109, 2, var51);
    double var110[2];
    if (input[4] <= 0.013010803610086441) {
        set_output2(var110, 0.9984977276780165, 0.0015022723219834124);
    } else {
        set_output2(var110, 0.000514383795286088, 0.9994856162047139);
    }
    add_vectors(var51, var110, 2, var50);
    double var111[2];
    if (input[4] <= 0.011796427424997091) {
        set_output2(var111, 1.0, 0.0);
    } else {
        set_output2(var111, 0.0010282776349614586, 0.9989717223650385);
    }
    add_vectors(var50, var111, 2, var49);
    double var112[2];
    if (input[3] <= 0.03397362306714058) {
        if (input[5] <= 0.10709628462791443) {
            set_output2(var112, 1.0, 0.0);
        } else {
            set_output2(var112, 0.0, 1.0);
        }
    } else {
        if (input[4] <= 0.009335766546428204) {
            set_output2(var112, 1.0, 0.0);
        } else {
            set_output2(var112, 0.0, 1.0);
        }
    }
    add_vectors(var49, var112, 2, var48);
    double var113[2];
    if (input[5] <= 0.06775535643100739) {
        if (input[4] <= 0.018891802988946438) {
            set_output2(var113, 1.0, 0.0);
        } else {
            set_output2(var113, 0.0, 1.0);
        }
    } else {
        if (input[4] <= 0.007968130055814981) {
            set_output2(var113, 1.0, 0.0);
        } else {
            set_output2(var113, 0.0, 1.0);
        }
    }
    add_vectors(var48, var113, 2, var47);
    double var114[2];
    if (input[4] <= 0.011826287489384413) {
        set_output2(var114, 1.0, 0.0);
    } else {
        set_output2(var114, 0.0015082956259426627, 0.9984917043740573);
    }
    add_vectors(var47, var114, 2, var46);
    double var115[2];
    if (input[4] <= 0.011796427424997091) {
        set_output2(var115, 0.9994892830653123, 0.0005107169346877945);
    } else {
        set_output2(var115, 0.0015128674782120168, 0.9984871325217879);
    }
    add_vectors(var46, var115, 2, var45);
    double var116[2];
    if (input[5] <= 0.06534364446997643) {
        if (input[3] <= 0.10272813774645329) {
            set_output2(var116, 1.0, 0.0);
        } else {
            set_output2(var116, 0.0, 1.0);
        }
    } else {
        if (input[4] <= 0.006692052120342851) {
            set_output2(var116, 1.0, 0.0);
        } else {
            set_output2(var116, 0.0, 1.0);
        }
    }
    add_vectors(var45, var116, 2, var44);
    double var117[2];
    if (input[9] <= 0.011109763290733099) {
        if (input[5] <= 0.11314297839999199) {
            set_output2(var117, 1.0, 0.0);
        } else {
            set_output2(var117, 0.0, 1.0);
        }
    } else {
        if (input[4] <= 0.007742408895865083) {
            set_output2(var117, 1.0, 0.0);
        } else {
            set_output2(var117, 0.0, 1.0);
        }
    }
    add_vectors(var44, var117, 2, var43);
    double var118[2];
    if (input[4] <= 0.011730728670954704) {
        set_output2(var118, 0.9985198509333677, 0.001480149066632249);
    } else {
        if (input[3] <= 0.02155445422977209) {
            set_output2(var118, 0.7606003752345216, 0.23939962476547844);
        } else {
            set_output2(var118, 0.0, 1.0);
        }
    }
    add_vectors(var43, var118, 2, var42);
    double var119[2];
    if (input[4] <= 0.010405571665614843) {
        set_output2(var119, 1.0, 0.0);
    } else {
        set_output2(var119, 0.001550387596899241, 0.9984496124031007);
    }
    add_vectors(var42, var119, 2, var41);
    double var120[2];
    if (input[3] <= 0.03667139820754528) {
        if (input[4] <= 0.01862003095448017) {
            set_output2(var120, 1.0, 0.0);
        } else {
            set_output2(var120, 0.0, 1.0);
        }
    } else {
        if (input[7] <= 0.0922245942056179) {
            set_output2(var120, 0.7548216311609732, 0.24517836883902686);
        } else {
            set_output2(var120, 0.0010487415233075513, 0.9989512584766924);
        }
    }
    add_vectors(var41, var120, 2, var40);
    double var121[2];
    if (input[3] <= 0.036151980981230736) {
        if (input[7] <= 0.18370938301086426) {
            set_output2(var121, 1.0, 0.0);
        } else {
            set_output2(var121, 0.0, 1.0);
        }
    } else {
        if (input[4] <= 0.00854429928585887) {
            set_output2(var121, 1.0, 0.0);
        } else {
            set_output2(var121, 0.0, 1.0);
        }
    }
    add_vectors(var40, var121, 2, var39);
    double var122[2];
    if (input[4] <= 0.010392774362117052) {
        set_output2(var122, 1.0, 0.0);
    } else {
        set_output2(var122, 0.0010075566750629614, 0.9989924433249371);
    }
    add_vectors(var39, var122, 2, var38);
    double var123[2];
    if (input[4] <= 0.011796427424997091) {
        set_output2(var123, 0.9984968874042569, 0.0015031125957431523);
    } else {
        if (input[2] <= 0.1055404283106327) {
            set_output2(var123, 0.6315190593589987, 0.3684809406410013);
        } else {
            set_output2(var123, 0.0, 1.0);
        }
    }
    add_vectors(var38, var123, 2, var37);
    double var124[2];
    if (input[4] <= 0.011796427424997091) {
        set_output2(var124, 0.9989837424546869, 0.0010162575453131046);
    } else {
        set_output2(var124, 0.0010136873547138365, 0.9989863126452861);
    }
    add_vectors(var37, var124, 2, var36);
    double var125[2];
    if (input[4] <= 0.011796427424997091) {
        set_output2(var125, 0.9994962178996665, 0.0005037821003335183);
    } else {
        set_output2(var125, 0.0005112436252298333, 0.9994887563747702);
    }
    add_vectors(var36, var125, 2, var35);
    double var126[2];
    if (input[4] <= 0.011354229878634214) {
        set_output2(var126, 1.0, 0.0);
    } else {
        set_output2(var126, 0.001018329938900203, 0.9989816700610998);
    }
    add_vectors(var35, var126, 2, var34);
    double var127[2];
    if (input[4] <= 0.011796427424997091) {
        set_output2(var127, 1.0, 0.0);
    } else {
        if (input[7] <= 0.08816269040107727) {
            set_output2(var127, 0.711897666981612, 0.28810233301838795);
        } else {
            set_output2(var127, 0.0, 1.0);
        }
    }
    add_vectors(var34, var127, 2, var33);
    double var128[2];
    if (input[3] <= 0.0414251908659935) {
        if (input[5] <= 0.10709628462791443) {
            set_output2(var128, 1.0, 0.0);
        } else {
            set_output2(var128, 0.0, 1.0);
        }
    } else {
        set_output2(var128, 0.001526710359550884, 0.9984732896404491);
    }
    add_vectors(var33, var128, 2, var32);
    double var129[2];
    if (input[4] <= 0.013865464832633734) {
        if (input[1] <= 0.7873021960258484) {
            set_output2(var129, 1.0, 0.0);
        } else {
            set_output2(var129, 0.25257797581158503, 0.7474220241884151);
        }
    } else {
        set_output2(var129, 0.0, 1.0);
    }
    add_vectors(var32, var129, 2, var31);
    double var130[2];
    if (input[5] <= 0.06366866454482079) {
        if (input[2] <= 0.26002420485019684) {
            set_output2(var130, 1.0, 0.0);
        } else {
            set_output2(var130, 0.0, 1.0);
        }
    } else {
        if (input[3] <= 0.019591040909290314) {
            set_output2(var130, 1.0, 0.0);
        } else {
            set_output2(var130, 0.0005099921412339234, 0.9994900078587661);
        }
    }
    add_vectors(var31, var130, 2, var30);
    double var131[2];
    if (input[5] <= 0.06356324627995491) {
        if (input[0] <= 0.14752690121531487) {
            set_output2(var131, 1.0, 0.0);
        } else {
            set_output2(var131, 0.0, 1.0);
        }
    } else {
        if (input[7] <= 0.09506302326917648) {
            if (input[5] <= 0.09850636124610901) {
                set_output2(var131, 0.8719148663375857, 0.12808513366241428);
            } else {
                set_output2(var131, 0.0, 1.0);
            }
        } else {
            if (input[4] <= 0.011109660379588604) {
                set_output2(var131, 0.7954964176049131, 0.20450358239508704);
            } else {
                set_output2(var131, 0.0, 1.0);
            }
        }
    }
    add_vectors(var30, var131, 2, var29);
    double var132[2];
    if (input[4] <= 0.010405571665614843) {
        set_output2(var132, 1.0, 0.0);
    } else {
        if (input[7] <= 0.08602088689804077) {
            set_output2(var132, 0.8279790970615951, 0.17202090293840486);
        } else {
            set_output2(var132, 0.0, 1.0);
        }
    }
    add_vectors(var29, var132, 2, var28);
    double var133[2];
    if (input[3] <= 0.04110341519117355) {
        if (input[5] <= 0.1314438357949257) {
            set_output2(var133, 1.0, 0.0);
        } else {
            set_output2(var133, 0.0, 1.0);
        }
    } else {
        set_output2(var133, 0.0010259580506482033, 0.9989740419493518);
    }
    add_vectors(var28, var133, 2, var27);
    double var134[2];
    if (input[4] <= 0.013942408841103315) {
        if (input[1] <= 0.8118664920330048) {
            set_output2(var134, 1.0, 0.0);
        } else {
            set_output2(var134, 0.3204891941698777, 0.6795108058301222);
        }
    } else {
        set_output2(var134, 0.0, 1.0);
    }
    add_vectors(var27, var134, 2, var26);
    double var135[2];
    if (input[4] <= 0.011796427424997091) {
        set_output2(var135, 0.9994923812018462, 0.0005076187981537753);
    } else {
        if (input[8] <= 0.3981941342353821) {
            set_output2(var135, 0.7150101419878296, 0.28498985801217036);
        } else {
            set_output2(var135, 0.0, 1.0);
        }
    }
    add_vectors(var26, var135, 2, var25);
    double var136[2];
    if (input[3] <= 0.036151980981230736) {
        if (input[5] <= 0.11046934127807617) {
            set_output2(var136, 1.0, 0.0);
        } else {
            set_output2(var136, 0.0, 1.0);
        }
    } else {
        if (input[4] <= 0.00854429928585887) {
            set_output2(var136, 1.0, 0.0);
        } else {
            set_output2(var136, 0.0, 1.0);
        }
    }
    add_vectors(var25, var136, 2, var24);
    double var137[2];
    if (input[9] <= 0.011039651930332184) {
        if (input[5] <= 0.1273052915930748) {
            set_output2(var137, 1.0, 0.0);
        } else {
            set_output2(var137, 0.0, 1.0);
        }
    } else {
        if (input[3] <= 0.02156412322074175) {
            set_output2(var137, 1.0, 0.0);
        } else {
            set_output2(var137, 0.0, 1.0);
        }
    }
    add_vectors(var24, var137, 2, var23);
    double var138[2];
    if (input[4] <= 0.011649401392787695) {
        set_output2(var138, 1.0, 0.0);
    } else {
        set_output2(var138, 0.0004950495049505005, 0.9995049504950495);
    }
    add_vectors(var23, var138, 2, var22);
    double var139[2];
    if (input[4] <= 0.013942408841103315) {
        set_output2(var139, 0.9989873417721519, 0.0010126582278481122);
    } else {
        set_output2(var139, 0.0, 1.0);
    }
    add_vectors(var22, var139, 2, var21);
    double var140[2];
    if (input[4] <= 0.013010803610086441) {
        set_output2(var140, 0.9994994924085389, 0.0005005075914611239);
    } else {
        set_output2(var140, 0.0005146607476387651, 0.9994853392523613);
    }
    add_vectors(var21, var140, 2, var20);
    double var141[2];
    if (input[4] <= 0.0118919862434268) {
        set_output2(var141, 0.9994835046556818, 0.0005164953443181833);
    } else {
        if (input[2] <= 0.10680433362722397) {
            set_output2(var141, 0.6595238095238095, 0.3404761904761905);
        } else {
            set_output2(var141, 0.0, 1.0);
        }
    }
    add_vectors(var20, var141, 2, var19);
    double var142[2];
    if (input[4] <= 0.011730728670954704) {
        set_output2(var142, 0.9990195732256891, 0.00098042677431085);
    } else {
        set_output2(var142, 0.0005260017443961616, 0.9994739982556038);
    }
    add_vectors(var19, var142, 2, var18);
    double var143[2];
    if (input[4] <= 0.013739950954914093) {
        if (input[7] <= 0.17620298266410828) {
            set_output2(var143, 1.0, 0.0);
        } else {
            set_output2(var143, 0.1480936257912557, 0.8519063742087443);
        }
    } else {
        set_output2(var143, 0.0, 1.0);
    }
    add_vectors(var18, var143, 2, var17);
    double var144[2];
    if (input[4] <= 0.013739950954914093) {
        if (input[9] <= 0.12298852112144232) {
            set_output2(var144, 1.0, 0.0);
        } else {
            set_output2(var144, 0.0, 1.0);
        }
    } else {
        set_output2(var144, 0.0, 1.0);
    }
    add_vectors(var17, var144, 2, var16);
    double var145[2];
    if (input[4] <= 0.011796427424997091) {
        set_output2(var145, 0.9994908385746883, 0.0005091614253116877);
    } else {
        set_output2(var145, 0.001517454196579004, 0.998482545803421);
    }
    add_vectors(var16, var145, 2, var15);
    double var146[2];
    if (input[4] <= 0.013739950954914093) {
        if (input[5] <= 0.10718116164207458) {
            set_output2(var146, 1.0, 0.0);
        } else {
            set_output2(var146, 0.0, 1.0);
        }
    } else {
        set_output2(var146, 0.0, 1.0);
    }
    add_vectors(var15, var146, 2, var14);
    double var147[2];
    if (input[4] <= 0.013739950954914093) {
        if (input[5] <= 0.07600340247154236) {
            set_output2(var147, 1.0, 0.0);
        } else {
            set_output2(var147, 0.16744343699686468, 0.8325565630031353);
        }
    } else {
        set_output2(var147, 0.0, 1.0);
    }
    add_vectors(var14, var147, 2, var13);
    double var148[2];
    if (input[5] <= 0.06354932487010956) {
        if (input[0] <= 0.12756529450416565) {
            set_output2(var148, 0.9990037495245169, 0.0009962504754831949);
        } else {
            set_output2(var148, 0.0, 1.0);
        }
    } else {
        if (input[3] <= 0.019591040909290314) {
            set_output2(var148, 1.0, 0.0);
        } else {
            set_output2(var148, 0.0010588702442754676, 0.9989411297557246);
        }
    }
    add_vectors(var13, var148, 2, var12);
    double var149[2];
    if (input[5] <= 0.06356324627995491) {
        if (input[3] <= 0.1118387971073389) {
            set_output2(var149, 1.0, 0.0);
        } else {
            set_output2(var149, 0.0, 1.0);
        }
    } else {
        if (input[4] <= 0.0079572475515306) {
            set_output2(var149, 1.0, 0.0);
        } else {
            set_output2(var149, 0.0, 1.0);
        }
    }
    add_vectors(var12, var149, 2, var11);
    double var150[2];
    if (input[3] <= 0.0371463168412447) {
        if (input[4] <= 0.027828927151858807) {
            set_output2(var150, 1.0, 0.0);
        } else {
            set_output2(var150, 0.0, 1.0);
        }
    } else {
        if (input[4] <= 0.00854429928585887) {
            set_output2(var150, 1.0, 0.0);
        } else {
            set_output2(var150, 0.0, 1.0);
        }
    }
    add_vectors(var11, var150, 2, var10);
    double var151[2];
    if (input[4] <= 0.013739950954914093) {
        set_output2(var151, 0.9984848484848485, 0.0015151515151514887);
    } else {
        set_output2(var151, 0.0, 1.0);
    }
    add_vectors(var10, var151, 2, var9);
    double var152[2];
    if (input[4] <= 0.013739950954914093) {
        if (input[9] <= 0.015251809731125832) {
            set_output2(var152, 1.0, 0.0);
        } else {
            set_output2(var152, 0.17332645870928934, 0.8266735412907107);
        }
    } else {
        set_output2(var152, 0.0, 1.0);
    }
    add_vectors(var9, var152, 2, var8);
    double var153[2];
    if (input[4] <= 0.011730728670954704) {
        set_output2(var153, 0.9994853631764189, 0.0005146368235810088);
    } else {
        if (input[1] <= 0.20808659493923187) {
            set_output2(var153, 0.8299940318867765, 0.17000596811322363);
        } else {
            set_output2(var153, 0.0, 1.0);
        }
    }
    add_vectors(var8, var153, 2, var7);
    double var154[2];
    if (input[4] <= 0.013739950954914093) {
        set_output2(var154, 0.9989898989898991, 0.0010101010101009919);
    } else {
        set_output2(var154, 0.0, 1.0);
    }
    add_vectors(var7, var154, 2, var6);
    double var155[2];
    if (input[4] <= 0.011796427424997091) {
        set_output2(var155, 0.9994840208845254, 0.000515979115474676);
    } else {
        set_output2(var155, 0.0009985184437531478, 0.9990014815562469);
    }
    add_vectors(var6, var155, 2, var5);
    double var156[2];
    if (input[4] <= 0.010405571665614843) {
        set_output2(var156, 1.0, 0.0);
    } else {
        if (input[8] <= 0.3322599232196808) {
            set_output2(var156, 1.0, 0.0);
        } else {
            set_output2(var156, 0.0, 1.0);
        }
    }
    add_vectors(var5, var156, 2, var4);
    double var157[2];
    if (input[5] <= 0.06356324627995491) {
        if (input[9] <= 0.09438046719878912) {
            set_output2(var157, 1.0, 0.0);
        } else {
            set_output2(var157, 0.0, 1.0);
        }
    } else {
        if (input[3] <= 0.019591040909290314) {
            set_output2(var157, 1.0, 0.0);
        } else {
            set_output2(var157, 0.0005227982051470724, 0.9994772017948529);
        }
    }
    add_vectors(var4, var157, 2, var3);
    double var158[2];
    if (input[4] <= 0.011730728670954704) {
        set_output2(var158, 0.9994900560938297, 0.0005099439061703298);
    } else {
        set_output2(var158, 0.0, 1.0);
    }
    add_vectors(var3, var158, 2, var2);
    double var159[2];
    if (input[4] <= 0.011730728670954704) {
        set_output2(var159, 1.0, 0.0);
    } else {
        set_output2(var159, 0.0004995004995004953, 0.9995004995004996);
    }
    add_vectors(var2, var159, 2, var1);
    mul_vector_number(var1, 0.0125, 2, var0);
    memcpy(output, var0, 2 * sizeof(double));
}
